### ISSUE TITLE
84614992 When a Syndicate name is updated, it is not updated in the UserID (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1002]
Issue reported by **REGManager** at 2017-09-06 08:09:52 UTC
Time: 2017-09-06T08:05:46+00:00
Session ID: 534c1b5a5eb8de7debfed11eed524d99
Problem Page URL: [/userid_details/5462b402e937907d7000002d?option=Select+specific+userid](/userid_details/5462b402e937907d7000002d?option=Select+specific+userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
When I update a syndicate name, such as the attached, the syndicate in the UserID is left hanging and still shows the old name.
In this example, LEI is now Doreen Olds, not John Holiston.
http://www13.freereg.org.uk/uploads/feedback/screenshot/59afad50f493fd314c78b34c/Capture.JPG    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59afad50f493fd314c78b34c/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Two points. 
I never have understood why you need to change the syndicate name just because you change the coordinator. The coordinator name is a field within the syndicate. Therefore is always available to any component of the software.
If a change IS made to the syndicate name then the system automatically propagates the change in syndicate name to the members of the syndicate. The screenshot does not provide an example of a profile that has not been changed.

**Comment by Captainkirkdawson** [comment]
Story #1402 has a much more useful description and will be the place where further comments re made
