### ISSUE TITLE
95373581 Website Problem (Ray Glen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1033]
Issue reported by **Ray Glen** at 2018-01-08 20:39:41 UTC
Time: 2018-01-08T20:37:09+00:00
Session ID: 2c4a80b4d71607a136056b57252cb84f
Problem Page URL: []()
Previous Page URL: [https://www.freereg.org.uk/contacts/new](https://www.freereg.org.uk/contacts/new)
Reported Issue:
This user has complained about downloading a virus from "your site".

http://www.rootschat.com/forum/index.php?topic=785245.0

I am willing to intervene, would you explain your side of the story?

Cheers
Ray Glen

I am [Ray] on Rootschat.com

    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5a53d70df493fd24c9622279/_old_)

**Comment by SteveBiggs** [comment]
The rootschat link shows that WinREG is being flagged as a threat. We've seen this before due to Windows not liking the name.

**Comment by edickens** [comment]
Which is why we are changing it to WinFreeREG.  As soon as we can get this version working everyone should move to it.

**Comment by FreecenBren** [comment]
Roots web have taken down most of their links due to issues.
Please see this updated link.
http://freepages.genealogy.rootsweb.ancestry.com/~bowbren/index.htm

All my freepages are down that I use for FreeCEN and those that Rena uses
 for Scotland plus about 200,000 users worldwide.
It has been like this since Christmas Eve.
We are innocent contributors to what we call this ‘outrage’

FreeCEN mailing lists are working but we cannot amend, add or delete
anything link failures etc.
We have to be patient while they check the issues at the above link.

There are lots of postings about this on the freepages mailing list.
Ancestry is the parent company.

**Comment by SteveBiggs** [comment]
@FreecenBren but that isn't connected to the WinREG issue is it?

**Comment by FreecenBren** [comment]
All I know is from all the postings on Freepages that  Rootsweb are
Checking  all links on their webpages and all those links on users of
Freepages on Rootsweb.
As they check them they will reset access to them on individual basis once
established that the sites checked do not have any security risks. This can
take months apparently. They are asking us all to be patient.
In the meantime we have bare with it.

It is strange that rootschat is showing a problem at the same time as
rootsweb have this problem.
So could there be a connection?
My knowledge of rootschat is nil. That is all I was thinking.

**Comment by SteveBiggs** [comment]
The link you provided from freepages on rootsweb says that they have been "in the process of improving the site throughout 2017" and "have spent the last few weeks reviewing the functionality", also you said, it has been like this since Christmas Eve.
The WinREG issue was first raised on rootschat last Sunday (7th Jan), so I can't see that there is a connection.

**Comment by FreecenBren** [comment]
It was Christmas Eve 2017 when we started to get errors that we could not
and still cannot remove from the the FreeCEN mailing lists.

I was posting about rootsweb issues so that all knew about the issue, only
because it could have a knock on effect to rootschat.
Not knowing if Rootsweb and rootschat are connected, and I do not use
WINREG only WINCC I bow down to your thinking.

**Comment by SteveBiggs** [comment]
Thanks Brenda, let's hope they sort their issues out soon.

**Comment by richpomfret** [comment]
Closing.
