### ISSUE TITLE
95536281 Creating a church name with a single quote loses the single quote and all characters up to the next space (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1037]
Issue reported by **STSCoord** at 2018-01-10 17:51:21 UTC
Time: 2018-01-10T17:47:44+00:00
Session ID: c647493f1883e538eb7a4eed4abc875f
Problem Page URL: [/churches/5a5651c0f493fd2fd49845d6](/churches/5a5651c0f493fd2fd49845d6)
Previous Page URL: [https://www.freereg.org.uk/churches/new](https://www.freereg.org.uk/churches/new)
Reported Issue:
I am trying to set up a church called "St Paul's Road Wesleyan Methodist".

The church name that is created is "St Paul Road Wesleyan Methodist".

There was, and still is, a St Paul's Road in Smethwick, spelt with the single quote.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5a565299f493fd2fd4984c82/_old_)

**Comment by Sherlock21** [comment]
I am inclined to side with you on this one, Michael.

The code to remove the apostrophe from church names was put there so we don't have the likes of St Paul's Church - which IS wrong.
I guess your example here was never though of in the original spec nor in the testing.
But if you done manage to get it fixed, then I suggest you use St Pauls Road etc. (without the correct apostrophe.)

**Comment by PatReynolds** [comment]
Amend documentation to reflect the need to use St Pauls Road (etc.).

**Comment by AlOneill** [comment]
@Sherlock21 @SteveBiggs @PatReynolds The current guidance on styling Church names is:

"For larger Places, it may be necessary to add a street name in order to distinguish one Church clearly from another. For example, for a Place with two Methodist congregations, one meeting in the High Street, the other in Winding Lane, the names should be styled as: Methodist (High Street), Methodist (Winding Lane). Two more unusual examples in the database are All Saints (North Street) and All Saints (Pavement), both being in York."

So, should the example above be "Wesleyan Methodist (St Pauls Road)" or should the guidance be amended?

**Comment by SteveBiggs** [comment]
@AlOneill the issue here is the fact that a single apostrophe is not accepted (e.g. Paul's vs Pauls). The update in documentation suggested is to explain this.

**Comment by AlOneill** [comment]
@SteveBiggs Yes, I realise that, but I wanted to check that the existing guidance is sound, especially as the example here is not using the suggested form.

**Comment by SteveBiggs** [comment]
I think the guidance is correct. The recommended format should be "Wesleyan Methodist (St Pauls Road)", but as always, there may be exceptions.

**Comment by Captainkirkdawson** [comment]
There are Methodists who are not  Wesleyan Methodists

**Comment by Sherlock21** [comment]
Exactly,Kirk

In the original item, the issue was how to get an apostrophe into a church name. Simple as that. And my answer up there said: Omit the apostrophe in that attempted church name of St Paul's.

The introduction of the extra Wesleyan work in the GUIDANCE NOTES is quite erroneous, as Kirk points our. 

The guidance is correct as it is. Please don't change it.
My answer to Michael  as in comment 2 above is still in my view sound as well. The number times when this will occur must be small, because this is the first time the issue has cropped up in the history of FR. 

So please leave everything as it is in terms of the guidance on church names

**Comment by AlOneill** [comment]
I have added a paragraph to explain how apostrophes are not accepted in the Church Name field.

You can view on production at https://www.freereg.org.uk/cms/information-for-coordinators/coordinator-actions#createChurch

Test3 has also been updated.

BTW, my comment was ambiguous re other aspects of the naming convention. I did not mean what others thought I meant, so no issue there!
