### ISSUE TITLE
101338852 Data Problem (Nancy Frey nee Davidge)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1053]
Issue reported by **Nancy Frey nee Davidge** at 2018-03-18 21:40:52 UTC
Time: 2018-03-18T21:40:17+00:00
Session ID: a66553f90782bd6f80d09fef691ef814
Problem Page URL: [unknown](unknown)
Previous Page URL: [https://www.freereg.org.uk/contacts/58185f0ae93790eb7fad1278/report_error?query=5aaedca2f4040b9e224442b3](https://www.freereg.org.uk/contacts/58185f0ae93790eb7fad1278/report_error?query=5aaedca2f4040b9e224442b3)
Reported Issue:
Surname of Groom is DAVIDGE.  My ancestors.    

![Screenshot](http://www.freereg.org.uk/uploads/contact/screenshot/5aaedce4f493fd865c597670/_old_)

**Comment by SteveBiggs** [comment]
This should not have been converted to an issue but sent to the Somerset coordinator to action. Can be closed.

**Comment by SteveBiggs** [comment]
Further details received. The problem reported is that soundex does not find entries that the researcher would expect. The example given is when searching DAVIDGE or DAVADGE, it does not find DAVAGE. Should it? Could it be made to?

**Comment by Captainkirkdawson** [comment]
Soundex is soundex and ever more shall be so.

Soundex basically strips the vowels plus  y, h, w from a name and creates a numerical code based on each of the remaining 3 characters (unless there are duplicates) and adds that to the first letter in the name.  There are some other rules. A soundex search then retrieves entries with the same code.
https://en.wikipedia.org/wiki/Soundex
A weak but useful system. 

Soundex searches for  DAVIDGE or DAVADGE are identical (after dropping the vowels). Neither will retrieve DAVAGE nor BAVIDGE for that matter. The first because it has 1 fewer consonant (3 notand the second because  it starts with a B and not a D 

Will we change it? Absolutely not since then it would not be a soundex search

**Comment by PatReynolds** [comment]
I might write a blog post (or someone else could...) explaining why learning more about soundex can really help improve your searches because the 'everyone knows' this-combination-of-letters-makes-this-sound rules are not the way SOUNDEX works, and thus you need to know how to search for DAVIDGE so that you'll find the DAVAGEs too.

**Comment by SteveBiggs** [comment]
The way Soundex works has been explained to the originator of this issue and they now understand that.
