### ISSUE TITLE
Add sitemap for FreeREG

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#1056]
Sitemap is very useful for tracking all of our pages (what's active) and user journey flow. Helps to identify 'blocks' and refine user experience. Original request via Denise/Rane

**Comment by Captainkirkdawson** [comment]
To what extent are you suggesting this? All our pages or just our public facing pages? If the latter are you asking for the inclusion of all detailed Refinery Help pages?.
In reality our menu bar is our sitemap. You cannot access any of the individual pages without having first gone to either. Search, Transcriptions, Help etc

**Comment by RohitLearner** [comment]
As a matter of fact, there are expansive no. of approaches to create and to represent sitemap.
Different sort of sitemaps:- 
https://speckyboy.com/collection-inspiring-sitemaps-user-flow-maps/
Different tools for Sitemaps:-
1. Customized one (Generally the best and take a long stretch of diligent work)
2. Slickplan
3. Dynomapper
4. WriteMaps 
5. https://www.lauyou.com/10-best-free-sitemap-generator/ (these are great and free as well) 
Along these lines, which one of them is your inclination for the site.

**Comment by richpomfret** [comment]
Public facing pages only. Researcher flow rather than transcriber (at least for this story). Thanks Rohit - shall review those and see if that saves a bit of time.

**Comment by richpomfret** [comment]
@DeniseColbert can you provide specific examples for how a sitemap might be used? What's required here that cannot be fulfilled within analytics already?

**Comment by RohitLearner** [comment]
Just as a suggestion. **Does our site need a sitemap?**
If our site’s pages are properly linked, Google's web crawlers can usually discover most of our site. Even so, a sitemap can improve the crawling of our site, particularly if our site meets one of the following criteria:

**Your site is really large.** As a result, it’s more likely Google web crawlers might overlook crawling some of your new or recently updated pages.
**Your site has a large archive of content pages that are isolated or well not linked to each other.** If you site pages do not naturally reference each other, you can list them in a sitemap to ensure that Google does not overlook some of your pages.
**Your site is new and has few external links to it**. Googlebot and other web crawlers crawl the web by following links from one page to another. As a result, Google might not discover your pages if no other sites link to them.
**Your site uses rich media content, is shown in Google News**, or uses other sitemaps-compatible annotations. Google can take additional information from sitemaps into account for search, where appropriate.

**Comment by Captainkirkdawson** [comment]
@RohitLearner  It is important to recognize that the FreeUKGEN  sites, FreeREG, FreeCEN and FreeBMD are simply search engine access to databases. Their publicly accessible webpages are minimal in number. For FreeREG those 3 or 4 pages are already indexed by Google using a sitemap https://github.com/FreeUKGen/MyopicVicar/blob/2a1defdc4882f0d8e5976ebdf910c1ab1f6ff96a/public/sitemap_location.txt
and providing  researcher access to the sitemap provides no additional value.  We severely restrict the ability of web crawlers to go walking through the site because they get no additional information and actually cause issues by doing their access in incorrectly formatted requests eg trying to access a search result without having done a search.
https://github.com/FreeUKGen/MyopicVicar/blob/2a1defdc4882f0d8e5976ebdf910c1ab1f6ff96a/public/robots.txt
![freereg](https://user-images.githubusercontent.com/2874694/38511800-8e31f962-3be6-11e8-8cc3-a21f39da77c1.JPG)
The reason for the "No information is available for this page." is that no one ever actually sees such a page. It immediately refers to the the actual search page

**Comment by DeniseColbert** [comment]
Site map was requested by Google Analytics volunteer Rane (@jiun0426). I can't seem to tag her to give her input here - not sure why? Will link to the story on Slack and see if she can comment. 

eta: tag seems to have worked!

**Comment by Captainkirkdawson** [comment]
@DeniseColbert you should point Rane to my response to Rohit above

**Comment by richpomfret** [comment]
@DeniseColbert any further input? If not we will close this - Kirk mentions that we have a sitemap within google analytics.
