### ISSUE TITLE
Manuals and Document to study for GSoC 2018

### ISSUE THREAD

**Issue by RohitLearner** [FreeUKGen/FreeUKRegProductIssues#1061]
@Captainkirkdawson  @richpomfret @benwbrum 
Amid this period of GSoC 2018, which manuals, records, videos and website to which we should allude to enhance the comprehension of FreeUKGen work? Particularly identified with Data Visualisation; which resources should we use to grab the input, working and the big picture of FreeUkGen Transcription? Just asking as the enthusiast.

**Comment by PatReynolds** [comment]
Hi @RohitLearner www.freeukgenealogy.org.uk is a good place to start for 'the big picture' of what Free UK Genealogy does.  We have a few videos on our Youtube channel https://www.youtube.com/channel/UCP839R-ftWroUjqv9f02aTg
Probably the best way to start to become familiar with our sites is to use them.  E.g. I just tried a surname search for Singh on FreeCEN2 - some interesting families there!  You could see if you could pick them up in FreeBMD or FreeREG.  
We have a facebook page: https://www.facebook.com/freeukgen There is also a group for those involved with the site as volunteers or researchers: https://www.facebook.com/groups/FreeUKGEN.FreeREG/ which will give you some idea of the work being done, barriers met, etc.
There's a brief introduction to the records here: http://www.nationalarchives.gov.uk/help-with-your-research/research-guides/birth-marriage-death-england-and-wales/ (they also have a page on censuses).  Since the National Archives don't hold the Church of England registers, that bit is weak - here is more detailed: https://www.familysearch.org/wiki/en/England_Church_Records  NB Scottish records are different - https://www.familysearch.org/wiki/en/Scotland_Genealogy

**Comment by RohitLearner** [comment]
@benwbrum @PatReynolds Thanks in order for the assets. I truly appreciated the post on twitter (https://twitter.com/FreeUKGen) particularly https://twitter.com/FreeUKGen/status/976173840190582784 ). What's more, I additionally have a suggestion for the site (https://freecen2.freecen.org.uk/) in regards to the option of adding gif in the page. This method can be extended to https://www.freebmd.org.uk/cgi/search.pl; which will increase user experience. Please ignore if this idea is already discussed or rejected. Much obliged for the reply. What's more, would I be able to know who is the web developer or designer of this astounding site?

**Comment by PatReynolds** [comment]
@patreynolds to reply on slack
