### ISSUE TITLE
104581075 Film and Image Columns added (was "Corrupted Downloads") (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1064]
Issue reported by **nejws05** at 2018-04-25 10:17:55 UTC
Time: 2018-04-25T10:12:23+00:00
Session ID: 93bd3c93f2e4111a90f73dbadad3501e
Problem Page URL: [/registers/5409e36ceca9eba2065569ac](/registers/5409e36ceca9eba2065569ac)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5ae04bfaf493fd0182f37469](https://www.freereg.org.uk/freereg1_csv_files/5ae04bfaf493fd0182f37469)
Reported Issue:
One of my transcribers computer expired, he downloaded his current batch, but  It would not be accepted by Winreg.
After much head scatching I discovered that all batches have had two extra fields attached and ANY download is now useless without modification. Can these "upgrades" be tested properly..
Eric Wealleans Northumberland Coordinator    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5ae055d3f493fd0aa0132a24/_old_)

**Comment by SteveBiggs** [comment]
Through some quick testing, it would appear that files that were uploaded without the Film/Fiche number and Image number present (and no +LDS header line) are being downloaded WITH those columns added, so WinREG flags all entries as errors due to their being too many fields.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs  @edickens @Sherlock21 
Would an acceptable solution be to add the +LDS header ? then winreg should not object

**Comment by SteveBiggs** [comment]
Yes that should be acceptable to both WinREG and WinFreeREG.

**Comment by Captainkirkdawson** [comment]
Fix applied and deployed in both test2 and test3

**Comment by richpomfret** [comment]
@Sherlock21 can you give this a test?

**Comment by Sherlock21** [comment]
If this story is about Winreg files ( as indicated in the text of the first comment, thenI can't do any work on this for you.Sorry.

 Winreg is not designed to run on a Mac.

**Comment by Captainkirkdawson** [comment]
@Sherlock21 The basic test is does a download of an old file now include both the +LDS and 2 film fields

**Comment by SteveBiggs** [comment]
I just downloaded an old file on test3 that didn't originally have image fields and the downloaded file did include both the +LDS and 2 (blank) film fields, so looks good.

**Comment by Sherlock21** [comment]
In T3 I found a file of mine that was Old Stye with  LDS field values.

This downloaded fine - the 2 LDS field values  were shown in cols P and Q correctly.

Edits the above file online, to remove the LDS fields ( because I could not readily find one that had no LDS fields  populated) and downloaded that.

It downloaded OK
Viewed in a spreadsheet it looked OK

Viewed in a Text editor app, it showed there were fields O, P & Q at the end of each record in the file, but which had no data. Correct
But - in this example there was no data in col O in the original.
Not sure if they ( these 2 fields P & Q were meant to be there or not?

**Comment by Captainkirkdawson** [comment]
TY
Sounds like it does what it should

**Comment by richpomfret** [comment]
Ready for deployment.
