### ISSUE TITLE
106524029 Contact my coordinator (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1071]
Issue reported by **edickens** at 2018-05-17 22:00:29 UTC
Time: 2018-05-17T21:55:06+00:00
Session ID: 14d8d1a07468ded69a4e090d4b4a5994
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/assignments/5462b420e937907d7000055b/list_assignments_of_myself](https://www.freereg.org.uk/assignments/5462b420e937907d7000055b/list_assignments_of_myself)
Reported Issue:
I've just been in contact with a new transcriber who has registered then asked "What happens now?".
May I suggest that there is an Action to contact their SC.  They should always go there first for any question, not just for assignment of work.  There may be a link somewhere, but it needs to be very visible especially for new transcribers, and specific to their SC, .
EricD    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5afdfb7df493fd61e761e691/_old_)

**Comment by PatReynolds** [comment]
Does #1350 cover this? If so, please close.

**Comment by edickens** [comment]
Not really, but it is a similar problem.  I'm suggesting here that there is something more positive for those who have registered and is part of the logged in Actions screen.  This also needs to be more important for the SC to deal with.  Today I've had a problem with a new transcriber who has not heard from their SC, I expect because they have never made contact before and the SC has never given them work, so has not seen the message as important.  So these very important emails, which are not part of the message system, must not get lost in the traffic.
#1350 is for anyone to contact a CC.

**Comment by richpomfret** [comment]
Adding further info into 1350 and closing.
