### ISSUE TITLE
106843424 Stray baptism not present in any batch (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1074]
Issue reported by **brobinson43** at 2018-05-21 14:43:44 UTC
Time: 2018-05-21T14:29:46+00:00
Session ID: 85eeb61e4ab7acdb8342b0f79fcb670c
Problem Page URL: [/registers/59aba93bf493fd0a57bd051d](/registers/59aba93bf493fd0a57bd051d)
Previous Page URL: [https://www.freereg.org.uk/churches/599e8adcf493fd8fe2a333f1](https://www.freereg.org.uk/churches/599e8adcf493fd8fe2a333f1)
Reported Issue:
The place Coleshill WAR, church SS Peter & Paul register PR has a baptism in the decade 1530-1539 (possibly a zero year entry -- see screen shot attached) but no such record is shown in any of the four batches making up this part of the register.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5b02db20f493fd61e77ce314/Screen_shot_2018-05-22_at_12.35.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b02db20f493fd61e77ce314/Screen_shot_2018-05-22_at_12.35.jpg)

**Comment by Captainkirkdawson** [comment]
Things have clearly changed since this report was entered.
![register](https://user-images.githubusercontent.com/2874694/42243779-b78adcbc-7ecf-11e8-9b1b-5c32d7c38ebc.PNG)
And there are 2 files showing nil start entries
![files](https://user-images.githubusercontent.com/2874694/42243834-d8b20fdc-7ecf-11e8-9386-abc04fbc76bd.PNG)
If one looks at the marriage file with the nil entry it is
![marriage](https://user-images.githubusercontent.com/2874694/42244845-c57aac90-7ed3-11e8-9129-a205735df4c3.PNG)
There is one record that causes the nil entry it is a date with an uncertain character
![nil year](https://user-images.githubusercontent.com/2874694/42244883-ee9ab250-7ed3-11e8-933f-4bda07e70112.PNG)
Looking at the baptism file
![baptism](https://user-images.githubusercontent.com/2874694/42245104-c8311e1e-7ed4-11e8-9c57-110450410cb5.PNG)
This has 50 entries that result in a nil value because of a ucf date.
I suspect that the record with 1848 is an error
![201](https://user-images.githubusercontent.com/2874694/42245260-58fbaf2c-7ed5-11e8-8fec-325925795a24.PNG)

There is little more that I can do due to the limitations of dealing with UCF dates

**Comment by richpomfret** [comment]
@SteveBiggs to review/check.

**Comment by SteveBiggs** [comment]
I don't think the nil entries feature in the summary tables. The baptisms file does indeed have 41 records in the 1530's and the marriages file has 12. (Interesting that the BA table shows one less - 40).

But I agree with Kirk that this has been overtaken by changes.
