### ISSUE TITLE
110372553 Improve the list batches report (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1089]
Priority (0 6  8 5 ) 19

Issue reported by **REGManager** at 2018-07-01 11:02:33 UTC
Time: 2018-07-01T10:56:33+00:00
Session ID: 346ce9d6df04ba3484de8cd4247aceb8
Problem Page URL: [/freereg1_csv_files](/freereg1_csv_files)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action](https://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Is it possible to add columns for the Year From and Year To entries to each batch on this "List Batches" report?
I ask because it will then be possible to transfer this list to a spreadsheet, sort it, and then use it to set the Image Groups to Completed when necessary.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b38b4c9f493fd96f88d4b11/_old_)

required by #1102

**Comment by richpomfret** [comment]
Steve/Eric to review and assess how we might do this. Export with extra columns?

**Comment by edickens** [comment]
Steve and I think that a separate report is best.  If the two columns cannot be fitted in, and we think that there is enough room if you look at the width of the breadcrumbs, then omit the Actions.

**Comment by edickens** [comment]
Background.
When Bev set up the Image Groups, and we checked them, most were set to "Available", because we do not know if they have been transcribed.  This means that they show in the "Available" report under "Assignments" as "Not yet transcribed".   Until this report  is correct, or at least more uptodate, we cannot ask transcribers to use this and so we cannot ask them to use the Image Server System.  This report triggers a request for transcribing work.
To get it uptodate CCs need to change the Image Group from "Available" to "Completed" when necessary.  But to do this at present it is necessary to go to about six screens for each Image Group, and there are thousands to be done.  But if the "List Batches" report has the start and end year, it can be skimmed and put into a spreadsheet and sorted.  This can then be compared with the Image Group, which does show the years, and edited accordingly.  A one click operation.
We do have a lot of images that are waiting to be transcribed but do not have an accurate report on what they are, and we should get many more images soon.  So this needs doing before the new images arrive.
Not many CCs are doing anything towards the Image System at present.  We need to get them all working on it.
This is more important than getting statistics on the use of the Image System.

**Comment by Captainkirkdawson** [comment]
@edickens  @SteveBiggs  @Sherlock21 
Deployed the first reformat of the display to test2 for evaluation
Added the start and end year columns
Have eliminated the Zero Year column and made a 0 start year as an active link to the entries
Have fixed #1498 at same time we use the Register type code consistently to  reduce space usage
Since this is the MOST heavily used display PLEASE REVIEW CAREFULLY
Note it is ONLY test2

**Comment by Captainkirkdawson** [comment]
ps changed format of date to save space and it is now the date the file was last processed which was story #791

**Comment by edickens** [comment]
Getting this error.  I  thought it was because I chose a county with no data, but same with SSX.
![capture](https://user-images.githubusercontent.com/8876165/44269707-45053f80-a22d-11e8-8140-703761060795.JPG)

**Comment by Captainkirkdawson** [comment]
Fixed please retry raises an interesting question on why there is no processed date

**Comment by edickens** [comment]
**Great.**
UserID and Reg columns could be narrower and Church wider.
Not sure of the sequence as there is one out of sequence at the top.  But does not matter if we copy and paste to a spreadsheet.
Can the column headings be outside the scroll area so that they do not scroll?  But at least they line up properly here.
Are the missing processed dates because they came across from FR1?

**Comment by SteveBiggs** [comment]
Looks good.

The ones with no processed date do look like they are very old files from FR1.

**Comment by Captainkirkdawson** [comment]
Will look at a fixed header but remember that will have alignmenment issues. 

Also will look at userid and reg widths.

2 options on the empty processed date. 1) we revert to uploaded date 2) if the processed date is missing we use the uploaded date

**Comment by edickens** [comment]
Or option 3) leave blank as now.  Not a serious problem unless people keep asking why.

**Comment by Captainkirkdawson** [comment]
@edickens yes that is an option. The database on test2 is very old and out of date so not a great test for those decisions

You commented "Not sure of the sequence as there is one out of sequence at the top. " To what are you referring ??????

**Comment by edickens** [comment]
My mistake.  The fist file is SSS not SSX:-
The SSX List Batches by filename starts:-
![capture](https://user-images.githubusercontent.com/8876165/44290852-9e439200-a272-11e8-8c0f-d9c5535e5520.JPG)
But why is this filed under SSX?

**Comment by SteveBiggs** [comment]
Not sure, but I've removed it and uploaded correctly named alternative.

**Comment by Captainkirkdawson** [comment]
Thank you I propose to ignore. Filenames can be anything as fair as FR is concerned

**Comment by Captainkirkdawson** [comment]
I think userid and Reg are already at minimum width

**Comment by edickens** [comment]
Yes, the report looks fine now.  Go for it.

**Comment by Captainkirkdawson** [comment]
@edickens There is one request you made that has not been addressed yet

_Can the column headings be outside the scroll area so that they do not scroll?_

**Comment by edickens** [comment]
Not that im[important and as they are they will align properly.

**Comment by Captainkirkdawson** [comment]
Does that mean the requirement for fixed headers does not exist?
I would prefer not to have fixed headers as we page the results for those people with "hundreds of batches" and I have never done fixed headers for paged tables

**Comment by edickens** [comment]
Leave as is now.  Done.  Thanks.  ED

**Comment by Captainkirkdawson** [comment]
@edickens @SteveBiggs @Sherlock21 
I have cleaned up the code. I have also used additional information to update the processed date if it was missing. This MAY mean the initial display is a little slower but it will help in future accesses.
This display MUST be reviewed before we pull into production

**Comment by edickens** [comment]
No problems in Test2.  I have tried different Counties as well.

**Comment by SteveBiggs** [comment]
Looks good to me too.

**Comment by richpomfret** [comment]
Ready to deploy.

**Comment by SteveBiggs** [comment]
Deployed, tested and good. Can close.
