### ISSUE TITLE
111417504 Unable to view download listed images (Mary)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1100]
Issue reported by **MaryKay** at 2018-07-13 13:18:24 UTC
Time: 2018-07-13T13:11:25+00:00
Session ID: 4a1a466ea1bc3f35db45cbe4dc4d8757
Problem Page URL: [/image_server_groups/5a9ebb18f493fdbfcb925e48/index](/image_server_groups/5a9ebb18f493fdbfcb925e48/index)
Previous Page URL: [https://www.freereg.org.uk/sources/5a9ebb18f493fdbfcb925e48?image_group_filter=](https://www.freereg.org.uk/sources/5a9ebb18f493fdbfcb925e48?image_group_filter=)
Reported Issue:
I have tried to view or download several images from Wisbech_St Peter-Digital PR/CAM-WisbechStPeter-BA-1860-1876-1-007625332 	& Wisbech_St Peter-Digital PR/CAM-WisbechStPeter-BA-1876-1908-2-007625332.  I get this message:
There was a problem with your request. There is no file CAM-WisbechStPeter-BA-1876-1908-2-007625332_00295.jpg     

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5b48a6a0f493fdb1c2305261/_old_)

**Comment by SteveBiggs** [comment]
If you go directly onto the IS via 'Access Image Server Directly' the images can be viewed, but going via 'Image Server' -> 'Image Groups', they give the error Mary reports.

I think it may be a problem with the folder name they are in on the IS - Wisbech_St Peter-Digital PR?

**Comment by edickens** [comment]
It is there:-
![capture](https://user-images.githubusercontent.com/8876165/42699542-f6c35b8e-86b8-11e8-8994-b1c0ae082403.JPG)
I can't see anything wrong.

**Comment by SteveBiggs** [comment]
Yes it's there because you can view it via 'Access Image Server Directly', but is there a problem with the folder name? Maybe the underscore?

**Comment by SteveBiggs** [comment]
... or is it the dash in the folder name? It looks like all groups in a folder with a dash have this problem.

**Comment by AlOneill** [comment]
At the risk of sounding like a pedantic teacher, they are **hyphens**, not dashes, which are longer (and mean something different than a hyphen).

I suggest it would be helpful to all if we train ourselves to use the correct names.

**Comment by SteveBiggs** [comment]
I'm sure you are correct Alison, but if we were to comment on every grammatical or punctuation error in people's posts, we wouldn't have time left to actually fix the issues :-)

**Comment by AlOneill** [comment]
@SteveBiggs I am not commenting on a grammatical or punctuation error, but on an error in terminology. The issue of hyphens vs dashes happens to be something that matters in transcriptions: if we use the terms interchangeably, how can we expect others to get it. That's all.

**Comment by SteveBiggs** [comment]
@AlOneill I've been involved in transcribing for over15 years and the difference between hyphens vs dashes has NEVER come up as an issue. Transcribers type what they see not what it's called.

**Comment by AlOneill** [comment]
@SteveBiggs Fair enough, but others have seen this an an issue. See
https://www.freereg.org.uk/cms/information-for-transcribers/creating-a-transcription-file#spreadsheet
particularly the section on Autocorrect.

Apologies for taking this way OT.

**Comment by SteveBiggs** [comment]
Understood Alison. I can see it can be an issue. I apologise for making a big deal of it.

Let's focus back on the problem which is why can't these images be viewed or downloaded when the IS folder has a hyphen in the name?

**Comment by Captainkirkdawson** [comment]
@AlOneill  @SteveBiggs it was nice to see the posts of 2 mature people.
@AlOneill it was good to read your documentation on the issues associated with punctuation. It might be useful to write a story on the search issues I am sure we can use emendations to handle them

**Comment by SteveBiggs** [comment]
Another similar problem With this image group (and there is no hyphen in the folder name this time):

![image](https://user-images.githubusercontent.com/25303607/43687815-42ee42ee-98d4-11e8-8daa-0f16ae11b318.png)

If you list (LS) images and try to view or donwload you get an error:

![image](https://user-images.githubusercontent.com/25303607/43687825-6ff6cfae-98d4-11e8-9d34-4a43e2e55463.png)

but if you go into the image server directly 

![image](https://user-images.githubusercontent.com/25303607/43687835-a6b363ae-98d4-11e8-8937-8bb33ffb7d4c.png)

you can see all the images:

![image](https://user-images.githubusercontent.com/25303607/43687842-c8735f3a-98d4-11e8-8868-5f29ae7f7a8f.png)

We need a resolution to this urgently because the SC cannot assign these images.

**Comment by Captainkirkdawson** [comment]
Sorry but have been casing the other urgent issues

**Comment by Captainkirkdawson** [comment]
Looking at the logs for the image server. The request that is coming through is 
Parameters: {"chapman_code"=>"CAM", "folder_name"=>"Chesterton PR", "image_file_name"=>"CAM-ChestertonStAndrew-GR-1564-1682-1-001.tif", 
The actual folder name on the image server is {"chapman_code"=>"CAM", "folder_name"=>"Chesterton_St Andrew PR", "image_file_name"=>"CAM-ChestertonStAndrew-GR-1564-1682-1-001.tif"
An examination of the source record for Chesterton St Andrew PR shows that the folder name is actually stored as Chesterton PR so the code is functioning correctly. The problem originated when the source record was initially created on "2018-03-06T15:57:58.478Z". So we have 2 choices change one of the folder names so that they match either the one stored in the source record or the one on the image server. Likely an edit of the folder name on the source is the most appropriate solution

**Comment by Captainkirkdawson** [comment]
The original problem from Mary is more complex.
There is just ONE source for Wisbech St Peter that has a folder name of Wisbech_St Peter PR.  Yet the image server has 3 physical folders Wisbech_St Peter PR, Wisbech_St Peter-1 PR  and  Wisbech_St Peter-Digital PR. All Image Server Groups and their images are stored under that the one source Wisbech St Peter and its folder Wisbech_St Peter PR. Hence any attempt to view or download the images in the other 2 physical folders will fail.

**Comment by Captainkirkdawson** [comment]
The original specification called for the support of multiple sources for a specific register. However the system as implemented only supports one source for the image server. Other sources were expected to be on different servers and their support has not been fully implemented. In addition it would appear that all sources for a register on the image server while separated into specific Image server groups are expected to have their images located in the first physical folder for that source.

**Comment by Captainkirkdawson** [comment]
**In fact it is now clear that these 2 examples of the issue are directly related**. The first physical file for Chesterton is actually Chesterton PR. The other 4 physical files Chesterton-Rescans PR, Chesterton_St Andrew PR, Chesterton_St Andrew-Rescans PR and Chesterton_St Andrews PR (note the s) have their image server groups and their images are expected to be in the first physical folder which is Chesterton PR. Hence my original suggestion of how to fix this is incorrect since changing the folder name to one of the others would leave the other images in the different physical folders inaccessible. 
A quick scan of Cambridge shows that this is a widespread issue. Nor is the issue restricted to Cambridgeshire!

**Comment by edickens** [comment]
I agree with this assessment of the problem.
I have just fixed NBL Blanchard by downloading and uploading again int a new IG.  The images then go in the first Place/Church/Register Type folder.
But, as Kirk says, there are a lot like this where there are different folders for different Batches, a legacy from the past.
I can easily move these images into the first relevant folder, but will this upset anything else? Perhaps we need to experiment somewhere?

**Comment by edickens** [comment]
This is CAM Chesterton:-
![capture](https://user-images.githubusercontent.com/8876165/43705971-fc1ebd70-995b-11e8-8586-c9608df7b268.JPG)
The tif images are not needed as they have been re-scanned as jpg.  I could copy all the useful images into the first folder and see what happens.  If that is OK, then I could delete the other folders.

**Comment by SteveBiggs** [comment]
@edickens that sounds like a good approach. Copy the required images into Chesterton PR then we can ask Mary to check she can now access them.

Thanks @Captainkirkdawson for the rapid and thorough investigation and explanation of the issue.

**Comment by Captainkirkdawson** [comment]
@edickens I would recommend proceeding with caution. I believe that moving the files into the first folder will work. The only issue I see is if there are actually 2 churches in the place. Then exploration is needed to access the actual database/physical file set up. To help in this we could display the physical location in the source document show. Perhaps this should be restricted to the system administrator. We could also make this editable just for the system administrator.

**Comment by edickens** [comment]
Mary is now able to view all Chesterton images.  But I have not checked if Allocation and Assignment works.
What I did will be in a separate email.

**Comment by edickens** [comment]
What now?  I suggest that I consolidate all Places with one Church but multiple folders on the Image Server into the first folder, and leave the other folders there but empty.  If necessary, we will know what has been in each folder from the images listings in the IGs.
This should make all images viewable through the website.

**Comment by SteveBiggs** [comment]
Sounds reasonable to me.

**Comment by Captainkirkdawson** [comment]
There will be no impact on Assignments and Allocation as these make no use of the physical location information.
It is ONLY view and download that access the physical location. Also the Manage Image Server action of course but that does not use any aspect of the application.

**Comment by edickens** [comment]
I will start on what I have suggested earlier.

**Comment by Captainkirkdawson** [comment]
@edickens I am totally confused by your private emails and your posts here as to what is a problem and what is not. As a result until you document an issue either in this story or in another I propose to do nothing.

**Comment by edickens** [comment]
All have now been "fixed".  Let me know if anyone cannot see an image.
Can be closed.

**Comment by Captainkirkdawson** [comment]
Thank you @edickens
