### ISSUE TITLE
124056325 Last updated date shows 12 Dec 2018 ( on 6 Dec 2018) (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1146]
Issue reported by **ericb** at 2018-12-06 20:05:25 UTC
Time: 2018-12-06T20:02:09+00:00
Session ID: 3fbdd3d6b333fc3ebd6fbd43a97a8374
Problem Page URL: [/manage_counties/place_range?params=H](/manage_counties/place_range?params=H)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places](https://www.freereg.org.uk/manage_counties/selection?option=Work%20with%20Active%20Places)
Reported Issue:
I Just uploaded some files in DEV / Harpford
and notice the Last changed date is now IN THE FUTURE
http://www13.freereg.org.uk/uploads/feedback/screenshot/5c098105f493fd0566f8f4a7/Future_Last_Changed_date.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5c098105f493fd0566f8f4a7/Future_Last_Changed_date.jpg)

**Comment by Captainkirkdawson** [comment]
Because you uploaded a file with that information

+INFO,,PASSWORD,SEQUENCED,MARRIAGES,UTF-8,,,,,,,,,,,,,,,,,,,,,,,,,,,,
#,CCC,Eric Booker,"Yorkshire, West Riding",DEVHPDMA1,,8 Nov 2018,,,,,,,,,,,,,,,,,,,,,,,,,,,
#,CREDIT,Eric,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
#,12 Dec 2018,Images by E Booker,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
#,DEF,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
chapman_code,place_name,church_name,registe
