### ISSUE TITLE
130507921 There is something wrong with this display (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1180]
Issue reported by **STSCoord** at 2019-02-19 12:12:01 UTC
Time: 2019-02-19T11:49:03+00:00
Session ID: 21e199af83b17001f2fa534753d9dd68
Problem Page URL: [/freereg1_csv_entries?locale=en](/freereg1_csv_entries?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/5c656824f493fd38ce0c5fe9?locale=en](https://www.freereg.org.uk/freereg1_csv_files/5c656824f493fd38ce0c5fe9?locale=en)
Reported Issue:
While trying to investigate a totally unconnected problem, I came across this problem.

Look at the column headings in comparison to the details in the columns.

They are not just badly aligned with the details (this should be remedied, somehow but is not the cause of the problem).

No, there is a misleading column name, possibly due to the implementation of  Flexible-CSV.

This column name? "Person Surname". And this is represented by the very narrow column below it. This is very confusing because, theoretically, this column should be the single character for "Sex".

The fault makes it look like the Person Surname for record #3 is "Herbert Edgar".

This had me puzzled for quite some time before I realised what the problem is.
https://www.freereg.org.uk/uploads/feedback/screenshot/5c6bf291f493fd247d7ab425/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

E0, U4, S8, C7: P19

**Comment by SteveBiggs** [comment]
The 'Person Surname' field has no entries so the column is very narrow. Can it be made wider so that the headers line up better?

**Comment by Sherlock21** [comment]
I: agree with Michael: the onscreen layout of a typical batch contents, is not the best it could be, and often, its totally confusing.

here is an example I am just uploading.

here there are no emply fileds to confuse things.
yet the headings are well off set relative to the column it belongs to.

This example is from an old style LDS file
My suggestion - meant to be helpful rather than just critical,  is ad follows:-
SO as not to make the file names row into a double row ( or worse) - to allow most record to be displayed at a time -
I suggest abreviating the column headers:
Rec_No
Mar_dte
Bride_Fn
Bride_Sn
Groom_Fn
Groom_Sn

etc thus saving up to a third of the line length per field. Reduce the font a point or two, and save even more.
If you really must wrap the field names to make sufficient savings, then reduce the clear space above and below this text soa s to tak up no more column length tahn at present.

So long as the colour remains distingly different to the record contents, it will be clear what they mean if dont correctly













On 19 Feb 2019, at 12:59, Stephen Biggs <notifications@github.com> wrote:

The 'Person Surname' field has no entries so the column is very narrow. Can it be made wider so that the headers line up better?

**Comment by SteveBiggs** [comment]
@Sherlock21 you didn't attach your example.

**Comment by Sherlock21** [comment]
Sorry, Steve - I thought that I did.

here it is here.













On 20 Feb 2019, at 12:52, Stephen Biggs <notifications@github.com> wrote:

@Sherlock21 you didn't attach your example.

**Comment by SteveBiggs** [comment]
Not sure what's happening Eric, but it's still not showing.

Steve

Stephen Biggs
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
@SteveBiggs @Sherlock21 The tables have been fixed so column headers line up with data in display of entries; applies to all 3 record types

**Comment by Sherlock21** [comment]
Thank you.

**Comment by Sherlock21** [comment]
Thank you.
