### ISSUE TITLE
133813739 transcriber credit (Julie )

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1204]
Issue reported by **JulieHarold** at 2019-03-29 18:28:59 UTC
Time: 2019-03-29T18:25:12+00:00
Session ID: ae1d617e79e0a911702105ccfe956f83
Problem Page URL: [/freereg1_csv_files/546384a2e937904abb10eb9f/edit?locale=en](/freereg1_csv_files/546384a2e937904abb10eb9f/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_files/546384a2e937904abb10eb9f?locale=en](https://www.freereg.org.uk/freereg1_csv_files/546384a2e937904abb10eb9f?locale=en)
Reported Issue:
I am finding a number of files where I am being credited rather than the person given in the headers   
eg
Transcriber name Anona Needham
Transcriber email freereg-norfolk@highfields1.plus.com
Credit Person Julie Harold
Credit Person's email address anona@amneedham.eclipse.co.uk
Comments about the batch corrected by Julie Harold

search for Reeder 1767 Norfolk 

Baptism entry
Field 
(only fields with a value are shown)	Value
County	Norfolk
Place	Great Ellingham
Church name	St James
Register type	Parish Register
Baptism date	24 May 1767
Person forename	Peter
Person sex	M
Father forename	Peter
Mother forename	Esther
Father surname	REEDER
Film	4143502
Film Number	1202
Transcribed by	Julie Harold
Credit	Julie Harold
File line number	281
Line id	Norfolk.NFKGELBA1.CSV.281
Processed date	29 Mar 2019

Julie Harold Norfolk coordinator    

![Screenshot](https://www.freereg.org.uk)

Needs research: what did we decide it should do, what does it do, and what should it do?

**Comment by SteveBiggs** [comment]
The 'Credit to' name is being shown as the Transcriber in the search result.

**Comment by edickens** [comment]
The header information in the help needs updating:-

https://www.freereg.org.uk/cms/information-for-transcribers/file-headers

It says some fields are essential when they are not now.

**Comment by SteveBiggs** [comment]
@edickens could you open a new issue with that help documentation change?

**Comment by Captainkirkdawson** [comment]
The basic issue is that with the introduction of the GDPR  we were required to offer the transcriber with the options of a) not having their work acknowledged and b) to enable them to use a pseudonym rather than their actual name should they chose. 

This could only be done with the the userid collection for the transcriber.  The transcriber name in a header is freeform and unverified. In many cases it did not match any name in the userid collection.  This meant that we commenced using the name of the transcriber as contained in their userid for the files that they had uploaded.  

It appears that the Julie is placing transcriptions under her own userid when making corrections hence it is her name that shows up in the transcribed_by field as shown in the story description. There is NO easy solution to this matter.  
a) The cleanest is that coordinators who have moved files into their own folders be asked to move them back. That way the process will work as designed. I do not that Julie has 1156 files so no simple task for her. I do not know the extent to which it is an issue for other coordinators. The system resource impact is minimal.
b) An alternative is to determine if the userid of the file owner is a coordinator. If it is then we use the header transcriber name  and if not we use the userid information. This is unclean as leaves the underlying problem unresolved which could bite us in the future. It means the GDPR is NOT applied to those transcribers

In researching this matter there are several additional comments
1) We do not appear to have notified coordinators or transcribers of this change.
2) The Transcriptions coverage code was never updated to conform with the GDPR
3) There does not appear to be any help material for Transcribers or Coordinators on the on-line editing processes for entries and batches 
4) There does not appear to be any Help advice for coordinators on best practices for editing batches off line that strongly recommends editing and replacing a transcribers batches in the transcribers folder.
Could @PatReynolds @edickens @SteveBiggs @AlOneill please review points 1-4 as well as a and b.
Based on the response to the review  either option a or b will be pursued in this story and new ones written for 1-4 if deemed required.

**Comment by Captainkirkdawson** [comment]
Story #1983 added for point 2)

**Comment by richpomfret** [comment]
@PatReynolds to check on point 3 & 4 (we think we do have this already). If not, we'll create new stories to cover them.

**Comment by richpomfret** [comment]
@SteveBiggs to reply back to Julie.

**Comment by PatReynolds** [comment]
Nothing I could see online for points 3 or 4.
Stories made for point 3 transcribers (#1990) and coordinators (#1991).
Story made for point 4 (#1992)

**Comment by SteveBiggs** [comment]
Reply sent to Julie.

**Comment by edickens** [comment]
Close?  It is up to SCs to ensure that the right information is entered.  Will be superseded by online data entry and better upload screen when links to image groups and other header information can be verified.
