### ISSUE TITLE
Records retrieved in Search not updated

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeUKRegProductIssues#1216]
Yesterday I amended a record for Joseph Peel in Spofforth burials. A search on this entry now retrieves two Joseph Peels, one of which has an error message quite confusing for researchers.
Why is this please?
![Wrong data](https://user-images.githubusercontent.com/10379655/59911249-5c8ff480-940b-11e9-8588-f3524d84e585.jpg)

**Comment by Captainkirkdawson** [comment]
Cannot research with information on what process was followed in amending the record. Without such information research is impossible. ie was it on-line edit , batch replacement, file deletion followed by file uploading

**Comment by richpomfret** [comment]
@SteveBiggs to get in contact and request more specific info on process followed leading to the issue.

**Comment by suffolkroots** [comment]
This was an online edit

**Comment by Captainkirkdawson** [comment]
Similar to #1236

**Comment by Captainkirkdawson** [comment]
Unable to confirm that fix to #1236 avoids this problem as there is still no information on what was edited

**Comment by edickens** [comment]
Data problem 144087575 of 2019-07-26 was the start of the problem.  I have since changed the year of baptism and year of birth of Rianda.FIFKENBA3.CSV.1209 which is FIF Kennoway BA Ann TURPIE 11 May 1817.
Search now gives three entries.  One extra created for each amendment...
![Capture](https://user-images.githubusercontent.com/8876165/63371686-79e62e00-c37c-11e9-90d6-4d60374ec498.JPG)

**Comment by Captainkirkdawson** [comment]
This is fixed I believe on test3 see story #1236

**Comment by richpomfret** [comment]
Will be fixed elsewhere.
