### ISSUE TITLE
149938368 There is a recursive loop in FreeREG Help (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1246]
Issue reported by **MikeNL** at 2019-10-02 09:32:48 UTC
Time: 2019-10-02T09:30:20+00:00
Session ID: 68c11bc1bcb180127f79f28519ddbf74
Problem Page URL: [/cms/information-for-transcribers](/cms/information-for-transcribers)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers](https://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
On the "Help for Transcribers" screen there is a link to "Help for Transcribers" which is exactly the same as the screen that you are on.    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@SteveBiggs to ask for further info.

**Comment by SteveBiggs** [comment]
I asked for clarification and the reply was:

I have attached an image of the problem which, I hope, is self explanatory.
When you click on the link, you are returned to the same page making the link redundant once you are on the page.

![image](https://user-images.githubusercontent.com/25303607/66393838-7873d200-e9cb-11e9-8aa1-654ed2e598bb.png)

**Comment by SteveBiggs** [comment]
I then replied to Michael as follows:

The link is highlighted indicating that is the page you're on. If you click on one of the other links below it, that takes you to the page which also has the link to that page highlighted. That's the way it's been designed, e.g:

![image](https://user-images.githubusercontent.com/25303607/66393921-ace78e00-e9cb-11e9-9e34-00943957666c.png)

**Comment by AlOneill** [comment]
In addition, on hover, the tooltip has "This page".

The alternative is to leave the active page out of the navigation list altogether: the active page can't be listed without making it a link as the styling does not allow for non-links in the navigation list.

**Comment by richpomfret** [comment]
@Vino-S to take a quick look and see if switching off current link is easily 'doable'.

**Comment by SteveBiggs** [comment]
Suggest this can be closed as explanation was given and accepted.

**Comment by AlOneill** [comment]
Update on styling used for section menu items such as those in "Transcriber Help":
- all pages for the section are listed as this makes creating a new page much more straightforward — there is less likelihood of a page (together with a link to same) being left off the section listing in error
- the current page is marked "(this page)"
- the tooltips have been removed as they are not accessible to all users

Please note that this is a Refinery editing issue rather than one for a developer as there is nothing (currently) automatic about the listing of pages in a section menu.

As long as these guidelines are followed by those creating and editing pages in Refinery, I agree with @SteveBiggs that this issue can be closed.
