### ISSUE TITLE
153664102 Inconsistency in register types (PR, OT etc) (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1256]
Issue reported by **STSCoord** at 2019-11-14 12:28:22 UTC
Time: 2019-11-14T12:19:27+00:00
Session ID: f631a0a48a0c910c4bd84a85463d1759
Problem Page URL: [/freereg1_csv_entries/56a8b611f493fd5121000020?locale=en](/freereg1_csv_entries/56a8b611f493fd5121000020?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg1_csv_entries/56a8b611f493fd5121000020/edit?locale=en](https://www.freereg.org.uk/freereg1_csv_entries/56a8b611f493fd5121000020/edit?locale=en)
Reported Issue:
I have a file STSSTOMA99.CSV which, according to one part of FreeREG is of type "Other Transcript". See attached image.

However, an entry in the file shows the Register Type as "Unspecified".

I edited the record by putting a space into the Notes field. When the record re-displayed after the edit, the Register Type is "Other Transcript"

Recently, I went through a huge exercise to allocate all "Unspecified" Register Types to the correct register type. Obviously, there could be something wrong here. There is certainly a mismatch somewhere.
https://www.freereg.org.uk/uploads/feedback/screenshot/5dcd4866f493fdf17a4a9a1a/File_data.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The complaint is valid. 
Propagation of change information to all parts of the system is an extremely difficult and time consuming undertaking. For example there are 39,000+ entries for the register in question. Each one of those records would have to be updated with the change, in addition the 39,000+ search records that also contain the register type would have to be updated. ie the one simple change has to propagate to 100 batches and 78,000 entries and records. These have to be updated on each of the database servers. Often the process simply times out.
The 'cleanest' solution is stop using the information from the lowest level in the database but to use the information from the highest level in the database.
Put another way. A record belongs to an entry, an entry belongs to a batch, a batch belongs to a register, a register belongs to a church, a church belongs to a place and a place belongs to a county.
Currently each level contains the information about the each of the levels above it, ie a record has the register type, church name, place name and county stored within it.
This makes for very fast response when displaying the result of a search but a pain when a change has to be propagated.
If one has to look up the chain to get the information then we have to do 5 database accesses to get the information to display instead of 1.

**Comment by edickens** [comment]
Michael,
I've been trying to work this out.  The register type of this batch is OT, Other Transcript, which would be correct.
The usual problem is between OT and TR.  These mean the same.  As Kirk says, it is too big a job to standardise the register type code, so we should change it whenever we can.  OT is the preferred version.
Eric D

**Comment by Captainkirkdawson** [comment]
Sorry @edickens this is not OT/TR issue. What Michael has done is to change  unspecified register types to OT; but the vast majority of the records and entries still show unspecified. It is a legitimate concern

**Comment by Captainkirkdawson** [comment]
Unclear what management wishes me to do ie change display and remove propagation where it can be

**Comment by edickens** [comment]
I think I understand the problem a bit better.  We should be able to move batches that are Unspecified because a lot that came from FR1 are like that.  This will mean that all upload CSVs will have to have the register type added.  The obvious way is to download, edit, upload and delete the original, but this is very laborious.  Perhaps we can discuss at the next Scrum?

**Comment by richpomfret** [comment]
Agreed to proceed as recommended.

**Comment by SteveBiggs** [comment]
It's unclear to me what is recommended. The file Julie refers to in #1307 already has the register type 'PR' against every entry - what edit to the file does @edickens suggest? I am attempting a reprocess of the file to see if that sorts it out.

**Comment by SteveBiggs** [comment]
The reprocess fixed it.

**Comment by edickens** [comment]
The register type within the file has no significance once loaded.  If a batch is moved between register types the file is not changed.  The register type entered is used at first upload and was important when we first set up FR2.  But now the entries are checked against the Place, Church and Register type, and that is where the batch is held.
When we improve the data entry, and particularly go to online data entry, I want the upload screen to ask to select the Place, Church, Register Type, Source and Image Group.  This could be done now before online data entry, and the last two would be very useful.

**Comment by edickens** [comment]
Be careful with reprocess.  If the batch is locked it still sends it for processing and says it has done that but it does not process.  And if you are reprocessing a batch for an Inactive transcriber, it still send them a processed email.

**Comment by SteveBiggs** [comment]
It's still not clear what edit you suggest in your comment of Feb 17th. I always check the file isn't locked before I reprocess. If an inactive transcriber gets the email they can ignore or delete it.

**Comment by edickens** [comment]
Unspecified batches are ones created in FR1 before we added PR etc. after the Church name.  They came into FR2 and created Unspecified Register Types.  These batches are now being moved to the correct Register Type.  If these old batches are downloaded, then they will need the Register Type adding to be accepted.
The problem with sending upload emails to Inactive UserIDs, is that some have asked for no more contact from FreeREG and some left more than 10 years ago and are annoyed at still getting emails.  It is bad publicity.

**Comment by SteveBiggs** [comment]
Your first point doesn't apply to Julie's file but I understand what you refer to.

On your second point, the solution is to fix the system so that it doesn't send processing emails to inactive userIDs rather than stopping dealing with wrong register types.

**Comment by Captainkirkdawson** [comment]
With the server upgrade we have the performance required to do a chain look up of the register type , church and place instead of using the entry/file versions.
@SteveBiggs @edickens @Sherlock21 this need solid test to confirm that register type and church reflect what is entered in the Place/Church Register

**Comment by edickens** [comment]
Tried my usual Somerset Search.  Having selected Somerset, if I click the blank entry at the top of the list of places so as to choose all places, then search, i get Red error screen.

**Comment by edickens** [comment]
While testing I may have found another relative.

![Capture.JPG](https://images.zenhubusercontent.com/5cb4c5e2cccdd751e9e85870/3760d014-fcf9-4cb6-b86c-40afa2ff967a)

An illiterate with strong Somerset accent.  I altready have a DIGGINS.

**Comment by edickens** [comment]
Proper searching, and with options, works fine.

**Comment by Captainkirkdawson** [comment]
@edickens please retry that somerset search again.

**Comment by edickens** [comment]
Yes.  OK now.  Eric
