### ISSUE TITLE
160477144 No dates loaded on flexible batch upload (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1271]
Issue reported by **nejws05** at 2020-02-01 08:59:04 UTC
Time: 2020-02-01T08:52:55+00:00
Session ID: eaa3454c7b020918a3a6ac2d38c27b35
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?locale=en](https://www.freereg.org.uk/manage_counties/select_action?locale=en)
Reported Issue:
I uploaded NBLBAMBU3 on 30/1 and it appeared ( a day later) on  the website with no dates for either death or burial.
I have since removed and reloaded with the same result (also very slow to be processed)
Eric  Wealleans
Northumberland Coordinator    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is no such file as NBLBAMBU3 on the system for nejws05 and never has been

**Comment by Captainkirkdawson** [comment]
I did observe that there was a file NBLBAMBU2

So decided to look at it; well I see what the problem was 

+INFO,eric.wealleans@btinternet.com,password,SEQUENCED,BAPTISMS,,,,,,,,,,,
#,CCC,Eric.Wealleans,Northumberland,NBLBAMBU2.CSV,30-Jan-2020,,,,,,,,,,

The batch is defined to be a BAPTISM hence the fields have no relevance as they are burials

Change to BURIALS and it should process correctly
