### ISSUE TITLE
164110785 Details have not downloaded (Bernard)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1284]
Issue reported by **BernardW** at 2020-03-14 10:19:45 UTC
Time: 2020-03-14T10:15:37+00:00
Session ID: f8e34a4bbe9afb0f3118d89005e1a290
Problem Page URL: [/freereg_contents/5dfb8afdf493fd95bbe95179/unique_register_names?locale=en](/freereg_contents/5dfb8afdf493fd95bbe95179/unique_register_names?locale=en)
Previous Page URL: [https://www.freereg.org.uk/freereg_contents/5dfb8afdf493fd95bbe95179/show_register?locale=en](https://www.freereg.org.uk/freereg_contents/5dfb8afdf493fd95bbe95179/show_register?locale=en)
Reported Issue:
I am looking for surnames in this Parish of Bengeworth but the details have not downloaded.

BernardW    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The unique names is not updated instantaneously because of the "cost". It is updated weekly on a Monday. Have added a note to the Help
Unique Names
This display provides a list of all the unique names for events recorded in the place or church or register. This is extremely useful is seeing the various spellings that have been used and enables you to ensure that you have searched for all variations. The list is accessible through the Transcriptions pages or through the Detailed Search Result page by following the links to the place, church or register. **Please note this information is updated weekly on a Monday.**

**Comment by richpomfret** [comment]
Done - closing.
