### ISSUE TITLE
166495436 Inability to update a batch (Barrie)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1295]
Issue reported by **brobinson43** at 2020-04-11 00:43:56 UTC
Time: 2020-04-11T00:34:23+00:00
Session ID: f86e362a43b1f2a99a3e247a9541a7d0
Problem Page URL: [/csvfiles/56371325f493fd9f88000001/edit?locale=en](/csvfiles/56371325f493fd9f88000001/edit?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/56371325f493fd9f88000001/edit?locale=en](https://www.freereg.org.uk/csvfiles/56371325f493fd9f88000001/edit?locale=en)
Reported Issue:
I am trying to replace a file originally uploaded when I was transcribing for a different syndicate, and received the attached error message.

The header of the revised batch contains my userID in the form brobinson43 without reference to the syndicate (formerly Anna Rufer, now Barrie Robinson.

Other than this, the batch filename is exactly the same. Does the system now require a syndicate name after the userID or is there likely to be some other problem?
https://www.freereg.org.uk/uploads/feedback/screenshot/5e9112ccf493fd2b41d9fd68/Screen_Shot_2020-04-11_at_10.35.04_am.jpg    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
The file is WARLITBA3. I have tried to replace into Barrie's userID and get the same message.

**Comment by Captainkirkdawson** [comment]
This is certainly an interesting puzzle. 
Changing syndicates has **no** impact on the physical files of any userid. 
The files for barrie have no baptism files for WARLIT. Hence the system is reporting correctly when it says he does not have that file.
Looking at the attic it shows that he **did** have baptism file and did 3 replacements of them on 2 Nov 2015. The first was at about 7:10 GMT. The second was at about 7:39 and that is the one that has the on-line records. However there is a third file apparent uploaded about a minute later that does not get processed but does move the active file into the attic. The same thing happens to the BA1 and BA2 files at almost identical times.  The logs of those days have long since been deleted (it was nearly 5 years ago in the early days of REG2 so what was going on cannot be determined and one can only speculate.  My speculation is that there were 2 copies of the upload processor running on the same set of files leading to cross interference. We did put in extra interlocks on the processor in our first year to avoid that. However it is all speculation.
Proposed recovery is for either I or EricB to remove all traces of the 3 BA files for WARLIT and for Barrie to simply upload new versions when we have removed the traces. We can provide him with the last attic copy if that is needed.

**Comment by SteveBiggs** [comment]
I don't understand your statement that barrie has no baptism files for WARLIT. He has 3:
![image](https://user-images.githubusercontent.com/25303607/79052127-2a66b200-7c2c-11ea-99a7-6d5a5e8ba753.png)
and:
![image](https://user-images.githubusercontent.com/25303607/79052176-91846680-7c2c-11ea-9857-0a7eeb5423fb.png)

**Comment by Captainkirkdawson** [comment]
Perhaps I was not clear enough. Perhaps it would have been better to say 
There are **no physical baptism** files for barrie for WARLIT
![barrie_active](https://user-images.githubusercontent.com/2874694/79053362-012d2e00-7bfa-11ea-9b96-f5accbefe966.JPG)

**Comment by SteveBiggs** [comment]
Interesting. So what's the difference between the physical files you listed and the ones I see under "Physical Files"?:
![image](https://user-images.githubusercontent.com/25303607/79054763-969ee100-7c3f-11ea-9474-1adaed9be24e.png)

**Comment by SteveBiggs** [comment]
However, I tried to download WARLITBA3 and it reports:
![image](https://user-images.githubusercontent.com/25303607/79054817-fe552c00-7c3f-11ea-9abd-d0ce54018926.png)

So I guess it's not really there.

**Comment by Captainkirkdawson** [comment]
Yours was a database collection; mine was looking at what was actually there. Those 3 BA are not on the disk.
My proposed solution is the only way forward.

**Comment by SteveBiggs** [comment]
I agree.

**Comment by Captainkirkdawson** [comment]
Will you let Barrie know what we plan to do. I do not want him doing something at the same time

**Comment by edickens** [comment]
I have emailed Barrie to say to do nothing until told.

**Comment by Sherlock21** [comment]
Kirk 
for some reason I don’t understand, I cant log in to Github right now

SO given the story on this one, I think it better if you delete all the unwanted files, rather than me 
I have that feeling that I would have to resort to  asking you to do it anyway in the end!


regards
Eric B

**Comment by Captainkirkdawson** [comment]
The clean up has been performed.

Barrie should now be able to replace the file

**Comment by Sherlock21** [comment]
Thank ypu.
