### ISSUE TITLE
166800893 File Processing Stalling (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1296]
Issue reported by **SBManager** at 2020-04-14 13:34:53 UTC
Time: 2020-04-14T13:32:00+00:00
Session ID: 5b5634b4de5efa0c1e6dbadf671de224
Problem Page URL: [/physical_files?locale=en&page=](/physical_files?locale=en&page=)
Previous Page URL: [https://www.freereg.org.uk/physical_files/waiting_to_be_processed](https://www.freereg.org.uk/physical_files/waiting_to_be_processed)
Reported Issue:
File processing has stopped 3 times in the last couple of days. I've restarted it each time by clicking 'Process' on the oldest file.    

![Screenshot](https://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
Could be WARLITBA3.CSV ?

**Comment by Captainkirkdawson** [comment]
@SteveBiggs confirmed there were 50 note **50** attempts to process the file SSXFLEBU.CSV for jmcat in the past 24 hours. I downloaded it and it processed on my server. I note that it has since processed  in production. Could see nothing odd with the file except a trailing blank on the church name and no Register 

Have now noticed an oddity. 
The records are SSX,Fletching,**St Andrew and St Mary the Virgin**  ,71,16 Oct 1816,Thos
Yet the log says it was updating a PR 
Updating the current batch for SSX, Fletching, St Andrew and St Mary the Virgin, **Parish Register**. <br>

**Comment by SteveBiggs** [comment]
50?! Wow. Thanks for sorting it out. I did notice that it had an unspecified register.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs 
The successful run was updating the Unspecified register
Started on the file SSXFLEBU.CSV for jmcat at 2020-04-14 19:31:54 +0100. <p>
Updating the current batch for SSX, Fletching, St Andrew and St Mary the Virgin, Unspecified. <br>
675 records were processed of which 0 were updated/added and 0 had data errors. <p>
Created  675 entries at an average time of 53ms per record at 2020-04-14 19:32:30 +0100. <br>

**Comment by Captainkirkdawson** [comment]
WARLITBA3.CSV is definitely crashing the processor

**Comment by SteveBiggs** [comment]
Thanks @Captainkirkdawson , I'll look into it with Barrie.

**Comment by Captainkirkdawson** [comment]
Found the bug that was causing the processor crash. It was associated with a change in location information. In these cases it was a change in Register Type

**Comment by edickens** [comment]
Great news.  So it has been useful.

**Comment by Captainkirkdawson** [comment]
Deployed to production
