### ISSUE TITLE
168615780 Searches not finding entries when single year and month is lower case (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1310]
Issue reported by **REGManager** at 2020-05-05 13:43:00 UTC
Time: 2020-05-05T13:35:19+00:00
Session ID: 3a321eefe404f2bc23bfe511dbfde508
Problem Page URL: [/search_queries/5eb16b96f493fd29b1dd8d11?locale=en](/search_queries/5eb16b96f493fd29b1dd8d11?locale=en)
Previous Page URL: [https://www.freereg.org.uk/search_queries/new?locale=en](https://www.freereg.org.uk/search_queries/new?locale=en)
Reported Issue:
Search for MA John Taylor & Elizabeth Rushton, LIN, Great Hale, 30 Sep 1828 but enter 1828 to 1828.  No result.  The entry is there.
Investigation shows that search results with all lower case month are not found, but starting with upper case are found.
I'm not sure if this is the whole story, but that is what the researcher philosbourn@gmail.com has found.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
Fuller details from researcher:

John Taylor & Elizabeth Rushton, Great Hale, 30 Sep 1828

It did not turn up when I put in 1828 for start and end dates, but it did appear with start and end dates 1828 to 1829. A marriage from 1839: Mary Footitt & Thomas Cock was found correctly with only 1839 as the date.

I did some investigation and I think that the problem is to do with the way that the dates have been transcribed. All of the search failures I found had the month in lower case only while the successful searches had the month in title case (e.g. May, Sep, etc).

From Mick Claxton:

If I correct the record online from sep to Sep the record is then found without any problems. If researchers carry out a single year search it will ignore records that have been transcribed in this way. Can  the programming be changed to cater for this or will the actual records that have all lower case months  need to be manually corrected?

**Comment by Captainkirkdawson** [comment]
An example of the search dates problem will cause is story #2278

**Comment by Captainkirkdawson** [comment]
Will need to be corrected in the database; changing the programming to bypass a data error is not a good idea.

**Comment by Captainkirkdawson** [comment]
Propose to close in favour of  #2278
