### ISSUE TITLE
169987863 Destroy UserID fails with no reason (Eric D)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1323]
Issue reported by **REGManager** at 2020-05-21 10:51:03 UTC
Time: 2020-05-21T10:47:36+00:00
Session ID: 1ce8d0b201bf3ae7a085e590c35a2a56
Problem Page URL: [/userid_details/5462b406e937907d700000fa?locale=en&option=Select+specific+userid](/userid_details/5462b406e937907d700000fa?locale=en&option=Select+specific+userid)
Previous Page URL: [https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid](https://www.freereg.org.uk/userid_details/selection?option=Select%20specific%20userid)
Reported Issue:
Sandra and I have tried to destroy "DavetheMad" but get the attached error report which does not give a reason.  He has no batches.
I asked Coordinators to tidy up their list of UserID so if a lot do this I may get a lot of complaints.  This is urgent.
https://www.freereg.org.uk/uploads/feedback/screenshot/5ec65d17f493fd2704a442d0/Capture.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Not critical to operations; will await priorization

**Comment by edickens** [comment]
Except that I have just asked in my Newsletter that SCs tidy up their UserIDs and do this.

**Comment by Captainkirkdawson** [comment]
Deletion fails because the user has attic files. Cannot delete a userid that has files OR attic files as it would leave us with orphan files.

![dave.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/254fcb6c-d96e-4690-bc86-ab89cdd60397)

**Comment by edickens** [comment]
Further investigation.
Destroying DavetheMad does not work because there are a lot of GLA files in the Attic.  But the UserID says that he has not uploaded any files, the field at the bottom of his Profile listing.
The UserID STSCoord, no longer needed, cannot be destroyed because there are files in the Attic, but the UserID Profile says that no files were uploaded?
So both failed for valid reasons.  I have not had any more reports of Destroy failing and I asked SCs to tidy up their list of UserIDs.
