### ISSUE TITLE
176628951 Files awaiting processing (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1363]
Issue reported by **nejws05** at 2020-08-06 07:35:51 UTC
Time: 2020-08-06T07:34:21+00:00
Session ID: 2d998207b8433b24e31291cc014b243f
Problem Page URL: [/manage_syndicates/display_files_waiting_to_be_processed](/manage_syndicates/display_files_waiting_to_be_processed)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action?locale=en](https://www.freereg.org.uk/manage_syndicates/select_action?locale=en)
Reported Issue:
NBL batch waiting to be processed since yesterday
Eric  Wealleans
NBL Coordinator    

![Screenshot](https://www.freereg.org.uk)

**Comment by richpomfret** [comment]
@Captainkirkdawson @Vino-S can we investigate what might be causing this/why it occurs with certain files? With a view to pre-empting it. Steve suggests a timeout of a sort if files are 'hanging' or 'blocking' the system.

**Comment by richpomfret** [comment]
A notification is needed for any such files.

**Comment by Captainkirkdawson** [comment]
Problem is caused by any file that crashes the processor; we recover the processor after the crash and proceed with processing. Unfortunately it selects the file that has been waiting the longest which is the file that crashed the processor and it does it again and again.
There is no way of predicting which files cause a crash. The processor often runs for months without a crash. Normally the condition is found and a fix applied. Sometimes the only fix is for the file to be correctly formatted.

**Comment by edickens** [comment]
Kirk.  Can we find in a log or somewhere, what causes the crash?  We can then try to avoid it.  Steve will save the file next time it happens and we will try to see if we can find what is wrong..

**Comment by Captainkirkdawson** [comment]
The crash is in the production log and the reason in the processing log file for that file
