### ISSUE TITLE
177676691 Search retrieves deleted records. (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1367]
Issue reported by **alsibk** at 2020-08-18 10:38:11 UTC
Time: 2020-08-18T10:34:27+00:00
Session ID: bf6632282101af6ef087609a711d40d2
Problem Page URL: [/manage_counties/select_action?locale=en](/manage_counties/select_action?locale=en)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/new?locale=en](https://www.freereg.org.uk/manage_counties/new?locale=en)
Reported Issue:
Files deleted WRYARMBU.csv

Register MI Armthorpe deleted, reinstated.

File WRYARMBU.csv uploaded.

Open search on Bird/WRY/Armthorpe Burials retrieves 4 results, 2 of which lead nowhere.

See attachment.

https://www.freereg.org.uk/uploads/feedback/screenshot/5f3baf93f493fd4d07c3636f/No_record.JPG    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
The files were deleted some weeks ago.

**Comment by SteveBiggs** [comment]
Ali, I've just looked in the file and see that Lily BIRD does not have 'MI' as the register type - it is blank.

Doesn't explain the duplication though.

**Comment by SteveBiggs** [comment]
That also raises the question of why did this entry with no register type not create a new batch under an unspecified register?

**Comment by SteveBiggs** [comment]
It may be worth reprocessing the file to see if it sorts the problem out?

**Comment by suffolkroots** [comment]
This issue dates back to 9 July, when two WRYARMBU.csv files were uploaded by transcriber, one in Register MI, other in Register Unspecified.
![9 July](https://user-images.githubusercontent.com/10379655/90511193-03793900-e154-11ea-939b-d0d6b47afe04.JPG)

I tried to delete the Unspecified, and Replace the MI without errors.
This resulted in the Replacement of both files, no longer with errors.
![17 July](https://user-images.githubusercontent.com/10379655/90511225-0ffd9180-e154-11ea-8645-5b21af70fba1.JPG)

At this point I asked EricB if he would please delete the Unspecified file for me, as I wished to go no further with a strange set of circumstances.

Since then searches retrieve names from original deleted files, but no detail.

**Comment by Sherlock21** [comment]
When I followed it up with Kirk at the time, I was advised the leftover bits of data would clear by some nightly cleanup routine - or so I seem to remember

**Comment by edickens** [comment]
I remember that too.  You need to wait until tomorrow to see if your changes have worked.

**Comment by SteveBiggs** [comment]
@edickens the changes were made on 9th July.

**Comment by edickens** [comment]
I meant to wait until the next day after deleting file.

**Comment by Captainkirkdawson** [comment]
Things get very confused if one does not wait overnight after removing and
then doing something else to the register
Kirk Dawson
Fairmont, B.C. Canada

**Comment by suffolkroots** [comment]
Deleted entries are retrieved on a search, weeks later. Is this how FreeREG works?

**Comment by suffolkroots** [comment]
> 
> 
> That also raises the question of why did this entry with no register type not create a new batch under an unspecified register?

This entry did have a register type---entered as Memorial Inscription rather than MI

Which created the file Unspecified. Subsequently deleted

**Comment by SteveBiggs** [comment]
I think what Kirk is saying is that if a file is deleted from a register, then nothing more should be done to that register until the overnight process has run to clean things up.

I've had a look to see what the Help says about this and it is covered under 'Files with more than one batch' because the entry which used Memorial Inscription rather than MI was effectively another batch within the file with a register type of Unspecified. The process to deal with this is detailed in the Help as follows:
![image.png](https://images.zenhubusercontent.com/5cb596063b6bd6333fc1dc24/d94bec23-8e44-4d03-ad9d-e70d9c0d2e70)

So rather than delete the file, it's recommended to correct the register type and merge the batches.

**Comment by suffolkroots** [comment]
Thanks Steve for clarification.
But:
Deleted entries are retrieved on a search, weeks later. Is this how FreeREG works?

**Comment by SteveBiggs** [comment]
It shouldn't work like that but I assume the system has got confused and there are residual errors that need manual intervention. Only Kirk can clarify exactly what has happened.

**Comment by richpomfret** [comment]
@Captainkirkdawson If we cannot prevent this from happening in the first place - is there a post-processing task to detect/clean-up such records?

**Comment by richpomfret** [comment]
Perhaps a lock following deletion for x amount of time?

**Comment by PatReynolds** [comment]
Have an email sent to say that delete has been successful.

Have a message on delete to say: please wait for the email before you do anything else to this register.

Ideally, have a block on further register changes before delete has cleared.

**Comment by Sherlock21** [comment]
Since this whole p problem stems from my being asked to delete a batch for someone - usually because its too big for them to do, but not always so, HOW am I supposed to know that its a simple 1 batch in the 1 file, or its a multi batches in1 file?

important because the single batch in a file runs OK and can be replaced the same day; whilst the multi batch job ( which I cant find out before hand) has to await the overnight processing before being replaced.

OR is the only solution NOT to reuse file names  for the file's replacement? would that work to stop these clashes?
Else what would please?

**Comment by suffolkroots** [comment]
This is the first time I have ever had to deal with a multi batch file and I handled it wrongly. Sorry all and Sherlock21 in particular.

Query re residual deletes still remains.

**Comment by SteveBiggs** [comment]
@suffolkroots just checking did you add a register type of MI to the Lily BIRD entry in the file?

**Comment by suffolkroots** [comment]
No, I changed Memorial Inscription reg type to MI reg type.

**Comment by SteveBiggs** [comment]
That's odd. If you download the file, there is nothing in there for the register type (just a space):

![image](https://user-images.githubusercontent.com/25303607/90759128-eb322700-e2d7-11ea-9188-504bd5590698.png)

**Comment by suffolkroots** [comment]
Well I'm baffled, the file I uploaded has everything OK.
This looks like the original file which created 2 batches.

**Comment by Sherlock21** [comment]
Ali
- no need for you to apologise - I had forgotten - if I ever knew!
And I thought that more recent rewrites/ bug fixes ad eliminated the need for overnight processing of any parts of this task.

**Comment by PatReynolds** [comment]
@suffolkroots could you please add back MI as this will solve the problem.  We haven't been able to determine what has happened, I'm afraid, but will keep this in mind if it occurs again.

**Comment by suffolkroots** [comment]
OK will add back MI.

BTW, no email received re message from Pat 3 days ago.

**Comment by richpomfret** [comment]
Closing - if it emerges again we will create a separate story.
