### ISSUE TITLE
183508291 County content report needs double quotes around church names (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#1384]
Issue reported by **LINCC** at 2020-10-24 22:31:31 UTC
Time: 2020-10-24T21:52:06+00:00
Session ID: 06a0608ba50bfa37034b7fe5bbc946db
Problem Page URL: [/manage_counties/selection?option=Offline%20Reports](/manage_counties/selection?option=Offline%20Reports)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/selection?option=Offline%20Reports](https://www.freereg.org.uk/manage_counties/selection?option=Offline%20Reports)
Reported Issue:
When the offline County Content report has been produced the obvious thing to do is to look at it within a spreadsheet.

Unfortunately, the file is a literal .csv file meaning that fields are separated by commas.

Within LIN there is a church called "St Mary, St Bartholomew and St Guthlac" in Crowland. This causes an extra column to be created for those files for this church, totally corrupting the column layout of the file.

There is also a place called "Kirkby, East". Luckily, there are no files connected with this place as this also corrupts the column layout.

Could the report be changed so that ALL text strings are enclosed within double quotes (")? NB not single quotes (')    

![Screenshot](https://www.freereg.org.uk)

**Comment by Sherlock21** [comment]
I suggest that the CC either removes the comma from the church name
or replaces it be the word ‘and’ 

then there will be no issues that cause the extra , and thus the layout will not arise.

as to Kirkby, East as a place name, It should not be there! I have deleted it.
East Kirkby is already in FR, with some records

Regards
EricB

On 25 Oct 2020, at 11:08, FreeUKGenIssues <notifications@github.com> wrote:


Issue reported by LINCC at 2020-10-24 22:31:31 UTC
Time: 2020-10-24T21:52:06+00:00
Session ID: 06a0608ba50bfa37034b7fe5bbc946db
Problem Page URL: /manage_counties/selection?option=Offline%20Reports <x-msg://4/manage_counties/selection?option=Offline%20Reports>
Previous Page URL: https://www.freereg.org.uk/manage_counties/selection?option=Offline%20Reports <https://www.freereg.org.uk/manage_counties/selection?option=Offline%20Reports>
Reported Issue:
When the offline County Content report has been produced the obvious thing to do is to look at it within a spreadsheet.

Unfortunately, the file is a literal .csv file meaning that fields are separated by commas.

Within LIN there is a church called "St Mary, St Bartholomew and St Guthlac" in Crowland. This causes an extra column to be created for those files for this church, totally corrupting the column layout of the file.

There is also a place called "Kirkby, East". Luckily, there are no files connected with this place as this also corrupts the column layout.

Could the report be changed so that ALL text strings are enclosed within double quotes (")? NB not single quotes (')

 <https://camo.githubusercontent.com/e9d19cb6aa736c609f5ff3343c15ce9c620bff9f/68747470733a2f2f7777772e667265657265672e6f72672e756b>

**Comment by PatReynolds** [comment]
Places with commas should be changed to the non-comma version (e.g. East Kirkby). 
Coordinators need to make sure, when they give a batch to transcribe that they give the correct version of place name. @SteveBiggs to let coordinators know.

**Comment by SteveBiggs** [comment]
@Sherlock21 can you confirm that you have deleted all places of the form Kirkby, East in the FreeREG system? I believe that you have but just want to check. Thanks
