### ISSUE TITLE
205785455 Problem uploading (Joanne)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1437]
Issue reported by **ManCity** at 2021-07-09 18:37:35 UTC
Time: 2021-07-09T18:35:59+00:00
Session ID: 619cebfddd85ec99206f4548b228fe68
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
Getting quite a few transcribers over the last week saying they can't replace.  Keep getting the message you are trying to upload a document that you do not have.  I've sometimes been able to upload for them, other times had to delete the document and do a fresh upload which always go through ok.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
It looks like there may still be a problem with Replacing files on FreeREG.

**Comment by Captainkirkdawson** [comment]
@SteveBiggs the issue is the following. When that software was running an initial upload had the CSV extension down cased to csv. When they attempt to replace it with the file with the original CSV extension they will get that message. Solution is for them to either 1) delete the original file and do a fresh upload or 2) to change the CSV extension on their file to csv

**Comment by SteveBiggs** [comment]
Thanks for that Kirk. I didn't think to look at the case of the extension. I will check that on any other reported replace issues.

**Comment by SteveBiggs** [comment]
I've asked Jo to check the extension case in future. This can be closed.
