### ISSUE TITLE
207062715 Never open a CSV file in a Spreadsheet program (Stephen)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1439]
Issue reported by **steveroland** at 2021-07-24 13:25:15 UTC
Time: 2021-07-24T13:05:29+00:00
Session ID: 98068c51d7dbe2520aadb31eb0faa1d3
Problem Page URL: [/cms/information-for-transcribers/creating-a-transcription-file](/cms/information-for-transcribers/creating-a-transcription-file)
Previous Page URL: [https://www.freereg.org.uk/cms/information-for-transcribers](https://www.freereg.org.uk/cms/information-for-transcribers)
Reported Issue:
We should add to the Help on the use of Spreadsheets that opening a .CSV format file in a spreadsheet will likely cause problems with certain data formats in the header and potentially dates. While working on a transcription ALWAYS keep the file in the native spreadsheet type, e.g. .XLS, .ODF, etc. Only save as CSV when ready to upload the file.    

![Screenshot](https://www.freereg.org.uk)

E0 U6 S8 C6:P20

**Comment by AlOneill** [comment]
The current guidance, on 'Creating a transcription file' reads:

"We recommend that you save your working file in the spreadsheet's own format (file ending). This will make it simpler to re-open the file and will preserve such things as column widths and font size for when you next work on your transcription."

I understand the concern about dates getting mangled — this the current advice, on 'Entering data from registers':

"If using a spreadsheet, be sure to set the cell format for any date fields (columns) to text rather than date: computers are not good with dates before 1900, and certainly do not understand the split-year convention."

However,  I do not know what "certain data formats in the header" means or what sort of problems are likely to arise.

**Comment by suffolkroots** [comment]
Header line 1 cell A +INFO  and line 5 cell A +LDS can be affected.

Dates from 1900 onwards are a problem, not before 1900.

**Comment by SteveBiggs** [comment]
Following on from @suffolkroots' comment, I would add to recommend that the entire sheet be formatted as Text before starting entering any data - including header to it.

**Comment by AlOneill** [comment]
Two pages updated:
https://test3.freereg.org.uk/cms/information-for-transcribers/entering-data-from-registers
https://test3.freereg.org.uk/cms/information-for-transcribers/creating-a-transcription-file

**Comment by SteveBiggs** [comment]
I think they will be sufficient to help transcribers.
