### ISSUE TITLE
218902924 Illegal quoting (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1456]
Issue reported by **alsibk** at 2021-12-08 14:22:04 UTC
Time: 2021-12-08T14:17:55+00:00
Session ID: a98bec8cde3277f477388d75f2a644b3
Problem Page URL: [/freereg1_csv_files?locale=en](/freereg1_csv_files?locale=en)
Previous Page URL: [https://www.freereg.org.uk/csvfiles/new](https://www.freereg.org.uk/csvfiles/new)
Reported Issue:
*We were unable to process the file possibly due to an invalid structure or character. Please consult the System Administrator*. 

Please could we have a line number for this, as in FreeCEN.    

![Screenshot](https://www.freereg.org.uk)

E0 U6 S9 C6: Priority 21

**Comment by Captainkirkdawson** [comment]
Added code to identify line. Running on test3.
Started on the file WRYTESTBA3.csv for Captainkirk at 2021-12-09 15:57:10 +0000. <p>
csv slurp rescue Unclosed quoted field in line 11.
Captainkirk	WRYTESTBA3.csv *We were unable to process the file possibly due to an invalid structure or character. Please consult the System Administrator*. <br>
Processing was terminated because of a fatal header error. <p>
There are no valid header lines. <br>

@SteveBiggs can you please review and test processor to make sure it still functions properly

**Comment by SteveBiggs** [comment]
Have made several tests and all looks good, thanks Kirk.
