### ISSUE TITLE
254232946 Coordinators making corrections to batches (Eric D)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1492]
Issue reported by **REGManager** at 2023-01-21 12:15:46 UTC
Time: 2023-01-21T12:09:45+00:00
Session ID: 2f4a2f95ab64fe86455ae9172620f3b6
Problem Page URL: [/manage_resources/new?locale=en](/manage_resources/new?locale=en)
Previous Page URL: [https://www.freereg.org.uk/feedbacks](https://www.freereg.org.uk/feedbacks)
Reported Issue:
When a CC finds errors in a batch they should in the first instance contact the transcriber and ask them to make the corrections.   If the transcriber does not reply within 7 days, then the CC should make the changes and they should email the transcriber to say what they have done because the batch will be locked against the transcriber.  If the UserID is Inactive the CC can make the changes immediately.
The CC Help needs updating.    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
I agree because some Transcribers take months (or even years) to complete a transcription file and make uploads/replacements throughout the transcription period. It's quite possible that a researcher might report an error in that file's records during this period. 

If the SC makes the correction without checking if the file has been completed or is still in work, this will lock the file and if the transcriber subsequently tries to replace it with further records, they will be surprised to find it fails because the file is locked. They could download the file to unlock it but if they then replace it with their file of additional records, it won't have the correction because they are unaware of it.

**Comment by edickens** [comment]
Steve,
There is a loop hole here.  Michael told me that he did the download, edit and replace when acting as the transcriber through the Manage UserID option.  So the file was uploaded under the transcriber's UserID and the file was not locked.  SC locking only seems to occur if the entries are edited online.  E

**Comment by SteveBiggs** [comment]
That's not a loophole but is the way the system is designed to work. Replacing a file does not (and should not) lock the file. It's when you do an online edit that it's locked to stop a further replacement of the file overwriting the edit.

Michael used his Coord status to replace the file into the transcriber's userID which is perfectly fine. The transcriber should have received a processing email telling them that the file had been replaced however, they wouldn't have known exactly what changes Michael made - this is where direct communication with the transcriber is needed to explain.

**Comment by DeniseColbert** [comment]
@AlOneill could you please add this to Coord Help?

**Comment by AlOneill** [comment]
@Captainkirkdawson 
It seems that this issue was asking for details and clarification not currently in the coord 'Help', so I will re-open and review — unless your understanding is different?

**Comment by AlOneill** [comment]
Information expanded as rubric in issue description
See [DRAFT Info for Coords](https://test3.freereg.org.uk/cms/draft-information-for-coordinators-87f0a886-23a7-49d8-bd15-d35c88fd1520) which also addresses #1549

**Comment by SteveBiggs** [comment]
@AlOneill please hold off on deployment as more detail will need to be added on responding to Contacts including the 45-day time limit and use of the 'Keep until I say so' button to avoid cases of amendments being made to files still being worked on. I will provide words of guidance for this in due course.

**Comment by AlOneill** [comment]
@SteveBiggs 
Noted.

**Comment by SteveBiggs** [comment]
@AlOneill attached is the updated section. Thanks.
[Contacts help.docx](https://github.com/FreeUKGen/FreeUKRegProductIssues/files/10831044/Contacts.help.docx)

**Comment by AlOneill** [comment]
@SteveBiggs 
In progress: updating "Responding to contacts" on [DRAFT Coord Actions](https://test3.freereg.org.uk/cms/information-for-coordinators/draft-coordinator-actions#contacts).

We cannot use the same heading twice (Responding to Contacts, h3 and h4) so am considering changing them so that the h3 is "Responding to Contacts (Data problems)" and the h4 is "Responding to the Contact message". If you have a better suggestion, then do say!

**Comment by SteveBiggs** [comment]
Sounds fine to me.

Stephen Biggs
FreeREG Chair

**Comment by AlOneill** [comment]
[DRAFT Coord Actions](https://test3.freereg.org.uk/cms/information-for-coordinators/draft-coordinator-actions) updated with the text of document from @SteveBiggs 
Resolved the issue of repeated headings, re-cased Commscoord as CommsCoord to improve readability and tweaked the text in a couple of places to sound more natural.

Ready for review.

**Comment by SteveBiggs** [comment]
Thanks @AlOneill . Just a couple of points - 'action' should not be in brown text but 'Keep until I say so' should:

![image](https://user-images.githubusercontent.com/25303607/221579570-b05af855-d914-4e3d-b491-5c7401bed2bd.png)

**Comment by AlOneill** [comment]
Oops! Both instances now corrected. Thanks @SteveBiggs 

I noticed just now that the @ menu has CommsCoord — so nothing more to change for anyone!

May I now publish "DRAFT Info for coords" and "DRAFT Coord actions" on t3?

**Comment by SteveBiggs** [comment]
Yes, looks good, thanks.

**Comment by AlOneill** [comment]
Thank you @SteveBiggs 

Draft versions of "Info for Coords" and "Coord Actions" promoted and published on t3.
Ready to be deployed for user testing.

**Comment by DeniseColbert** [comment]
Now on live so closing
