### ISSUE TITLE
265545481 Main help page - description of "Nearby Places" (Andrew)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1502]
Issue reported by **AndrewW** at 2023-06-01 10:38:01 UTC
Time: 2023-06-01T10:30:35+00:00
Session ID: 6910737aef2d79b1556930d7307323b3
Problem Page URL: [/cms/help](/cms/help)
Previous Page URL: []()
Reported Issue:
Hi all,

The current description of "Nearby Places" on the search help page (https://www.freereg.org.uk/cms/help) states:

"A new feature, Nearby places, when selected, enables you you search the places nearby your selected place. This is a powerful option which will include the nearest 40 places to the one selected. This is especially useful for searching around a Place that is near to a County boundary, or for dividing a large county into smaller parts. If this option generates too many records, you can repeatedly halve the radius of the search by using the Narrow Search button."

In testing this, the actual criteria seems to start at the nearest 100 places (rather than 40), and the "Narrow Search" button halves the number of places rather than halving the radius of the search.

It's a really useful function to have but I wonder whether the help information would benefit from being updated to reflect what is currently happening?

Many thanks
Andrew Whitehead (AndrewW, yksgenealogy@gmail.com, volunteer transcriber)    

![Screenshot](https://www.freereg.org.uk)

**Comment by SteveBiggs** [comment]
A documentation update appears to be needed.

**Comment by AlOneill** [comment]
Oh my! When did this change? Were we told and I missed it? I do not have the energy for regular monitoring of how FreeREG works, so thank you Andrew for the heads up.

**Comment by SteveBiggs** [comment]
I don't recall it changing either.

**Comment by Sherlock21** [comment]
Steve

I cant log on to Github at the moment, so here is me input to this item of “nearby”

Being the person who invented it, in conjunction with Kirk, I must add that I have never been asked about how it works nor whether it should be changed in any way.

it has been set for many years as described by Andrew W ie
In testing this, the actual criteria seems to start at the nearest 100 places (rather than 40), and the "Narrow Search" button halves the number of places rather than halving the radius of the search.

it occurs to me that the write up may have been re composed by someone who was not in the design at the start?
and I have not been asked to participate in any action re changing the logic or the visual result.
Indeed,  I would be very much against a change in its workings.

Regards
Eric B
On 4 Jun 2023, at 11:15, Stephen Biggs ***@***.***> wrote:


I don't recall it changing either.

**Comment by AlOneill** [comment]
Curiouser and curiouser …
The current description is exactly as given to me, by Kirk, when I first started working on the website. I have not changed it since and am not aware of anyone else doing so.

I will explore the current situation a little and then update the description of Nearby Places.

**Comment by AlOneill** [comment]
I note that the tooltip for Nearby Places, which can be changed only by a developer, has "up to 40 places".

**Comment by AlOneill** [comment]
@SteveBiggs 
[DRAFT Help](https://test3.freereg.org.uk/cms/draft-help#top) has been updated to reflect the situation as reported by AndrewW. I also added a heading to help screen reader users find the information.

I have removed the duplicate `id="top"` which was a hangover from way back and is no longer required since every REG page now has — or should have — `id="top"`set on an element at the top of the page. (I could not find it on a Search Results page, but the link behaved as expected — another very curious thing!)

**NB** A developer will need to update the tooltip text to say 100 instead of the current 40.

**Comment by SteveBiggs** [comment]
Thanks @AlOneill, looks good.

**Comment by AlOneill** [comment]
@SteveBiggs 
Thank you. I'll make the page sync-ready and open a new issue for updating the tooltip.

**Comment by AlOneill** [comment]
Update published — sync-ready.

**Comment by AlOneill** [comment]
Tooltip issue now now moved to #2667

**Comment by DeniseColbert** [comment]
Done, closing, Thanks!
