### ISSUE TITLE
270917957 Unprocessed files blocking further action. (Ali)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeUKRegProductIssues#1511]
Issue reported by **alsibk** at 2023-08-02 14:59:17 UTC
Time: 2023-08-02T14:51:54+00:00
Session ID: 9c86836d2340e21d429ad3db5e1bd6b8
Problem Page URL: [/manage_syndicates/display_files_waiting_to_be_processed](/manage_syndicates/display_files_waiting_to_be_processed)
Previous Page URL: [https://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Yorkshire,%20West%20Riding%20-%20Ali%20Hill?locale=en](https://www.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Yorkshire,%20West%20Riding%20-%20Ali%20Hill?locale=en)
Reported Issue:
The instruction to Replace a file which is unprocessed has been active for what seems to be a very long time. 
We have to request that the unprocessed file is removed before we can proceed with Upload..
This is unsatisfactory and an annoying nuisance.
Please can it be corrected?
Thankyou.    

![Screenshot](https://www.freereg.org.uk)

**Comment by edickens** [comment]
If the reason why the processing stalls is because of a file being replaced before the previous version has been processed, then can we introduce a check that when a file is "Replaced" the waiting processing list is checked and if there is a file of the same UserID & Filename in the queue, then the old one is deleted.
I can see why a transcriber would replace a file before the previous one was processed, and that is if, after uploading, they notice an error, then they would correct that and replace the file.
This check could stop the stalling problem.

**Comment by suffolkroots** [comment]
@edickens this problem occurs after the file unprocessed message has been received.
As you are no doubt aware, flexi files cannot be checked without uploading, and I am sure that Steve is as frustrated as I am by my continuous requests to delete a file. If CCs could remove the stuck file without referring to a higher authourity it would help.

**Comment by DeniseColbert** [comment]
Delete unprocessed files, and delete the existing list of unprocessed files

**Comment by DeniseColbert** [comment]
This has been done so no blocks should occur

**Comment by suffolkroots** [comment]
Denise this is still not satisfactory as we still need to refer to a higher authority to have the unprocessed file deleted.

Please can CCs have this action in their toolkit.

Please will someone delete OTHSHIBU4.csv, asp.

Thank you.
