### ISSUE TITLE
Register type is missing from Search results. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#175]
Issue reported by **ericb** at 2015-02-18 14:23:33 UTC
Time: 2015-02-18T14:20:33+00:00
Session ID: 5418701f501c1375392da0d9f1e141cc
Problem Page URL: [/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-02-18+14%3A20%3A25+UTC&session_id=5418701f501c1375392da0d9f1e141cc&user_id=ericb&problem_page_url=%2Fsearch_queries%2F54e49fa9e93790c36b000003&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2Fnew&feedback_type=issue](/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-02-18+14%3A20%3A25+UTC&session_id=5418701f501c1375392da0d9f1e141cc&user_id=ericb&problem_page_url=%2Fsearch_queries%2F54e49fa9e93790c36b000003&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2Fnew&feedback_type=issue)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/54e49fa9e93790c36b000003](http://freereg2.freereg.org.uk/search_queries/54e49fa9e93790c36b000003)
Reported Issue:
It is missing from ALL types, and form single types too if you had made a distinction.

Its common to many Counties / Places not just the one used here.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by benwbrum** [comment]
The problem seems to be that "TR" was not getting transformed into "Transcript".  I cannot duplicate this on my development environment, so I suspect that it's been fixed.  

Similar entries with TR in the test2 site (which was rebuilt less than a month ago) successfully transformed "TR" into "Transcript" rather than blanking it.

We need to test after a rebuild.
