### ISSUE TITLE
Case in UserID (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#199]
Issue reported by **REGManager** at 2015-04-13 07:00:44 UTC
Time: 2015-04-13T06:55:59+00:00
Session ID: 9714eb59579606fe7bbdde745c98e3ca
Problem Page URL: [/userid_details/new](/userid_details/new)
Previous Page URL: [http://freereg2.freereg.org.uk/userid_details/options](http://freereg2.freereg.org.uk/userid_details/options)
Reported Issue:
I'm not sure if it is a problem, but when checking the daily update log, there are a number of UserIDs in FR1 not in FR2, but I have entered them.  The problem seems to be that FR2 is converting all the UserIDs to lowercase when I set up a new UserID.  I always copy and paste the UserID (and all the other details) so the case should match FR1.
FR2 should not change the case of any UserID or other field when setting up or amending UserID details.
I will make some corrections and do some more checks.
EricD    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by edickens** [comment]
Yes, this does seem to be the problem.  But I cannot amend the UserID.  These transcribers have files so I cannot delete and setup again.
E

**Comment by Captainkirkdawson** [comment]
You will recall that this was an issue that was resolved about a month ago when rather than work on all lower case userids we had FR2 respect the case entered by the creator of the userid.
FR2 does not change the case since that change.
Unfortunately there were a number of userids created during the previous regime that have lower case in FR2 and are case sensitive in FR1. 
These will have to be adjusted manually at the system file level if they have files.
Please provide me a list of those that need case adjustment at the system level (offline please) and we will see what we can do.

**Comment by Captainkirkdawson** [comment]
Change of plan; because of the implication we will have to add a name change capability for REGManager that changes all of the parts.

**Comment by edickens** [comment]
```
But it shouldn't happen again.

E
_____________________________________
```

Eric J Dickens
FreeREG Chairman

**Comment by Captainkirkdawson** [comment]
Those who were registered with the incorrect case have now been corrected.

**Comment by edickens** [comment]
I'll have another check after tonight's update.
E
