### ISSUE TITLE
Unable to find a record that has not been transcribed (gilson), Still relevant?

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#225]
Issue reported by **gilson** at 2015-05-09 09:44:19 UTC
Time: 2015-05-09T09:21:51+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www13.freereg.org.uk/contacts/new](http://www13.freereg.org.uk/contacts/new)
Reported Issue:
Enter text here...I have a actual print of Helions  Bumpstead  Births..  it has Sarah Andrews   (Anderson)    birth in 1782  father is George and Mary Andrews (Anderson)  its more like Anderson ... your site will not bring up  any such person in any of the names. could you please give me the Answere for this date on Sarah Andrews...      I know someone may translate wrongly but I cannot find the  answere and it really is annoying. but I still find your site terrific.. regards P Gilson    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
I looked up where this place is, in case its a county or Place name problem - but that's not the issue!
Its in Essex.
And to save anyone hunting  further, as I had found the answer at the same time: We have not done any transcriptions for that place yet! So no wonder the reporter gets no result!

I emailed Julie & Bob with this info - they will reply far more politely than I could.

regards,

**Comment by edickens** [comment]
We get quite a few comments where researchers have not checked the Database
Contents.  This is the first question I ask when someone says an entry is
missing.  I don't know what else we can do to make them do this.
The problem arises when they search a county and do not select/check the
place names.  So should we put a comment at the top of the Results screen
to say "Not found what you are looking for?  Then check if we have
transcribed that place/year yet by looking at the Database Content
(link)".  And if we could go to the County that they selected, better still.

E

**Comment by Sherlock21** [comment]
I agree with your idea, Eric.
If the form was designed to require a County and a Place name, then that would a) enable it to be routed to the right CC, and b) would then fit in with your suggestion of: "Have you checked that we have data for the place, for the time period that you are searching?"
Need to Have facility for sending in Non place name based reports too of course!
If these boxes are not completed properly, then reject the Report.

**Comment by Captainkirkdawson** [comment]
Changed the name of the issue and added it as a feature request for the comment. BUT REMEMBER WE DO HAVE THAT ALREADY FOR A NO RESULTS RETURNED SEARCH
The Report a Data Record problem has the county place and church information in it so there is no need for additional fields.
The original general comment form asked for additional fields to be entered and these were removed in order to keep the form simple and encourage its use. People do not fill in comment forms with too many fields.

**Comment by Captainkirkdawson** [comment]
On a no results
 <p>No results found. This could either be because there are no transcriptions for the Places you were searching, review our  <%=link_to("Database Contents",main_app.freereg_contents_path)%> for what has been transcribed. Alternatively you may need to recast your search options, see our <%= link_to "Tips for Searching", "/tips-for-searching-the-database" %> for advise on how to get the most out of your searches</p>

**Comment by Captainkirkdawson** [comment]
Is this still relevant?

**Comment by edickens** [comment]
```
Hi Kirk.  Who are you addressing this to?  The originator "gilson"
is not known to me and is not a FR UserID.  E

On 22/10/2015 03:45, Kirk Dawson wrote:


  Is this still relevant?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
To us in the scrum
