### ISSUE TITLE
Searching problem: when Nearby is ticked, Origin place is excluded from results (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#253]
Issue reported by **ericb** at 2015-06-13 14:36:22 UTC
Time: 2015-06-13T14:30:30+00:00
Session ID: 73b02e21b8af242aba676f9f060f2a9c
Problem Page URL: [/search_queries/557c3e85f493fdccc3000b3d](/search_queries/557c3e85f493fdccc3000b3d)
Previous Page URL: [http://freereg2.freereg.org.uk/search_queries/new](http://freereg2.freereg.org.uk/search_queries/new)
Reported Issue:
do a search on NFK/ Great Porington/ Surname = Utting./ tick Nearby leave rest blank .

There are records that should appear, [ ie if you don't tick Nearby you get to see them]
The result of the Nearby exceeds 250 so one gets the warning and the cut down list of nearest to search place specified. EXCEPT that there are no records for Great Porington which there should be. ref to About Places "included" do include the correct OTHER near places.

There was another report of  mine in last few days about Nearby feature - do they link together?    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Why should that list contain any specific places? The search has terminated
having reached the maximum. The same applies to any form of search that
hits the maximum. There is no specific logic to those results that are
displayed. They are simply the first 250 records produced by the search
that meets the criteria.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
I thought that they are found and listed in distance from the specified start point. In the past they seem to have been so.
Was that not the case? or just by chance?

I have just run this same query again, but put a data range in.
this time I do get some Great Poringland records in the result and yes, they are all scattered about because the records look like in data order.

But, looking at the list of places included it says:
Search Logic: We have records within these places:
and goes on to list the places but excludes the Great Poringland name , which seems a bit not logical.

**Comment by benwbrum** [comment]
If we are excluding thevcenter place from nearby searches, that's definitely a bug.

**Comment by Sherlock21** [comment]
If, as Kirk says above, the list that is shown has no credibility because of the 250 limit warning, then its confusing. We should not show any results. Just the warning.
OR change the order of showing  the results so that one gets the Nearest the centre, working outwards, until the limit is reached. as I suggest above.

**Comment by Captainkirkdawson** [comment]
We are NOT excluding the center point

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Now there is the best solution yet

Display nothing but the error message on ALL searches that exceed the
maximum. This issue is not limited to the nearby feature.

The nearby feature works according to specification

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
The original user requirement was to take the centre point and work out from there to get those of the particular name that move a bit away from the "home village"

So, Home base place name,
then move radially out in steps: Base + 5miles
and so on:  Base + 10 miles; Base + 20 miles or whatever works out reasonable.

Then the question of maximum number of records to return arose, and setting a limit of 250, one expected that it would be the records from furthest out radius that would be discarded. This is supported today by the list of place names & their radius which is given in the About text, and starts at 0 miles and increases outwards.

I don't like disagreeing with Kirk, but when its an issue that I have been deeply involved in, then I mist make my position clear. When i tested out the feature, I cannot imagine that I would "pass" a result like that which I now see here. It may of course be that my testing did not happen to have the configuration of records that show this present result.

The feature may work according to the software spec, but it does not work according to the original user requirement -which I wrote. 

EB

**Comment by Captainkirkdawson** [comment]
Rarely do I disagree but I am certainly disagreeing with this stated problem. It is invalid. "Searching problem: when Nearby is ticked, Origin place is excluded from results" There is no searching problem and the origin place is not not excluded from the results.

During testing it was agreed that rather than work out we would work in. This was because of concerns over immediate and automatic doubling and its impact on the server through repeated doubled searches. The software still has the ability to go both out and in. Since then we did implement the limit which, most of the time, avoids server overload.

**Comment by Sherlock21** [comment]
Considering the second para, I fully agree with what you say.

So if the software to go from in to out is still there, can we not implement that rather than out to in perhaps?
Then we do see the Base Place data until the quantity gets too big and then it perhaps disappears from the selected 250?

The basic issue is that the list of places in the About list, is inconsistent with the data seen by the researcher.
As i said in an earlier note: the implication of the text is that the 250 limit has chopped off the result as one gets further out. 

So just give the 250 warning and show nothing would in my view, be more reasonable. This is what Ancestry does ( but their limit is in the 10's of thousands I seem to remember) so it would not be new to the public.
