### ISSUE TITLE
Tidy up some wording on Registration (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#257]
Issue reported by **REGManager** at 2015-06-17 12:46:18 UTC
Time: 2015-06-17T12:42:37+00:00
Session ID: e1a39fd1f181fe164d348282f9f3d1aa
Problem Page URL: [/userid_details/transcriber_registration](/userid_details/transcriber_registration)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
When registering can the word "Syndicates" say "Syndicates looking for volunteers" because people may ask why all counties are not covered.
Also, the Info button against this is losing the last part of the text as it runs into the footers.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1434545178-54769-5414/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Why was this not raised while we were doing the detailed testing over the past 3 days!!!!. Having to keep going back to code for issues like this is so inefficient.

**Comment by edickens** [comment]
Because I didn't press the Info button during testing.  The wording came 
up because I got an email saying that the FR1 list of recruiting 
counties was wrong and I have amended it ready for next week's update, 
by referring volunteers to the FR2 registration pages which made me look 
at the list of counties that are recruiting.
But this raises a good point.  It is easier, and I expect CCs will do 
it, to enter a comment using the "Report a problem" then go into the 
Waffle and create a new story, but the "Report a problem" does not give 
you the opportunity to say if it is urgent or not, and I would have 
given this a very low priority.
Kirk - You could have just left this until it was convenient to change it.
E

**Comment by Captainkirkdawson** [comment]
Please review page one last time; if acceptable it will all be deployed tonight

**Comment by edickens** [comment]
```
Very minor.  But would the help against Identifier be better to say
"Avoid using just your forename...." because as it is,
it sounds as if you shouldn't use your forename at all.
The list of recruiting syndicates starts with "Researcher" which is
what I suggested, but I thought that this same screen would be used
for Researchers but it is entitled "Transcriber Registration". 
However, I think this is still the best first syndicate in case
someone is just messing about and it will avoid going to SCs.  Your
help button is very explicit that if in doubt select England.
Otherwise, fine.  E
```
