### ISSUE TITLE
Duplicate UserID:Filename after batch Move (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#261]
Issue reported by **REGManager** at 2015-06-22 04:20:07 UTC
Time: 2015-06-22T04:05:16+00:00
Session ID: 589c6b173a1e850341227a8bbef74da0
Problem Page URL: [/places](/places)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action.%3Fcounty=Angus%20(Forfarshire)](http://freereg2.freereg.org.uk/manage_counties/select_action.%3Fcounty=Angus%20%28Forfarshire%29)
Reported Issue:
Ref: ANS Dundee
We moved a batch from "Dudee" to "Dundee" with the same Church and UserID:Filename.  At present it has a different Register Type, but what will happen if the file is corrected in FR1 to be all "Dundee" and is uploaded.  Which of the two UserID:Filename will it choose?  Now one is locked and one not, so will it choose the Unlocked?
We also did not test moving a batch into a Place with the same Church/Register Type/UserID/Filename already there.  Will it merge them?
This will happen if there are files with place name or church name typing errors in the same FR1 file.
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1434946807-2460-0109/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Unintended consequences; now you know why I wanted to go slow

**Comment by Captainkirkdawson** [comment]
No it will not merge them. There is no code to "merge". Nothing happens by magic. But for most aspects but not all it is not an issue.More after a nights sleep

**Comment by Captainkirkdawson** [comment]
Looks like we need a function to merge the two batches. Since they came from the same physical batch there should not be an issue

**Comment by Sherlock21** [comment]
That is merging with filtering out the duplicates - even multi-plicates - of course. because i remember some files did cover 3 churches and got copied into each Placename/Church . So it may be that you have more than duplicate to deal with.

**Comment by Captainkirkdawson** [comment]
Since they came from the same physical file there should not be any such
issues at this stage of our implementation. ie. nothing has been added on
line to the batch.
Remember this is the combination of 2 collection documents into one
document

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Kirk - I don't know how far you are with this, but some observations after doing a few corrections....
I am now fixing files with more than one Place in FR1 by correcting the file and uploading it again.  Most are just one entry with a spelling error.  This avoids duplicate Batches.
But this does mean that I am having to check every batch before I can move it in case I will move it to a place which already has the other part of it - if you see what I mean.  Large batches are usually OK, but a batch with just one or a few entries is suspect, but I still feel I need to check every one.  Easy to do, but time consuming as it means going to and fro between the source and destination place.
The ideal solution for me, and perhaps the easiest, would be to have a check in Relocate Batch for the UserID:Filename in the destination Place and then refuse the relocate.  The file will then need fixing in FR1.  This will avoid having to check for duplicates and other problems and no programming for merges.  Also, because Relocate asks for Church name and Register Type, it is possible to relocate and create two entries from the same File and so not merge, by inadvertently using different Church/Register Type.
(Not explained very well.  Get back to me if you need examples.)
E

**Comment by Captainkirkdawson** [comment]
The batch merge was deployed to test3 last night along with a number of other related changes. I would appreciate tour testing of the feature. While it is best to merge the small batch into the large batch from a performance perspective it will work either way.
WRT your long comment I do not fully understand the points you are making.Will correspond off line.
