### ISSUE TITLE
Destroy or Remove a batch

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#262]
It is important to remember that the whole database structure is a logical structure built from physical files.
A file is processed into logical batches according to the information it contains on place, church and register type. So a file can have many batches although by "convention" most files have only one batch.
This has no real implications for coordinators except we do have a function in the batch management tools that allows a transcriber/coordinator to destroy a batch. 
As implemented a destroy does remove the batch from the logical collection but it also deletes the physical file. It would seem that this is an inappropriate action.
Perhaps we need to simply have a destroy batch just do that. It removes the logical batch. This is easy to do as there exists a function now that does that but it is only available to the system administrator. But it does mean that we need a system to manage the physical files.

**Comment by Sherlock21** [comment]
I am sure that your logic is sound. But I am having a bit of difficulty following the terminology and translating that into what we have t the beginning of this manoeuvre and what we have at the end.
[ an off line reply my be suitable K?

**Comment by edickens** [comment]
Before we think about introducing another set of functions, and I 
understand the need that Kirk has expressed here, I think we need to 
debate the use of Batches.
At present the Register is "Register Type" such as "Parish Register".  
With this name it could cover the documents from 1530 to the present 
day.  There are date range and quality fields against the Register 
Record.  But, the quality will vary over the years and the Registers are 
a set of books, each usually covering about 50 years.  Images of these 
books are usually grouped into sets that match the books.
So my thoughts are that we need some more Batch functions.  In the 
Register functions we need "Create Batch".  The Batch name needs to be 
capable of being created.  We will need to show a link to the images and 
to identify their Quality.  But that is as far as my thinking can go 
because I cannot see how we can easily match the FR1 files to these 
Batch records.  But then perhaps we do not need to. When transcribers 
load into FR2 they can select the Batch that they are working on.
I hope this does not muddy the waters, but I think it is time to plan 
ahead so that we don't do another set of structure changes.
E

**Comment by Sherlock21** [comment]
My first comment is that there is a danger of confusion and mis-understanding possible here  from the Word Batch as Kirk has insisted in the past is his word for file as we used to call the bundles of records Transcribed and uploaded together. with names like NFKREPBA1.csv Preferred quantity being 2000 single line records.
Here  the word has become used as the contents of a Register Book.

Elsewhere. it was the quantity of records given to a Transcriber to work through.
