### ISSUE TITLE
Duplicated places (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#267]
Issue reported by **REGManager** at 2015-06-23 11:54:38 UTC
Time: 2015-06-23T11:49:01+00:00
Session ID: 785a7785c4c02889edc1431cf957d1dd
Problem Page URL: [/places?page=22](/places?page=22)
Previous Page URL: [http://freereg2.freereg.org.uk/places?page=25](http://freereg2.freereg.org.uk/places?page=25)
Reported Issue:
DEV Seaton and Beer seems to have got in a muddle.  Files were uploaded on 23 June.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435060478-18893-7009/Capture.JPG)

**Comment by Sherlock21** [comment]
Seaton and Beer is not in a muddle.
There once were 2 adjacent villages which formed one single Parish - Seaton and Beer.
BUT FreeReg is based on PLACES. these are 2 distinct places with the old parish church of Seaton and Beer being located in just one of the places - Seaton.
so that is where the files should be put.
If the CC wishes to put a copy of the files for Pre 1900 into EACH place name then fine. That's what has been done elsewhere.
There are so many lines in the DEV Main Records list under Not Approved versions of Seaton and Beer, only because of the different batches that have been uploaded with different variants of the old Parish name.

**Comment by edickens** [comment]
```
My concern is that there are four places showing with the same
spelling...



How can this happen?  This is the DEV All Places list.
E
```

**Comment by edickens** [comment]
I'm wondering now if the "Change Place Name" has been used?  This gives 
the list of places in the same county.  (There is no means to change 
county - another problem we have found to correct.)  But should this 
actually change the place name or move the Churches, Registers and 
Batches to the new place, checking for duplicates. This seems a 
dangerous function.  Much better to use "Relocate batch" then "Destroy 
Place".
E

**Comment by Sherlock21** [comment]
They are all  NotApproved lines of place name.
So the come from the fact that the file has the wrong place name - it should be either SEATON or it should be BEER

these 2 distinct places ar in the Master Places list. ready to receive the correctly named files.

[ the way the Red warniig seems to work is that only the first row in a set of "Identically wrong"  names gets the red warning.]

I have written to John telling him what he needs  to do.

EricB

**Comment by edickens** [comment]
Not programming.  Needs the data sorting out.

**Comment by Sherlock21** [comment]
When I get the revised tools for Relocating, I will be in a position to rapidly put right place name church name errors . So I we will need a Executive Policy Decision concerning: when do I intervene and correct things like this over the head of the CC who wont get on with it?
else its no good assigning these to me if i dont have the tools to do anything about it.
