### ISSUE TITLE
Overnight update rejections (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#280]
Issue reported by **REGManager** at 2015-07-04 08:01:45 UTC
Time: 2015-07-04T07:52:07+00:00
Session ID: fffaade409d8659689faa4536f9390ee
Problem Page URL: [/places?page=3](/places?page=3)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
The first night after releasing Relocate has caused quite a few rejections, mainly in Wales.
There are two problems.  In the attached, the Approved places are St. with a full stop, and the Unapproved without the full stop.  This has caused files which adhere to the standard to be rejected.  This needs fixing and will cause a lot of work for the CC.
Also, the batches that had already been uploaded have been removed.  I'm asking if it is necessary to remove these batches from FR2 if the files coming from FR1 have had their records rejected?  They could just be left as they were.  I'm not sure of the implications.  Could it mean that if the FR1 file is uploaded again it will not be necessary to force an update by having to edit the file?
E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1435996905-22742-0895/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
The issue of St, or St in the Place name is nothing to do with the software. It is what has been decided is the approved place name. We apply that test without any adjustments to the name in the file. It is the DM/coordinator who decide what is the approved name and then the software does then use it. It does seem that there is an inconsistency between the way in which St is used in the Place Name and in the Church name. In the latter there was debate for months on what the standard should be St or St. I hope we are not going to debate that now in the Place Name and reach a different conclusion!!!
The second part is not implementable as it leaves records in the database for which there is no actual entry in a file. Such records would stay for ever. We were able to keep these records because we used the Unapproved Place but with its elimination there is nothing to tag them to.

**Comment by Sherlock21** [comment]
In Place names,
Saint is St with no stop. no arguing. i know there are many which are with the stop, and these are getting changed as fast as i can.

In Church name I seem to recall the opposite was agreed for some reason. Perhaps someone can put me wise before we get to validating that  field.

**Comment by edickens** [comment]
Definitely both without the stop.
E

**Comment by Captainkirkdawson** [comment]
We agreed on no stop in churches. That is what the church processor does.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Thanks,K

So how many churches do we have that do have a stop please?

**Comment by Captainkirkdawson** [comment]
None. The processor will not create a St. for a church name

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
Boy I should know better than to say never!!!!! I found a situation tonight that was not being caught. st. Chad got through all the checks!!!!! It would not tomorrow!!!!!

**Comment by edickens** [comment]
```
And this...



But not up to you to find this.

E

_____________________________________
```

Eric J Dickens
FreeREG Chairman
    On 05/07/2015 01:48, Kirk Dawson wrote:

```
  Boy I should know better than to say never!!!!! I found a
    situation tonight that was not being caught. st. Chad got
    through all the checks!!!!! It would not tomorrow!!!!!
  —
    Reply to this email directly or view
      it on GitHub.
```
