### ISSUE TITLE
List of Church Dedications (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#282]
Issue reported by **REGManager** at 2015-07-05 06:22:01 UTC
Time: 2015-07-05T06:12:42+00:00
Session ID: 9a61343b778e47acfdd651b5db90d736
Problem Page URL: [/places?page=5](/places?page=5)
Previous Page URL: [http://freereg2.freereg.org.uk/places](http://freereg2.freereg.org.uk/places)
Reported Issue:
If you look at KEN Woodchurch you will see many Church dedications.  My guess is that these are places of baptism in a non-Conformist Circuit.  So are genuine place descriptions.
But we are having a discussion in STS as to handle this situation.  The latest thinking is to have the Place to be the centre of the Circuit, the Church to be "Circuit Registrations" (or similar) then place where the BA took place needs to go in the record, perhaps in Abode.
This is not wholly satisfactory, but  I can't think of anything better.
E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
If one looks at the details, this is one F1 file, with  many individual "church" names. Some are one-to-one, others are a few hundred records for that single "church" and one is: Vaccination records of 311 people.
This situation is ridiculous. 
If we block multiple churches in one uploaded Batch, then the Transcriber will get round that but uploading multiple single files.
But if we do block this in future, it will make the uploader think: "why?".
Sooner into proper FR2 and have Church field validation, the better.

It is not even Methodist Circuits. 
It is not a candidate for Area Registers either in my view.
There is no Register Type shown so where do the records come from?
Is it now time to make Register type mandatory?

**Comment by edickens** [comment]
```
I had this from Allan Raymond this morning about what to include in
FreeBMD2...
FreeBMD is transcribing
      what is shown in the GRO Index 1837 onwards.
It would not
    therefore be appropriate to add information
    not shown in the GRO Index.
  Which makes a lot of sense.  But it does mean that if we get
  access to birth or death records, which will either be before 1837
  or more detailed than the GRO indexes, we need to include them in
  FR2, especially if the person was not baptised.
  I mention this because it will affect what we allow for in the
  Church Dedication and Denomination.  It also means that
  technically FreeREG is not just Parish Registers.
```

**Comment by Sherlock21** [comment]
I have always considered Church Registers to be Registers of all the Places of worship & burial grounds.
I have never really accepted that it should also accept records of events that are essentially data from GRO registrations.
"Parish" is a geographical area and many religions have records which cross Parish boundaries which is why I plumped for having the records Location based - ie Place Names. The Only slight snag is how to accommodate registers which cross more than 1 place boundary. - hence Area Registers. per County.
Since the Church Name field is a Per Place name entity, we can adapt it a little to be descriptive enough to cope with these Area Registers but not whole essays about GRO records and how to read them, as they use all the available fields for the wrong data.

If FreeBMD is so pedantic about what they have in their  section, should we not take note of why they take that view?

**Comment by benlaurie** [comment]
On 5 July 2015 at 16:17, Sherlock21 notifications@github.com wrote:

> I have always considered Church Registers to be Registers of all the
> Places of worship & burial grounds.
> I have never really accepted that it should also accept records of events
> that are essentially data from GRO registrations.
> "Parish" is a geographical area and many religions have records which
> cross Parish boundaries which is why I plumped for having the records
> Location based - ie Place Names. The Only slight snag is how to accommodate
> registers which cross more than 1 place boundary. - hence Area Registers.
> per County.
> Since the Church Name field is a Per Place name entity, we can adapt it a
> little to be descriptive enough to cope with these Area Registers but not
> whole essays about GRO records and how to read them, as they use all the
> available fields for the wrong data.
> 
> If FreeBMD is so pedantic about what they have in their section, should we
> not take note of why they take that view?

The point is surely not that such data should not be collected, but that it
should live in an appropriate collection.

Whilst Allen is technically correct that FreeBMD is not the right home,
there's no particular reason FreeBMD (or FreeREG, or something else) should
not expand to cover alternate forms of data.

In the long run, I'd hope that users would be able to search across all the
projects anyway, making it less important where any particular piece of
data lives.

**Comment by Sherlock21** [comment]
Ben - i was not suggesting that this data has no place  anywhere in the group.

Rather that here in FreeReg was not it. - since our fields and the logic of FR2 was designed specifically for Parish Register sourced data.
And to cannibalise it to accommodate something  which it was not designed for, is wrong.

EricB

**Comment by benwbrum** [comment]
If we were to include this kind of record in FreeREG, I suggest that the
right way to do it is to create a new record_type (i.e. not
baptism/marriage/burial), with its own importer/transformer function.

**Comment by edickens** [comment]
This story is not about programming.  It is what we enter into Place and Church fields.  This is still not resolved and I think Pat needs to get involved.  It needs email exchanges then a decision to be posted here.

**Comment by Sherlock21** [comment]
In my view so far, no one has given any convincing  reason why freeReg should fundamentally change the nature of what our title stands for:  ie Registers.

Abode being used for comments like: Mothers Home may well be where a baptism took place but its not the Abode of the mother or baptisee. The Register Notes field is the place for comment like that if anywhere.

**Comment by PatReynolds** [comment]
Sorry if an yearlier version of this post  did not go out.

I thnk there are two issues here:
a) the definition of a church, and
b) the scope of Free REg.

For (a) we seem to be using 'church' to mean, generally, a body of believers or corporate body, rather than a building or a place. I think this is the way to use the 'church' field: so  not 'privately, at home' or 'Eastern Churchyard Extension", but 'St Peters' or 'Littlehampton Coorporation'.

For the Methodist question , does this listing help: http://www.methodist.org.uk/links/districts-circuits-and-other-methodist-organisations  It suggests the 'place' associated with each circuit.

For (b), this needs reolution by the trustees (and, indeed, is a question for all our projects.
