### ISSUE TITLE
how to find a place in London (JulieHarold)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#295]
Issue reported by **JulieHarold** at 2015-07-20 18:07:25 UTC
Time: 2015-07-20T18:05:15+00:00
Session ID: 7e27fad3aa505453e1795e77bebedead
Problem Page URL: [/freereg_contents/new](/freereg_contents/new)
Previous Page URL: [http://freereg2.freereg.org.uk/](http://freereg2.freereg.org.uk/)
Reported Issue:
Church St Dionis Backchurch - trying to find it in the database contents I have no idea where to look for it - it doesn't match any of the option listed.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Sherlock21** [comment]
First, if we have no transcriptions for the Place , then the name wont be in the County listing to search against. Then
Two standard questions for "London" - re you talking about City of London, in which case use the County = LDN. If it is in Middlesex, then use MDX. 
The other way is: look it up in Genuki Churches  database first - then that will give you the County + Church name.

**Comment by benwbrum** [comment]
Kirk requests Eric contact Julie to figure out what her goals were and how/if the UI could be made clearer.

**Comment by edickens** [comment]
I can understand Julie's problem.  It is much easier if we had a Place report, similar to the ones we use to list place names.  Perhaps it can show Churches then the number of records by type (there are no statistics at present, not even by county) and better still a summary of the Decade analysis which would show the period covered.
E

**Comment by PatReynolds** [comment]
What is her problem - what is she trying to do?

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
She wants to look in the Database Contents to see what has been 
transcribed.  In FR1 
http://www.freereg.org.uk/parishes/mdx/london.shtml#1 you can see at a 
glance both Place and Church.  Often you know the Church where someone's 
records are, but, especially in London, just that the Church is London 
or Middlesex.
I'm not saying that we should go back to the FR1 PPP format, but it is 
easier when you do not have the full details of what you are looking 
for.  So it is the pick-list system that could be better.
E

---

Eric J Dickens
FreeREG Chairman

**Comment by PatReynolds** [comment]
Hi Eric,

I see what she's trying to do now, and I agree, it's very difficult if you
don't know the name of the place (or only know an alternative name for the
place).  Would an 'all City of London' place that had in it all the
churches in the City of London in it help?  I notice there's an 'all
yorkshire', but it's empty.  Or do you think we need a link off from the
Database Contents page for help with finding churches, such as an
alphabetical listing of the city churches, with their historic wards?

Best wishes,

Pat

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by edickens** [comment]
There is a London "County" which is the City.  Selecting that brings up 
the districts.  A radius search should find the answer.
I think the problem is more to do with Greater London which takes in 
Middlesex and Surrey.  Perhaps these should be coded LDN and not MDX/SRY.
E

---

Eric J Dickens
FreeREG Chairman

**Comment by Sherlock21** [comment]
Hi,Pat.

The 'All Yorkshire' has nothing in it in the conventional sense, as you say. But that's where the crafty bit comes in. The link is a bit of coding by BenB & Kirk, whereby  the search goes off and picks up all the appropriate data from the individual places in each of the 3 Ridings. The data is only held in the one Place name.

You could do the same with City of London . but there is no need fro that because County = LDN  is all the original boroughs which comprise the City. = so just select County= LDN to get the same effect as All Yorkshire. 

I think Julie's issue id different to this idea though.
Her problem was: Knowing  a Church  name, and knowing its "somewhere in London', one can't find the Place - because our methodology does not work backwards. - you need to do it: County > Place > Church.

What Julie was wanting effectively was: County > Church >> then get a list of all the places with that church name, to pick from to complete the search set.

Its an alternative concept. And we could not readily fathom out how to offer Both starting points. So we dismissed it at the start of the project.

However, with the benefit of hindsight, we might be able to devise a solution - like the way Genuki's Churches Database works.

This would be a completely different front end though. as we pick from 2 Table backed fields.
This requires users to type in a bit of the name they need [ like St Mar will return all the names starting with those letters and give you St Margaret as well as St Mary and any others i cant think of]

too hard to write into words - just try it and see:-

http://www.genuki.org.uk/big/churchdb/

Try: St Mary in box 1, and Devon in box 2, and hit SEARCH.

then click the down arrow in the returned record:-

This is a list of every PLACE containing St Mary as a church - as in Exeter -
or as a place name.

Pick the one you think you need, and search for the location of this place with its churches within n miles radius in this case. [ but we would not use that feature, - they are doing something different to us -]

Hope this clears it up  

EricB

**Comment by Sherlock21** [comment]
Not sure I go with that for MDX / SRY as a sole grouping.

The same problem applies to all large conurbations where we have one commonly known Place name covering more than one County [ which is our next up Location group name]

take Birmingham. some is in WAR, some in STS, some in WOR.

EricB
