### ISSUE TITLE
When someone reports a problem it is not easy to find it in the Contacts list (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#304]
Issue reported by **REGManager** at 2015-07-23 06:01:50 UTC
Time: 2015-07-23T05:58:43+00:00
Session ID: 58dbb91e14a81451b0e11bf562c95f90
Problem Page URL: [/search_records/55106b15e93790f8ad2bc23e?search_id=55b08276f493fd0b9100003d](/search_records/55106b15e93790f8ad2bc23e?search_id=55b08276f493fd0b9100003d)
Previous Page URL: [http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-07-23+05%3A58%3A24+UTC&session_id=58dbb91e14a81451b0e11bf562c95f90&user_id=REGManager&problem_page_url=%2Fsearch_records%2F55106b15e93790f8ad2bc23e%3Fsearch_id%3D55b08276f493fd0b9100003d&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2F55b08276f493fd0b9100003d&feedback_type=issue](http://freereg2.freereg.org.uk/feedbacks/new?utf8=%E2%9C%93&feedback_time=2015-07-23+05%3A58%3A24+UTC&session_id=58dbb91e14a81451b0e11bf562c95f90&user_id=REGManager&problem_page_url=%2Fsearch_records%2F55106b15e93790f8ad2bc23e%3Fsearch_id%3D55b08276f493fd0b9100003d&previous_page_url=http%3A%2F%2Ffreereg2.freereg.org.uk%2Fsearch_queries%2F55b08276f493fd0b9100003d&feedback_type=issue)
Reported Issue:
All messages reporting a problem have the same Subject line "Data Error Report".
Can they have a serial number,  like this Story, then it is easy to find the correct one in the Contacts  List.  A six digit number should do!    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
From 308
As an enhancement. Can the Contact list be filtered for the CC to whom the message was addressed. At present the CC sees all Contacts, most of which do not concern them.
They need to see just the ones that have been emailed and referred to them and when they have answered it they can delete it. In this way they can check that they have answered all the ones that apply to them. It is also a good way to ensure that all Contacts do get answered because it is very easy to think that someone else has answered one, since the report does not always go to the correct person depending on what the author was doing when the report was submitted.

**Comment by Captainkirkdawson** [comment]
To be addressed as part of  #605
