### ISSUE TITLE
Multiple alternative names for County (was Restructure search page)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#313]
Issue reported by **REGManager** at 2015-07-28 06:11:49 UTC
Time: 2015-07-28T06:01:25+00:00
Session ID: b7767bb79342aa8b795d93586e74a0bd
Problem Page URL: [/freereg1_csv_files/557e202ff493fdc3c000e142](/freereg1_csv_files/557e202ff493fdc3c000e142)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_files/5462b40ae937907d700001af/by_userid](http://freereg2.freereg.org.uk/freereg1_csv_files/5462b40ae937907d700001af/by_userid)
Reported Issue:
STS, HelenB various batches are locked, but they do not show against the Place/Church which is STS/Clent.
If I use Syndicate functions and look at her batches (see attached) and then try to Browse the batch, I get "Page not found".
She is getting very frustrated because she has been trying to upload for a few days and keeps getting different messages because of different problems.  I have a long set of messages from her, in particular the fact that the record count for Clent keeps going up and down.
I don't know why some of her batches are locked and some not.  They need to be unlocked.  Michael, our new STS CC, has not been changing things.    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1438063909-32257-0368/Capture.JPG)

**Comment by Sherlock21** [comment]
This is Clent. was in STS, but Its been moved into the right County - WOR as I discussed with Michael yesterday.
So have Dudley and Oldbury.

**Comment by edickens** [comment]
OK.  I've found the batches now.  But we have a number of problems with this.
The transcriber now has files in WOR with a Chapman code of STS.  She is still transcribing these.  What will happen to her work as her UserID:Filename will match that in FR2 but not the Chapman code.
What should she change?  How will WinReg handle this?
She has been looking in STS to find her work, which she says keeps disappearing.  The place Clent is still in the STS MPN but all of her files are not.
If you look at her list of files, and then try to browse them, you get "Page not found".
What will a researcher do when they think that Clent is in STS?  Should the Alternative Place name also have the County so that we could put STS Clent as the Alternative to WOR Clent?  This will eventually sort out the researchers problem of boundary changes.
We do need to make these changes, but  need some more detailed thinking before we go any further.
E

**Comment by PatReynolds** [comment]
I would be happy with one geographic spot having an alternative name that
included different counties as well as different spellings, languages, etc.
of the place name.

Best wishes,

Pat

On Tuesday, 28 July 2015, Eric Dickens notifications@github.com wrote:

> OK. I've found the batches now. But we have a number of problems with this.
> The transcriber now has files in WOR with a Chapman code of STS. She is
> still transcribing these. What will happen to her work as her
> UserID:Filename will match that in FR2 but not the Chapman code.
> What should she change? How will WinReg handle this?
> She has been looking in STS to find her work, which she says keeps
> disappearing. The place Clent is still in the STS MPN but all of her files
> are not.
> If you look at her list of files, and then try to browse them, you get
> "Page not found".
> What will a researcher do when they think that Clent is in STS? Should the
> Alternative Place name also have the County so that we could put STS Clent
> as the Alternative to WOR Clent? This will eventually sort out the
> researchers problem of boundary changes.
> We do need to make these changes, but need some more detailed thinking
> before we go any further.
> E
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKGenProductIssues/issues/313#issuecomment-125511413
> .

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
Why would you want a different County? I can see the need for an Alternative Placename where a place has become known as something "local" say, as different to its proper Place name.
But Alternate County? 
This issus arises from the fact that in F1, some Places were Transcribed by people from STS, whereas the Places concerned are -and always were- in WOR. but their Records are at one of the  RO Offices in STS and the Place was put into STS in F1 without too much regard for structure and accuracy. Simple as  this. This relocation of data files is just a tidy up - being as I am pedantic on these matters.

**Comment by edickens** [comment]
There are boundary changes.  Huntingdonshire does not exist any more.  
Where I live here in Peterborough we are now in Cambridgeshire, but it 
has been in Northamptonshire, and some still think it is.  Stamford, 
which is near me, has parts of the town in Cambridgeshire, 
Northamptonshire, Rutland, Nottinghamshire and Lincolnshire.  The 
problem really is that a researcher may not know which county to select 
to find a place, particularly if we are using the original county.  So 
the Alternative name could be a different county but the same name so 
that it gets into the correct list of places to be searched.

**Comment by Sherlock21** [comment]
I have some sympathy with this issue. 
So a solution: instead of starting our Researcher Search selection parameters fromCount then Place name, how about a fundamental change. Use the style that Genuki Churches data base uses.

one field in which user puts the front part (or all if they know the spelling) or the place name.Then second field for County.
hit search

then the server returns a big list of EITHER: all places that begin ...as specified if only part specified, In the County if one was specified - else in the whole UK if not.
then the user picks the one they want and that populates the Place & County search.

In one simple step, it resolves having to know what County is xxxx in?
and how to spell xxyxxzzz corrrectly.
Simple. Everyone wins except the poor one who is to write it.

but I'll test it out.

**Comment by Captainkirkdawson** [comment]
The page not found aspect has been fixed.
The Batches not found issue was not real.
Title changed to fit later discussion in topic

**Comment by PatReynolds** [comment]
This issue is identical with #316
