### ISSUE TITLE
CC uploading a batch for a user. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#32]
Issue reported by **ericb** at 2014-10-21 16:10:00 UTC
Time: 2014-10-21T16:04:21+00:00
Session ID: 4125562a2ea083a2a8ed290ea439e365
Problem Page URL: [/manage_resources/539a6a3ceca9eb57f1000550](/manage_resources/539a6a3ceca9eb57f1000550)
Previous Page URL: [http://test2.freereg.org.uk/refinery/login?](http://test2.freereg.org.uk/refinery/login?)
Reported Issue:
When a user needs to upload a batch for a County that's not the one where his SC is,  then the CC concerned cannot do it using the feature of "Use other ID" as his name does not appear in the drop-down list.

eg myself ericb, [ in SC group NFK] doing some transcribing for WRY. SAY I am not able to upload for now. So want the CC for WRY to do it, as it's here County's data. My ID does not come up in the List that she can use.
Seems totally wrong as it is Data, not people it should be permitted.

EricB

**Comment by Captainkirkdawson** [comment]
Not convinced about this, Your SC can upload  the file for you if for some reason that you cannot.

**Comment by Sherlock21** [comment]
This issue is about DATA.
and the division of labour between SC and CC is: CC = DATA.

Therefore, the County Coordinator for the County with which this Batch is concerned should be the one to assist in uploading it on behalf of the Transcriber.

Hence: WRY data = WRY County Coordinator = Ali Hill.
There is no issue as far as I am concerned.

The alternative would be for the Transcriber to faff about and change their Host Syndicate to WRY, then get the Batch uploaded, then change back to whichever Syndicate will be needed next.
