### ISSUE TITLE
Checking the new data entry system (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#348]
Issue reported by **REGManager** at 2015-08-14 10:48:26 UTC
Time: 2015-08-14T10:39:43+00:00
Session ID: 12f2f4f48439dc3ec4805aa63b6db2d4
Problem Page URL: [/csvfiles](/csvfiles)
Previous Page URL: [http://test3.freereg.org.uk/csvfiles/new](http://test3.freereg.org.uk/csvfiles/new)
Reported Issue:
I first looked under Batches and could not see why there was no UserID selection, even when logged in as REGManager, but of course that would be batches for my UserID.  So looking under Manage Syndicates it is there and makes sense.
Some a minor comments.
The expected processing time should vary if all that is being done is to Validate.  Perhaps the wording should be to be "time to enter onto the database".
The Process button should be just under the selection.  It is nearly off the screen for me.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by edickens** [comment]
I have uploaded a File and put it into a UserID using "Manage Syndicates"/"Upload New Batch" but now I need the report to show the list of Files that have been uploaded and not processed.  Should I select by the UserID I chose?  But I see that if I select "Batches" and "List Batches" my unprocessed one is there, even this is not the UserID I chose, probably correct to be mine until it is processed.  However a report for "Unprocessed Files", as opposed to batches, could be useful.
I do find it difficult to find my way around the menus, particularly if I have not written down the relevant details.  But that could be because I am working under REGManager which has all the options.

**Comment by edickens** [comment]
Having only verified the file (error free I assume as no comment made) and come out of uploading,  it is in the list of files in Orange - correct.  But my only option seems to be to Process PR and is gives me "Yes or No" and not the option to do it now or overnight.  I now have a files in Test3 waiting for overnight processing!!!

**Comment by edickens** [comment]
```
Checked and ready to go when Kirk has finished fine tuning (replace
to be reinstated?) and says so.  I have Draft instructions ready.  E

On 03/09/2015 04:02, Kirk Dawson wrote:


  Assigned #348 to @edickens.
  —
    Reply to this email directly or view
      it on GitHub.
```
