### ISSUE TITLE
email address rather than userid in userid display (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#351]
Issue reported by **MikeNL** at 2015-08-15 16:02:14 UTC
Time: 2015-08-15T15:57:39+00:00
Session ID: dfe98240d0402766a7bd0b6919023a10
Problem Page URL: [/manage_counties/selection?option=Review%20Batches%20with%20Errors](/manage_counties/selection?option=Review%20Batches%20with%20Errors)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
Would it be possible to include the transcriber's email address either as-well-as or instead-of the UserId?

Currently I have to go into other screens to get the email address for the UserId in order to send an email requesting a correction of the error(s) being flagged.    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
That display is common to all of the selections; just different selections
and ordering. Putting the email address would make the display too large
and we felt that userid really was the most important.

At the same time I do hear and accept what you are saying.

What might be possible is to add another action which is email the person
and have it create a message that could be edited for content and then
sent,

My concern would be that are we would be getting too many actions on that
display. Perhaps we don't need then all and could drop one or more.
Personally the DES is likely rarely if ever used and is still available at
a lower level

We are reluctant to adopt single person needs as you might imagine so my
next question would be is this a need that your fellow coordinator have?

K

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Mike, I think you need to wait and see how many emails you need to send 
when we have moved fully to FR2. There are some now because of the 
overnight update, but when the transcriber loads directly into FR2 they 
will get the error reports.  They will also be able to see the list of 
place names so that they will not need to be told what to use.  I'm 
hopeful that the amount of work will reduce.  We are discussing a way 
for you to be told when a batch is complete and then you can email the 
transcriber about what to do next.  But that should be all.
E
