### ISSUE TITLE
List of Records does not display records that are in error (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#367]
Issue reported by **MikeNL** at 2015-08-19 15:27:55 UTC
Time: 2015-08-19T15:19:27+00:00
Session ID: a8a58e1cf528d6a5f7a5d5bff4a14e93
Problem Page URL: [/freereg1_csv_entries?_method=get&authenticity_token=kTKBPNocEq35X4WuV0LpzfhpVfuhajyoRml1nTfKhOw%3D&page=36](/freereg1_csv_entries?_method=get&authenticity_token=kTKBPNocEq35X4WuV0LpzfhpVfuhajyoRml1nTfKhOw%3D&page=36)
Previous Page URL: [http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=kTKBPNocEq35X4WuV0LpzfhpVfuhajyoRml1nTfKhOw%3D&page=37](http://freereg2.freereg.org.uk/freereg1_csv_entries?_method=get&authenticity_token=kTKBPNocEq35X4WuV0LpzfhpVfuhajyoRml1nTfKhOw%3D&page=37)
Reported Issue:
Looking at STSUTTMA.CSV which I know has an error on line 1757 (and FreeREG does display this as an error line in the "Errors" report) but the records displayed in List Of Records jump from 1756 to 1758, missing the error line. Surely it would be better to display the error line but maybe display it in red?

I raised another problem on the same file and record regarding file downloads not having the error line included in the downloaded file..    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
I will answer both feedbacks in the same response. (I have copied Alison
our documentation expert so that she can incorporate the underlying
concepts in her documentation)

FR2 is designed as a record based and not a file based system like FR1 or
FreeBMD for that matter).

It has been designed to support both on-line and off-line transcription.

A record with errors is not part of the database of records. It is held
separately waiting for it to be corrected. This is unlike FR1 where the
file was held in quarantine until the error of a record was corrected. In
FR2 all correct records are processed into the database.

It is expected that transcribers and coordinators will correct the record
on line using the edit capability. At the moment of correction it will be
incorporated into the database. This avoids all of the needs to process
files for correction and reloading.

Since a record has errors it cannot be included in the in the list of
records. It does not exist as far as the database of records is concerned.

The download of a file does not download a copy of the original file. It
downloads the group of records in the database  that are associated with
that userid and filename.

It does not download records in error since these are not yet in the
database.

Why do it this way? Because being an on-line system you or others may have
changed the Place/Church and Register information. You or the transcriber
may have corrected errors, you or transcribers may have added additional
records on-line. Hence what is downloaded is exactly what the system
contains. That may well NOT be what was in the original file.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1
