### ISSUE TITLE
Inconsistent page navigation/display (MikeNL)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#383]
Issue reported by **MikeNL** at 2015-08-26 07:26:33 UTC
Time: 2015-08-26T07:19:09+00:00
Session ID: e65dfc4c54612d5176a4e9497a59ba9f
Problem Page URL: [/manage_counties/selection?option=Places%20with%20Unapproved%20Names](/manage_counties/selection?option=Places%20with%20Unapproved%20Names)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_counties/select_action](http://freereg2.freereg.org.uk/manage_counties/select_action)
Reported Issue:
When you first go into the screen, the box is empty. Pressing the down arrow displays the list of unapproved names. Clicking on one of the names then displays details about that place. This is, I believe, the correct processing.

If you then choose one of the buttons available on the "place" screen an then navigate back to this screen, the cox contains the place name that has just been "processed" but the details of the place are not displayed.

Furthermore, if the down arrow is pressed, all the unapproved places are re-displayed but selecting any of them does NOT display the place details.     

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by dougkdev** [comment]
I am not sure what the issue is here as I am not quite following the
description of how to reproduce the problem.  I follow the first paragraph
fine to show the list of unapproved place names, but then the description
gets vague about which buttons he is pressing, and I'm not sure what he is
talking about with the down arrow (does he just mean selecting a place out
of the list?).  I am able to select a place from the list of places with
unapproved names, press buttons on the detail page for that place, and
navigate back to the detail page and the place information is still shown.
I can also navigate back to the list of places with unapproved names and I
can still click on the places in that list and see their details, so I am
not understanding what he is describing.  Kirk, do you know what he's
talking about?  If not, can we get some clarification? Thanks.

**Comment by Captainkirkdawson** [comment]
I am with you on this. I cannot see anything wrong. Given its age I suggest we close and move on. There have been many changes to breadcrumbs as they relate to places (including today) so it is likely not worth pursing.

**Comment by dougkdev** [comment]
Ok.  Thanks.
