### ISSUE TITLE
Manage Syndicate not showing batches (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#392]
Issue reported by **REGManager** at 2015-08-29 12:23:56 UTC
Time: 2015-08-29T12:19:13+00:00
Session ID: 75cd9dcd7ba2347bc9fe7d25473e143b
Problem Page URL: [/manage_syndicates/selection?option=Review%20Batches%20by%20Userid%20then%20Filename](/manage_syndicates/selection?option=Review%20Batches%20by%20Userid%20then%20Filename)
Previous Page URL: [http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Cambs,%20Beds%20and%20Hunts%20-%20Mary%20Korna](http://freereg2.freereg.org.uk/manage_syndicates/select_action.%3Fsyndicate=Cambs,%20Beds%20and%20Hunts%20-%20Mary%20Korna)
Reported Issue:
As reported earlier.  The Action - Manage Syndicate / List batches by UserID Filename does not show any batches.  Example attached.  But this Syndicate has not changed.  I have changed coordinators but not for this one.  So am not sure why this does not work.  I will try to find a syndicate that does work.  E    

![Screenshot](http://freereg2.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1440851036-28497-8044/Capture.JPG)

**Comment by edickens** [comment]
I cannot find a Syndicate where it does work.  In fact I cannot get it to work at all.  E

**Comment by Captainkirkdawson** [comment]
I have fixed the issue that was giving an empty display of files for the syndicate. The fix is available on Test3.
However in looking at the display of files for the syndicate I believe there is a more underlying issue that needs research. There are just not enough files being displayed. . For example Norfolk when locked at as a county has 155 pages of files. i.e about 9000. If you look at the combined syndicate of Norfolk, Suffolk and Essex there only 13 pages in total. Now some would likely have come from other syndicates but not that volume.
With one exception there are no files prior to to 2014.
I think the answer is that the selection is based on the syndicate in the file. This is most cases is historical and does not reflect the changes made to syndicates where they have been combined into one with different names.
This means we need to rethink the manner in which syndicate files are selected.

**Comment by EmJayFry** [comment]
On 04 Sep 2015 9:55 PM, Kirk Dawson wrote:

> I think the answer is that the selection is based on the syndicate in the file.
> This is most cases is historical and does not reflect the changes made to
> syndicates where they have been combined into one with different names.
> This means we need to rethink the manner in which syndicate files are selected.

WinREG has always used the County name as the syndicate.

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
That was the FR1 way but not rgw FR2 way!

**Comment by Captainkirkdawson** [comment]
Have revised the selection as well as adding the files waiting for processing action
