### ISSUE TITLE
Uploading the same batch fails but is not reported (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#393]
Issue reported by **REGManager** at 2015-08-29 15:18:42 UTC
Time: 2015-08-29T15:14:11+00:00
Session ID: 478adbf25428dedc1d62dd5bcf45c75e
Problem Page URL: [/freereg1_csv_files/55e1700de93790c601000001](/freereg1_csv_files/55e1700de93790c601000001)
Previous Page URL: [http://test3.freereg.org.uk/registers/55cdc79de9379010b0000006](http://test3.freereg.org.uk/registers/55cdc79de9379010b0000006)
Reported Issue:
I uploaded a batch LANHULBA2.CSV (LAN/Hulme) and edited a record.  The batch was then locked, correctly.  But when I corrected on my PC and uploaded again without unlocking, there is no warning that the upload had not taken place.  Similarly perhaps we need "Replacing - Are you sure?"     

![Screenshot](http://test3.freereg.org.uk)

**Comment by edickens** [comment]
Kirk - The problem gets more complicated.   I now have an Unprocessed file which is Locked.  But this is not obvious from the batch list.  That is why I uploaded with an error and could not understand why it did not show.  I'm trying with a spelling error in the Church to see if it creates a new Church.  Ideally I think we should do full validation on Place and Church if uploading into FR2.  E

**Comment by edickens** [comment]
I have now seen the email, which does state that there was a problem.  But I did not go to my emails immediately, so I think a warning on the website would help.

**Comment by Captainkirkdawson** [comment]
What do you mean the upload has failed? It either happens or it does not. If it does not succeed you will get a message telling you that it failed and why. An upload that would replace an existing file that has been processed and is in the database is a trapped error condition,  An upload that will replace a file that has only been checked will be allowed to proceed since it is assumed that if you are just checking then you will be doing more work.

**Comment by edickens** [comment]
Please close this as I now have more understanding of the upload process.  But I feel that some new users might make the same wrong assumptions as me.  E
