### ISSUE TITLE
Processing of uploaded small files - Test3 (EricD)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#407]
Issue reported by **EricD** at 2015-09-05 14:42:19 UTC
Time: 2015-09-05T14:36:20+00:00
Session ID: e981edd7110389f947e33d8234355368
Problem Page URL: [/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20(descending)](/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20%28descending%29)
Previous Page URL: [http://test3.freereg.org.uk/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20(descending)](http://test3.freereg.org.uk/freereg1_csv_files/selection?option=List%20by%20uploaded%20date%20%28descending%29)
Reported Issue:
I uploaded and checked the file for errors in the list of files.  The file showed as Orange, which is correct.  It had not been processed so I had to select Reprocess.  But it is only a small file, yet was still posted for overnight processing.
It seems that the "Process" in the Upload screen will not get used if you have to check for errors and come out to look at your emails to see if it verified correctly.    

![Screenshot](http://test3.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Sorry do not understand the point being made. Sounds like the system is working as it was designed. Reprocess always puts the batch in for overnight processing.
Personally I am unsure of the real value of the verify option, especially if used in that manner. It adds a level of complexity and uncertainty that is a real worry.  Especially if the user uses the system to correct the errors on line since they will have to download the corrected file and use that for additions etc
Fundamentally I had assumed that Verify would be used while the user was actively transcribing the batch. Likely checking at the end of a session. Making changes or corrections off line as they added new records. When finished I had assumed they would upload and process into database.
There is no value to a process where they upload, verify and then reprocess, They would have been better off to upload and process ASAP or Overnight.

**Comment by edickens** [comment]
```
My comment was that if I process the file under "Upload" it can be
processed immediately, whereas "Reprocess", even for the same file,
can only be done overnight.

Having now written up the Upload documentation, I am not sure
whether we have got the sequence right.  There are a lot of ways of
doing the same thing, all of which work.  But I think we need to
recommend a simple sequence and then only have the other Actions for
Management, perhaps not even SC or CC.

E

On 05/09/2015 16:22, Kirk Dawson wrote:


  Sorry do not understand the point being made. Sounds like the
    system is working as it was designed. Reprocess always puts the
    batch in for overnight processing.
    Personally I am unsure of the real value of the verify option,
    especially if used in that manner. It adds a level of complexity
    and uncertainty that is a real worry. Especially if the user
    uses the system to correct the errors on line since they will
    have to download the corrected file and use that for additions
    etc
    Fundamentally I had assumed that Verify would be used while the
    user was actively transcribing the batch. Likely checking at the
    end of a session. Making changes or corrections off line as they
    added new records. When finished I had assumed they would upload
    and process into database.
    There is no value to a process where they upload, verify and
    then reprocess, They would have been better off to upload and
    process ASAP or Overnight.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
I see no reason to use either replace or reprocess on a verified file
