### ISSUE TITLE
Upload into FR2 does not update the Search list of places (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#421]
Issue reported by **REGManager** at 2015-09-15 10:34:53 UTC
Time: 2015-09-15T10:30:24+00:00
Session ID: ee6312abacdbff215799fd9a5ff43a6e
Problem Page URL: [/registers/55f7e737f493fdf6f3000003](/registers/55f7e737f493fdf6f3000003)
Previous Page URL: [http://freereg2.freereg.org.uk/churches/55f7e737f493fdf6f3000001](http://freereg2.freereg.org.uk/churches/55f7e737f493fdf6f3000001)
Reported Issue:
MaryKay has uploaded a file directly into FR2, into a Place (LIN South Willingham) which is valid but has never had any transcriptions before.  The transcription shows in Active Places but is NOT in the search drop down list of LIN places.  Mick via E    

![Screenshot](http://freereg2.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
This is nothing to do with uploading directly into FR2. The same code is used regardless how how the file got there.
Suspect this is a common problem when a Place goes from No files to having a file. The Placecache is not being refreshed and hence is not in the drop down lists.

Had long suspected this which is why there was the story 350 which I have never had time to deal with; always been low on the priority list.

**Comment by Captainkirkdawson** [comment]
When a register already existed but was empty the code that updated the data present and a rebuild of the plache cache was bypassed. Correction applied
