### ISSUE TITLE
Role in FreeREG

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#43]
Eric reported in August

While discussing something with EricB, I had a look at his profile. There is no "Role in FreeREG". It should at least be "Researcher".

In the link I have given here it is at least "Pending".

See attached.

**Comment by Sherlock21** [comment]
My profile seems to work well enough without this though!

so perhaps it actually does nothing in the process, except just let everyone (who can see it) know what i do.
for that matter, where is the link to my actual list of "privileges" as i know them - ie the What I can do-

so that if I change jobs that is where one would go to add in by extra (or reduced) items. OR is thin only shown on the Profile or SysAdmin / RegMANAGER?

EB

**Comment by Captainkirkdawson** [comment]
The role in freereg is only visible to people whose role is that of a manager  since they are the only people who have a need to know. The role can only be changed by a system administrator. The role of Sherlock21 is solely that of a transcriber hence it is not visible to you.
This was the design.
