### ISSUE TITLE
what became of the PRINT THE SEARCH REPORT request? (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#441]
Issue reported by **ericb** at 2015-10-02 14:30:56 UTC
Time: 2015-10-02T14:27:47+00:00
Session ID: 72756f45f07ecd82b790a9cc597c9513
Problem Page URL: [/](/)
Previous Page URL: []()
Reported Issue:
I recall recent comments on this site which suggested that some sort of feature had been provided to print the results of a search request.

But I can't find it. - please give a clue - Or please make it more obvious!.

If i am wrong, and the feature is not going to be provided, then please explain why this decision?

ericB    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There never was a request to print the results of the search.
There was a request to print the details of a search record. That was implemented.
![capture](https://cloud.githubusercontent.com/assets/2874694/10249124/dc1aed04-68e0-11e5-9b38-7f9c8c62de73.JPG)

**Comment by Sherlock21** [comment]
K

I obviously had the wrong end of the stick.

I had believed that we were going to print the Search Results list - the list that has the 250 records limit, in a table form - since that's what looses it format however I try and copy it off screen.

[ie the page before the example you provided.]
And   as I had  a hand in writing one of these requests, what I refer to here - the page before picking View details - is what I was about.

So I guess if I want that, its Start again?
E

**Comment by Captainkirkdawson** [comment]
Absolutely. There never was a story for such a capability. 

Not sure about it as there could be up to 250 lines
