### ISSUE TITLE
List Batches not showing all batches (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#514]
Issue reported by **REGManager** at 2015-10-21 14:46:59 UTC
Time: 2015-10-21T14:42:26+00:00
Session ID: 3c7c9f2aed4f1e0c2f6885c8184c03e3
Problem Page URL: [/freereg1_csv_files/5462b41de937907d700004df/by_userid](/freereg1_csv_files/5462b41de937907d700004df/by_userid)
Previous Page URL: [http://www.freereg.org.uk/userid_details/5462b41de937907d700004df](http://www.freereg.org.uk/userid_details/5462b41de937907d700004df)
Reported Issue:
The Profile/List Batches does seem to have a problem.
Try chriselliottnbl where the list seems to stop at NBLN....
There should be 76 batches, as per the attached from FR1.  We have no reason to think that the lower end of the alphabet files have been moved or deleted.
It would also be helpful if we could have a batch count and also column sorts.  E    

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1445438819-76675-2408/Capture.JPG)

**Comment by Captainkirkdawson** [comment]
Missing with missing files caused by my batches generating a paged display while the display software had moved to scrollable.
Issue fixed but will await deployment until quiet system
Please raise count and sort as separate story. Not linked to basic issue. Think seriously about sort as they already have multiple sort selections

**Comment by Captainkirkdawson** [comment]
Deployed fix
