### ISSUE TITLE
Researchers not finding Database Contents (REGManager)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#555]
Issue reported by **REGManager** at 2015-10-28 09:07:37 UTC
Time: 2015-10-28T09:04:35+00:00
Session ID: 449a4792f05277ec9eb04499f24c5750
Problem Page URL: [/freereg_contents/5409d35eeca9ebd28e1e51e2/show_register](/freereg_contents/5409d35eeca9ebd28e1e51e2/show_register)
Previous Page URL: [http://www.freereg.org.uk/freereg_contents/5409d35eeca9ebd28e1e51e0/show_church](http://www.freereg.org.uk/freereg_contents/5409d35eeca9ebd28e1e51e0/show_church)
Reported Issue:
I'm still getting emails from people not finding the Database Contents.  Not only missing the link top left, but when they get into it, all the details, such as County Selection, and particularly Register details, are off the bottom of the screen.
If we have to use so much of the screen for the basic details, then we also need wording to say "Scroll down for more details".  E    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
How about if we change the name from Database Contents to Parish Coverage or Parishes or Registers  or Register Coverage.
We need to keep the total letters to less than 20, preferably less than 15.
Perhaps that would give people a better idea as to the content

**Comment by AlOneill** [comment]
How about just "Coverage", 8 letters?

**Comment by edickens** [comment]
```
I will ask CC and Transcribers.  I cannot understand why the present
name does not work.  E

On 31/10/2015 00:26, AlOneill wrote:


  How about just "Coverage", 8 letters?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by EmJayFry** [comment]
On 31 Oct 2015 8:33 AM, Eric Dickens wrote:

> I will ask CC and Transcribers.  I cannot understand why the present
> name does not work.  E

It's "Technical"

## 

Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
Have deployed to test3 a significant rewrite of the Database Contents. Its now called Transcriptions.

It is now possible to get to the number of records in a decade for a register in a maximum of 3 clicks. For small counties it is only 2.

On selecting Transcriptions you go to an introductory page and a county selection. (Alison comments on text please)

When you select a county you will either go directly to a display of all of the places/churches/registers if the county is less than 500,000 records or you will go to a further selection for large counties.

The second selection allows you to either select a specific Place or an alphabet range. Rather than all letters of the alphabet you can select an alphabet range. I have picked 10 ranges.

The displays from both selections are similar and identical to the smaller county display.

By using this type of display you no longer have to tunnel through place/church to get to register. All three levels are on the same display. 

The decadal display has been integrated into the register display as that is what is of interest to most people. So the register display has the decadal table up front and center and info about the register later. The transcribers names have been integrated into the decade table.

The notes for Places and Churches have been moved up in the display

There is navigation to all levels from wherever you are.

These pages all display correctly on a smartphone although it should be noted that the decade table is best viewed in Landscape hence the comment in the text

It is open for review and comment.
