### ISSUE TITLE
Place Name update history dates seem mixed up (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#572]
Issue reported by **ericb** at 2015-11-01 09:23:56 UTC
Time: 2015-11-01T09:17:14+00:00
Session ID: f5f95d77a26375fe93502c2cc1fb5222
Problem Page URL: [/places/53cd4995eca9ebee4f00b234](/places/53cd4995eca9ebee4f00b234)
Previous Page URL: [http://www.freereg.org.uk/places](http://www.freereg.org.uk/places)
Reported Issue:
There are 2  fields on the Place Name information  screen - one suggests it should be about the Place name itself, and when it was created & last changed, the other seems to be about the data ie the churches and files for that place.

But example: WRY/ Dewsbury  has dates of 30 Oct 2015 for both. This place has been called Dewsbury since the beginning. so one of these dates should reflect that.
The other should deal with the addition of records into Dewsbury.  

Other places  show the same issue  - eg NBL/Cornhill. so no doubt its generic    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
These dates can be quite confusing and unfortunately they are interconnected.
Date place information last amended is the date extracted from the document on the last time it was updated. ie a system date.
Date when record last amended is a calculated date that gets changed when a record in a batch is changed. 
Unfortunately since the last amended date is a record in the place document this will lead to the first date being changed as well.
The original idea was to try to capture when the place name was updated by the coordinator or DM. Clearly what is being done does not fit the bill.
The only information presented to the researcher is the second field and that is what they are interest in. 
The easiest solution is to drop the first field all together. Not sure of its real value. To do it properly would mean creating a new field and have that "managed by the Place update process. Likely a 2 day job. Is it worth it? It is certainly not urgent.

**Comment by Sherlock21** [comment]
I am inclined to say:
Temporarily just dont display this first field for the reasons you give. But dont take it out of all the coding - we may need it ( or something developed from it) later if we do find it necessary to resurrect the topic in future. 
So then you could close this topic?
