### ISSUE TITLE
Selecting County = CON to log on to it fails regularly (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#591]
Issue reported by **ericb** at 2015-11-05 15:35:47 UTC
Time: 2015-11-05T15:34:28+00:00
Session ID: 65b48de85bc26fa55a2402aa76cc51bb
Problem Page URL: [/places](/places)
Previous Page URL: [http://www.freereg.org.uk/manage_counties/select_action](http://www.freereg.org.uk/manage_counties/select_action)
Reported Issue:
It sees my selection of CON at log on as being just a stop. So goes nowhere.
Ericb    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Your screenshot shows you have not selected any county. There is no chapman
code in the county options breadcrumb.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Exactly

I DID click on CON on the first drop down little menu of ALL counties

-I have done it oft enough to know how to start!
CON highlighted when I clicked it - even tried a long, firm positive click in case I had been too quick.
And I repeated it a a few times from a re selected url too. 
All to no avail. AllI gor to see returned from the SELECT was the dot.

Eb

**Comment by Captainkirkdawson** [comment]
1. does it only happen with CON
2. When you select CON does it say that you are managing Cornwall before
   you select  an action
3. does it show Cornwall in the breadcrumb at that point before selecting
   an action
4. does it fail when selecting all actions if the answer to 2 and 3 is yes
   or just 1.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K
replies within your email
On 5 Nov 2015, at 17:07, Kirk Dawson wrote:

> 1. does it only happen with CON

```
it did.  (  I shut down and went of to watch the tv for a little while.) Its not happened again.
```

> 1. When you select CON does it say that you are managing Cornwall before
>    you select an action

I happened  after logging in with userID, and then my next choice is to pick the County from drop down list.
This was where it highlighted the CON, then when I hit SELECT at the bottom of screen, instead of connecting me to CON and changing the breadcrumbs, it just came back with this full stop 

> 1. does it show Cornwall in the breadcrumb at that point before selecting
>    an action

no never got that far

> 1. does it fail when selecting all actions if the answer to 2 and 3 is yes
>    or just 1.

I did not try any other Counties.
- gave up and put in the report before I did anything and forgot to do that!
  > 
  Other domestic callings then stopped me.

I will log on again now. to CON.

\its all OK now. - so don't follow up unless i happens again.

Thanks
Eb

> Kirk Dawson
> Fairmont Hot Springs, B.C.
> V0B 1L1
>

**Comment by Captainkirkdawson** [comment]
We are all using this selection system and have been for months. Code has not been changed.
You must always get an action selection menu after selecting the county or syndicate which both use the same code.
If you say you immediately got the place display then I suspect a double click at the time of the county selection
