### ISSUE TITLE
The FreeREG site & the Get-Scan area (Tim37)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#647]
Issue reported by **Tim37** at 2015-11-25 11:40:39 UTC
Time: 2015-11-25T11:34:44+00:00
Session ID: 1422af3d0c01b6bb28c9f1ad83e1d02f
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Isn't it time that a link was put in the 'Members' page at FreeReg that went directly to the Getscan part of the service.  This would save time & joined up thinking..
Also a tab in the 'Members' area that flagged when new files [or possibly] a list of the files that are currently ready for download.

Tim in West Sussex    

![Screenshot](http://www.freereg.org.uk)

**Comment by PatReynolds** [comment]
bcc Tim.

These are #219 - scheduled for Version 1.5 (Tim, we are currently beginning
work on 1.4, work on 1.5 is due to start January, but this may be delayed).

On Wednesday, 25 November 2015, FreeUKGenIssues notifications@github.com
wrote:

> Issue reported by _Tim37_ at 2015-11-25 11:40:39 UTC
> Time: 2015-11-25T11:34:44+00:00
> Session ID: 1422af3d0c01b6bb28c9f1ad83e1d02f
> Problem Page URL: /manage_resources/new
> Previous Page URL: http://www.freereg.org.uk/refinery/login
> Reported Issue:
> Isn't it time that a link was put in the 'Members' page at FreeReg that
> went directly to the Getscan part of the service. This would save time &
> joined up thinking..
> Also a tab in the 'Members' area that flagged when new files [or possibly]
> a list of the files that are currently ready for download.
> 
> Tim in West Sussex
> 
> [image: Screenshot]
> https://camo.githubusercontent.com/21479eb4918ad134dc1ef9321a1ea1582ace4dd8/687474703a2f2f7777772e667265657265672e6f72672e756b
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/647.

## 

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK
