### ISSUE TITLE
Use of Email Address Included in File Header  (Sue036)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#655]
Issue reported by **Sue036** at 2015-11-28 18:50:03 UTC
Time: 2015-11-28T18:45:44+00:00
Session ID: 83a0f038e8a5dadf379e265390dcb36d
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Can the Help information please be enhanced to include an explanation of what the email address of the the transcriber will be used for if it is included in the file header information? This would help trabscribers to decide whether or not to include their email addresses and, if they have more that one email address, which email address to include. I, for one, am reluctant to give my main email address if it is to be shared publicly.    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
The email address in the header is only used if there is no email address associated with the userid something that should never occur.
If used it would only be available internally in the system and available only to coordinators. It is not published.
Alison has asked that I prepare a note for her saying what in the header is now used in FR. Maybe one day I will get the time!

**Comment by PatReynolds** [comment]
I can't find the earlier issue that this duplicates, so not closing for now.
Is this a privacy issue, or do we never show the headers to the public?
Will inform Sue that if a user associates an email address with their ID, then no email address will appear in the header, and the email address will only be available to the Coordinators and management.

**Comment by Captainkirkdawson** [comment]
Unaware of any duplicate.

**Comment by PatReynolds** [comment]
Sue explains that this was a request for change to help documentation:
"I was asked to put my email addess in my file header but when I asked why, no one was entirely sure!

"I raised this as a problem on the advice of Eric Dickens because when I asked the question no one could find anything in the FreeReg 'Help' about this. He asked me to raise it so that the 'Help' could be, eventually, updated to answer the query. Sorry if my problem report was not very clear. "

**Comment by AlOneill** [comment]
After investigating what happens if the field is left blank, the File headers page now has:

The second data field is the email address of the transcriber: it is not made public and is accessible only to coordinators, for information. You may leave it empty, in which case the field is filled from the Profile.
