### ISSUE TITLE
Records from a Deleted batch still appear in Search Results. (ericb)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#664]
Issue reported by **ericb** at 2015-12-03 16:06:56 UTC
Time: 2015-12-03T16:01:20+00:00
Session ID: a7ee89aeb9a6027f0c5433c6fd2f6217
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/refinery/login](http://www.freereg.org.uk/refinery/login)
Reported Issue:
Earlier today I deleted a little file from FR (Wiltshire/ UnKnown place/ UnKnown church)

Now at 16:00 GMT I ran a search to see if one of these records was against any know place in Wiltshire.
Surprise is that the deleted record appears in my search result. 
What's gone wrong - or does the link to Researcher  search tables only update infrequently?

In attached, the 2 rows of NK were in the 20odd row file/ batch that I deleted

![Screenshot](http://www.freereg.org.uk/home/apache/hosts/freereg2/production/tmp/carrierwave/1449158816-43231-6202/Deleted_batch_contents.jpg)

**Comment by Captainkirkdawson** [comment]
The records for a files are actually deleted as part of the overnight
processing.

Why? Because the software applies a system-wide lock on all access to the
database while the entries and index entries are deleted. No searches are
permitted. Imagine the impact of a large file deletion; no searches for
5-10 minutes. So rather than delete entries during prime time we do it in a
controlled manner overnight.

Kirk Dawson
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
K

fine,thanks for this explanation. I did not know the detail, and it seemed like something wrong - like i had zapped the wrong file!

Close the #.

EB
