### ISSUE TITLE
Omission of baptismal name leads to search engine missing the birth (gupton)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#706]
Issue reported by **gupton** at 2015-12-07 11:27:24 UTC
Time: 2015-12-07T11:16:28+00:00
Session ID: 16b9c1a41e6c1bb71867c748bbe8bcab
Problem Page URL: [/information-for-transcribers/entering-data-from-registers](/information-for-transcribers/entering-data-from-registers)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
A transcriber has written to me:
"I selected all children baptized with the surname FOSTER in Stone in Oxney 1539-1600 and then checked the result against my own file. 17 were found in FreeREG but 19 in my file. The file when submitted after the upgrade was ERROR FREE. The two missing had no forenames in the parish register. I believe they were picked up in FreeREG1 prior to the upgrade but I may be wrong. Is this a known Bug?"

My suggestion would be to put \* in the field. Is that OK? 
Perhaps some advice can be added to the webpage instructions on this point.

Thanks

Graham

grahamjgu@gmail.com    

![Screenshot](http://www.freereg.org.uk)

**Comment by benwbrum** [comment]
If we get the filename, we can look into this.

**Comment by PatReynolds** [comment]
I have requested the filename from the transcriber.

**Comment by Captainkirkdawson** [comment]
The file is BobChown.KENSTIBA1

There are 2 records as indicated there there is no forename. These are not retrieved on a simple search for Foster. they should be as they have the surname Foster.
The records are picked up by searching for family members.

**Comment by benwbrum** [comment]
I've tracked down the records and duplicated the problem.  Apparently we never tested for unnamed baptisms (nor, I suspect, burials).

Here's the `freereg1_csv_entry` record:

```
{"_id"=>"55dc17e1f493fdde800609ee",
 "error_flag"=>"false",
 "line_id"=>"BobChown.KENSTIBA1.CSV.242",
 "file_line_number"=>242,
 "register_entry_number"=>nil,
 "birth_date"=>nil,
 "year"=>"1553",
 "baptism_date"=>"05 Nov 1553",
 "person_forename"=>nil,
 "person_sex"=>"F",
 "father_forename"=>"William",
 "mother_forename"=>nil,
 "father_surname"=>"FOSTER",
 "mother_surname"=>nil,
 "person_abode"=>nil,
 "father_occupation"=>nil,
 "notes"=>"No child's name.",
 "film"=>nil,
 "film_number"=>nil,
 "county"=>"KEN",
 "place"=>"Stone in Oxney",
 "church_name"=>"St Mary",
 "register_type"=>" ",
 "record_type"=>"ba",
 "freereg1_csv_file_id"=>"55dc17d4f493fdde8006069a",
 "record_digest"=>"51ODw7vdQwrxWFHMo8XsoA==",
 "u_at"=>2015-08-25 07:23:13 UTC,
 "c_at"=>2015-08-25 07:23:13 UTC}
```

As you can see, it has no field for the person_forename at all.

This is transformed into this `search_record`:

```
{"_id"=>"55dc17e1f493fdde800609ef",
 "transcript_dates"=>["05 Nov 1553"],
 "search_dates"=>["1553-11-05"],
 "location_names"=>["Stone in Oxney (St Mary)", " [Parish Register]"],
 "search_soundex"=>[{"first_name"=>"W450", "last_name"=>"F236", "type"=>"f"}],
 "record_type"=>"ba",
 "chapman_code"=>"KEN",
 "file_line_number"=>242,
 "line_id"=>"BobChown.KENSTIBA1.CSV.242",
 "transcript_names"=>
  [{"role"=>"f",
    "type"=>"other",
    "first_name"=>"William",
    "last_name"=>"FOSTER"}],
 "freereg1_csv_entry_id"=>"55dc17e1f493fdde800609ee",
 "place_id"=>"53cd4960eca9ebee4f005504",
 "search_names"=>
  [{"_id"=>"55dc17e1f493fdde800609f0",
    "first_name"=>"william",
    "last_name"=>"foster",
    "origin"=>"transcript",
    "type"=>"f"}]}
```

That record contains one name only, a family member named William Foster.  Since only a family member is named, the record is only retrieved in an _include family members_ search.

Frankly, I'm surprised that the search engine and transformation process get as far as they do, rather than barfing when such a record is encountered.  I've never given any thought to how the search engine should behave for nameless records, though of course burials unidentified corpses and baptisms of unnamed infants happen all the time!  

In the case of the record here, should we presume that the child has the surname of the father, and match searches against that name which don't specify a forename?

**Comment by PatReynolds** [comment]
I think it would be reasonable for a search to return where the surname
'Foster' is called - but I don't think it should be displayed as - Foster,
because that's not what the register says.

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Sherlock21** [comment]
Is the plan then to allow for missing first names [ across the board?]
or to check and reject if empty?

A statement of which are the mandatory fields might be useful for everyone - it could go in the guide notes on "what gores in where" fields

**Comment by edickens** [comment]
```
A blank firstname is valid.  For example, a burial of a new born. 
But there could be a check on MA and BA as they should never be
blank.  In some old MA the wife's name was not entered.  She was
just "The wife of" as women had no status then!!!  However, this
should be sorted out at data entry validation.  Searching should
always assume that a blank is possible, as you cannot assume that
all previous transcriptions have been so validated.  E

On 23/01/2016 18:48, Sherlock21 wrote:


  Is the plan then to allow for missing first names [ across the
    board?]
    or to check and reject if empty?
  A statement of which are the mandatory fields might be useful
    for everyone - it could go in the guide notes on "what gores in
    where" fields
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Captainkirkdawson** [comment]
Confirmed the code change has fixed the issue on test3 with the new processor
