### ISSUE TITLE
35927749 Data Question (Wendy Jones)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#736]
Issue reported by **Wendy Jones** at 2016-02-20 19:55:49 UTC
Time: 2016-02-20T19:51:29+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Hello:

I noticed on a general screen earlier about contacting the 'data' manager if errors were found.

While I was searching Nott and Knott in MDX St George Hanover Square today I noticed quite a few duplicates. I had no first names, no dates and marriage. 

Not sure if this is from different transcribers, or an upload problem.

Sincerely, Wendy :)    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
See also #742

**Comment by dougkdev** [comment]
This particular report looks like data problems rather than a system
problem.  I did a search on Nott and Knott in MDX St George Hanover Square
to reproduce the reported problem.  All of the duplicates I see are the
result of the same information existing in more than one file, except for
the Frances TOBB / Michael NOTT (last of the three listed under Nott
below).  That one is because the same information is in the file in two
places.  In that particular file (judybrett.MDXWSGMA.CSV) it looks like the
same info has been included twice for many more than the ones that show up
in NOTT searches.

Here are the duplicates I see from the Nott / Knott searches:

Searches for Nott:

Catherine ANDREWS / John Neal Pleydell NOTT marriage 29 Jun 1766. These two
records come from two different transcribers
(wbarraclough.MDXWSGMA4.CSV.1348 and mikewright.MDXWSGMA.CSV.80)

Mary Chamberlain / John Nott married 17 May 1768.  These two records come
from the same two different transcribers (wbarraclough.MDXWSGMA5.CSV.526
and mikewright.MDXWSGMA.CSV.957)

Frances TOBB / Michael NOTT marriage 15 Aug 1796. judybrett.MDXWSGMA.CSV.771
 and judybrett.MDXWSGMA.CSV.1754

Searches for Knott:

Elizabeth KNOTT / Richard SADGROVE marriage 21 Jul 1755.
(wbarraclough.MDXWSGMA2.CSV.509 and Wend.MDXWSGMA.CSV.2219)

Elizabeth KNOTT / Alexander JEFFREYS. (wbarraclough.MDXWSGMA6.CSV.550
and mikewright.MDXWSGMA1.CSV.715)

 Jane FRADSELL/ Cornelius KNOTT.  (wbarraclough.MDXWSGMA6.CSV.596 and
mikewright.MDXWSGMA1.CSV.761)

Mary BYRN / William KNOTT.  (wbarraclough.MDXWSGMA.CSV.591
and Kyran.MDXWSGMA.CSV.579)
