### ISSUE TITLE
49850458 No screenshots in HELP system (Michael)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#777]
Issue reported by **MikeNL** at 2016-07-30 23:20:58 UTC
Time: 2016-07-30T23:08:39+00:00
Session ID: 580322b13eb164be58008acd98b9d19c
Problem Page URL: [/information-for-transcribers/file-and-batch-actions](/information-for-transcribers/file-and-batch-actions)
Previous Page URL: [http://freereg2.freereg.org.uk/information-for-transcribers](http://freereg2.freereg.org.uk/information-for-transcribers)
Reported Issue:
As CC I have received an email from one of my transcribers. A part of it is included here: "Tried to replace but told this was not possible as file is locked – need to download updated copy & remove lock.
How?
Went to HELP – told to remove lock by downloading  a copy of the edited file – How?
Would appreciate some guidance on this".

Now, for a CC to explain this is virtually impossible because the screens that are available to a CC are much more powerful than those for a transcriber and, certainly for me, I cannot log into FreeREG as a transcriber. If there were screenshots in the HELP, all that would need to be done to answer this transcriber's query would be available in the HELP and the query would almost certainly disappear.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
Michael,

When you log in as CC, select Help, then in the first sentence of the 
text there is "Information for transcribers".  It is a link, but is not 
very visible because of the colour.  It is a link because a hand come up 
when you hover over it.  That takes you to the Transcriber's Help.  You 
can then copy and paste the relevant URL for them to see the correct 
page.  E
