### ISSUE TITLE
Images on information links on search page

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#793]
(from BenL)
While rollover works on the information links, the images are not there and clicking on them takes you to the top of the page.
(Works fine for me in Chrome)

**Comment by Captainkirkdawson** [comment]
Do not understand. There are no images to be displayed on roll over just text. What browser?

**Comment by PatReynolds** [comment]
Pat to ask Ben: if still an issue

**Comment by AlOneill** [comment]
There are no longer any (dummy) links on the info images on the Search page, so clicking will have no effect.

I have observed that, on occasion, I have to log in to see *any* images (content, rather than CSS). Don't know why this should be so. Could it be because some/many Mac users close browsers, so ending a session, only infrequently? -- I do not know what device BenL was using.
