### ISSUE TITLE
Regular check and enforcement of valid email

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeUKRegProductIssues#796]
Regularly require volunteers / registered researchers to re-validate their email address.

**Comment by ghost** [comment]
​And telephone numbers for Coordinators.

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by edickens** [comment]
Messages from the server bounce from time to time, but we do nothing about it.  This is usually because the User has changed their ISP  or put in a filter.  As management we assume that they have got the message and do not know that it never got through.  Messages getting through is most important for error messages when files are uploaded.
Either bouncing emails need to be sent to the SC so that they can take action, or as Pat suggests, say once a quarter, we email everyone and ask them to confirm that their email address is correct.  If we get no reply within a week then their UserID should be disabled.
We also have a slot for telephone number, but not many use this.  The problem is, particularly with Coordinators, that if the email does not work we have completely lost contact.  So rather than a telephone number, we need "Emergency contact information".  This could be a telephone number, but it could be a relatives email address, or even a postal address.  Just some means to contact them should we get no reply to an email.

**Comment by Captainkirkdawson** [comment]
WADR  the response has taken 1 story and added multiple unrelated stories. 

 WRT to this story. Regularly require volunteers / registered researchers to re-validate their email address. There are several ways this could be addressed. 
A mail out every few months.  Personally dislike and ignore on other systems that do it.
A request to reconfirm email address at log in after a specified period eg;get confirmation after 1, 2 or 3 months?

**Comment by edickens** [comment]
```
I like the login reconfirm request.

The rest of what I wrote was to explain the reason.  E
```

**Comment by PatReynolds** [comment]
This now may be via a single gateway.

**Comment by PatReynolds** [comment]
​Could be through the password reset?  I.e. the password is regularly
cancelled, forcing a password reset, which uses the email address.​

**Comment by Sherlock21** [comment]
Are you suggesting that you devise a system of demanding a Password reset by the user, at predetermined intervals?

That will go down like a lead balloon in my view. This not one of those ID's that has commercial sensitivity as far as the user is concerned, so its PW is one for life - to save having to have so many to regularly change and remember.

Send an email to the registered email address, and require a response "Or Else" by all means.

**Comment by helhyde** [comment]
Would it be ok if the password could be the same?

**Comment by Captainkirkdawson** [comment]
Since I am unfamiliar with any gateway system and how it might or might not function cannot comment nor how it would interface with our current userid collection and management practices.
Is the password reset suggestion for how that would be implemented under the gateway system if so its not relevant to FR development.
I agree 100% with EricB on automatic password reset requests. I hate them with a passion wither or not they accept the existing one. They and their resetting is my business.
Furthermore password resetting is very different from the subject of keeping email addresses up to date.
Story would be on hold until requirement on FR is known

**Comment by helhyde** [comment]
Technical specification for the Volunteers Gateway will be shared through
the tech list probably later this week.

_\- -_

_Dr Pat Reynolds_
Executive Director
Free UK Genealogy  http://www.freeukgenealogy.org.uk/
A charity registered in England and Wales, number 1096940, transitioning to
a Charitable Incorporated Organisation registered in England and Wales,
number 1167484
VAT registration: 233 0105 70

​+44 ​1904 541411​ +44 7943 145387

36 Albemarle Road, York, YO23 1ER, UK

**Comment by Captainkirkdawson** [comment]
Implemented a process in 978 as we need a flag set regardless
