### ISSUE TITLE
57575025 Church denomination can be accidentally overwritten (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#826]
Issue reported by **STSCoord** at 2016-10-28 09:03:45 UTC
Time: 2016-10-28T08:59:27+00:00
Session ID: 8dd3a414069ae2cc25436d0ed080d137
Problem Page URL: [/churches/55eaf404f493fdd3ed0001a9/edit](/churches/55eaf404f493fdd3ed0001a9/edit)
Previous Page URL: [http://www.freereg.org.uk/churches/55eaf404f493fdd3ed0001a9](http://www.freereg.org.uk/churches/55eaf404f493fdd3ed0001a9)
Reported Issue:
I had a church that I set to the denomination "Unitarian". I saved the record. I then realised that I had made a mistake on the Church Location, amended it and re-saved the record. To my amazement, the denomination changed to "Church of England".

This should not happen!    

![Screenshot](http://www.freereg.org.uk)

**Comment by benwbrum** [comment]
Assigning this to Israel.  He'll need a pointer as to how users get to this part of the app.

**Comment by ghost** [comment]
Will be happy to guide him if needed​

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by israelriibeiro** [comment]
Hi, Sandra and @benwbrum.

I discover the problem over here. When you hit edit button, Church of England was being pre-selected in html. Look here: [Church Of England](https://github.com/FreeUKGen/MyopicVicar/blob/master/app/views/churches/_form.html.erb#L12)

My solution to this problem is check if the church already has an denomination, if don't, you select Church Of England. Take a look: [Choose already saved denomination](https://github.com/FreeUKGen/MyopicVicar/blob/ae3ef055e140446fb88cb611955bc884c9b29ffa/app/views/churches/_form.html.erb#L12) .

**Comment by ghost** [comment]
Sorry I am a bit fuzzy here, but are you saying each time someone goes in
to edit​ church information, they would need to reselect the denomination
if it is not Church Of England?

---

Sandra Adams-West
_FreeREG Communications Coordinator_
____________________________________________________________________________________

**Comment by Sherlock21** [comment]
there is no mention of Which Action feature you are using here, to do all this.

**Comment by israelriibeiro** [comment]
@Sherlock21 , what did you mean?

My solution was this:

```
:selected => ["Church of England"] 
```

to this one:

```
:selected => ( (@church.denomination.empty?)? ["Church of England"] : [@church.denomination] )
```

If church denomination is not empty, chuch denomination already selected before will 
the first choice, it'll be selected.

@CommsCoord , the situation is this: when you, for the first time, changed the denomination, it went ok, cause you chose to do it, you selected the option you wanted. But, then, you tried to edit location and, in html, Church Of England is always pre-selected when you are on edit view.

**Comment by Sherlock21** [comment]
The person who raised this issue is a CC. So Simply, which Function was he using, that gave rise to tho problem? Life's hard enough without having to guess what was actually being done.

**Comment by Captainkirkdawson** [comment]
Eric it is in the initial post. He was doing a Church Edit.

I believe the solution proposed by Israel is quite correct and appropriate.

Since I have no access to a development server I cannot test his code. But I believe that Ben should pull into test3 and allow you and any others to test it

Well done Israel

**Comment by israelriibeiro** [comment]
I opened a pull request. Thanks, @Captainkirkdawson . Could you test the code, @benwbrum ?
[Pull request](https://github.com/FreeUKGen/MyopicVicar/pull/1014)

**Comment by Captainkirkdawson** [comment]
Code does not work when the church is being created. See 862 and the errbit church creation failures
