### ISSUE TITLE
59163553 Enhancement Suggestion (Pat Lawrence)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#842]
Issue reported by **Pat Lawrence** at 2016-11-15 18:19:13 UTC
Time: 2016-11-15T18:08:07+00:00
Session ID: 70b84bf5160e7505b3fa4da2613598e7
Problem Page URL: []()
Previous Page URL: [http://www.freereg.org.uk/contacts/new](http://www.freereg.org.uk/contacts/new)
Reported Issue:
Please, can you adjust the black boxes that pop up over a search field, so they don't block our entry into the field? Example, above: I typed my name and tabbed to the e-mail address field, and I had to stop and disengage the black info box before I could fill in the form. Tabbing is a practical method to advanced between fields - black boxes standing in the way is not practical and is very annoying. The black box could be place above, rather than over a field... Also, what is the reason for labeling the Details field in a Results page as Row 1 or Row 2? I can't think of any reason a researcher would need a row number. They want to know that's where they can get more details. Thanks for all your work putting this site together. I use it everyday!    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
Could you please let Pat know that the opening of the info button on tabbing and the use of row numbers are accessibility aids for disabled researchers who are using screen readers and other software to navigate the website.  Double tabbing does take a user to the input box. We do take note of the suggestion to position the  information on tabbing so that it does nor interfere with the entry box and investigate its practicality. .

**Comment by Captainkirkdawson** [comment]
Mind you after a nights sleep I don't think the position change would do anything as the user has to tab the second time to get into the entry box

**Comment by ghost** [comment]
I will close this for now. Perhaps in time it can be revisited.
