### ISSUE TITLE
59229373 How do I delete a syndicate? (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#847]
Issue reported by **REGManager** at 2016-11-16 12:36:13 UTC
Time: 2016-11-16T12:34:15+00:00
Session ID: 0b74f985fe0c161fb09d597452f2acff
Problem Page URL: [/syndicates](/syndicates)
Previous Page URL: [http://www.freereg.org.uk/manage_syndicates/select_action](http://www.freereg.org.uk/manage_syndicates/select_action)
Reported Issue:
I have moved out all UserIDs from WIL, but now I need to delete the Syndicate because Doreen has taken it on in Rest of England?    

![Screenshot](http://www.freereg.org.uk)

**Comment by Captainkirkdawson** [comment]
There is no ability to delete syndicates. I am surprised that  you want to. It was a syndicate it did work and some reports should acknowledge that. Why not simply assign Doreen to the WIL coordinator role

**Comment by edickens** [comment]
This goes against the principle of Syndicates.  A SC should have one list of the people who work for them.  Otherwise we will end up with one Syndicate per County and then have to move transcribers around as they work on different counties.  WIL is not really a Syndicate, just Jim Parson's group of transcribers.
There are also syndicates for Assistant SCs, (See SOM) and the number of assistants could change and that is when we may need to delete a Syndicate.
But this is not really important.  I can just rename the Syndicate as Not in Use and then rename it when needed.
Suggest this is closed.  E
