### ISSUE TITLE
Token Issue: 61300500 UserID trevpem cannot be accessed by owner (Sandra)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#864]
Issue reported by **CommsCoord** at 2016-12-10 11:55:00 UTC
Time: 2016-12-10T11:52:55+00:00
Session ID: e948b8d6404b76322e45097a358819f9
Problem Page URL: [/feedbacks](/feedbacks)
Previous Page URL: [http://www.freereg.org.uk/feedbacks](http://www.freereg.org.uk/feedbacks)
Reported Issue:
Owner of the account trevpem has been unable to access his account and keeps getting the password token error message after new pw request.    

![Screenshot](http://www.freereg.org.uk)

**Comment by edickens** [comment]
We have identified an Invalid Token problem and I will send an
    email to all SCs.  It is very obscure.  E

**Comment by PatReynolds** [comment]
See also #1021 and #1012

**Comment by Captainkirkdawson** [comment]
EricD reported to SCs
The problem is that when anyone submits a Password Change Request, either themselves or via their coordinator, a token is generated and saved against their UserID.  But when they click on the link in the email they receive, they may get logged into a different server which will not have that token, but a previous one.  Hence the token is shown as invalid.  But if they are lucky enough to get the same server, then the token will be valid.  So sometimes it works and sometimes it does not.  This same logic applies to new volunteers who are setting their password.

**Comment by Captainkirkdawson** [comment]
I am sorry that I do not accept this explanation. The token is a refinery object and as such is maintained in the sql user table not the userid mongodb collection.

**Comment by Captainkirkdawson** [comment]
The cause is that the devise mailer 
<p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p> translates into

http://www.freereg.org.uk/cms/refinery/users/password/edit?reset_password_token=

The Haproxy load balancer is set to have have all refinery urls go to colobus. This was fine until we implemented the major upgrade when refinery was mounted in cms.

Hence we need to have Haproxy refer cms/refinery urls to colobus. Request has been made of L

**Comment by AlexAvlonitis** [comment]
Thanks @Captainkirkdawson i was about to update with details this morning. that's exactly what it is, mysql replication issues, if you write on a slave rather than on master. Haproxy redirection is a nice solution, i was looking into this gem https://github.com/bdurand/seamless_database_pool to use a master server for all the writes, and for the reads use the slaves. But i think Haproxy would be easier and better, without touching the rails application.

**Comment by Captainkirkdawson** [comment]
I believe the change made to HAProxy have resolved this problem. Need to know if problems reappear
