### ISSUE TITLE
WInFreeREG: Upgrade from 1.0.1 to 1.1.1

### ISSUE THREAD

**Issue by EmJayFry** [FreeUKGen/FreeUKRegProductIssues#906]
Installing version 1.1.1 over the top of version 1.0.1, or after uninstalling version 1.0.1 firs, can give rise to a crash when opening any local transcription file.

**Comment by EmJayFry** [comment]
Causes
======
Investigations show that the crash (caused by an OutOfMemory Unhandled Exception) occurs when the program attempts to restore the window layout corresponding to the record type of the transcription file. Between version 1.0.1 and version 1.1.1 there must have been a change in the layout of the file containing the data that allows the window layout to be saved and restored.

**Comment by EmJayFry** [comment]
Background
=========
WinFreeREG tries to be kind to users by maintaining a file that contains the appearance of the main editing screen whenever a file closed. The appearance of the editing window consists of the columns, their order, width and visibility. Separate layouts are kept for each of the 3 record types: Baptisms, Burials and Marriages. The data is kept in the file

AppData\local\WinFreeREG\FileDetailsState.dat

**Comment by EmJayFry** [comment]
Workaround
==========
A temporary workaround is available. Simply delete the affected file

AppData\local\WinFreeREG\FileDetailsState.dat

**Comment by EmJayFry** [comment]
Solution
=======
Problem arises due to the nature of the information being saved and restored: 3, variable-length arrays of bytes. If, between saving the state information and next restoring it the program changes and the changes affect the length of one or more of the arrays, then the system fails with results seen.

Easiest solution is to apply a predictable format to the file. To this end, the file  now prefixes each of the variable-length arrays with 

a) a string containing the record type, and
b) a 32-bit integer containing the number of byes in the array

The method used writes the string so that its length is included. The string can be thus be any length, but is restricted to either "BA" or "BU" or "MA". If any string is missing, then the restore is aborted and the defaults assumed. The inclusion of the length allows the program to read it and compare it with the size of the expected array. Again, a mismatch aborts the restore and the the defaults are assumed.

**Comment by SteveBiggs** [comment]
I am now evaluating version 1.1.3 which has this fix plus some other fixes & updates. Looks good so far, but I still need to do a bit more testing.

**Comment by edickens** [comment]
Steve.  Please re-test installation.  It seems to be this which has 
caused more problems than the operation.  E

**Comment by SteveBiggs** [comment]
I have uninstalled / reinstalled again and that gave no problems, however, I then opened an existing file and simply clicked on '+' to add a record and got an Unhandled exception with the following Details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at WinFreeReg.formFileWorkspace.BindingNavigatorAddNewItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5485 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
WinFreeReg
    Assembly Version: 1.1.3.0
    Win32 Version: 1.1.3
    CodeBase: file:///C:/Program%20Files%20(x86)/FreeUKGenealogy/WinFreeREG/WinFreeReg.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.5483 (Win7SP1GDR.050727-5400)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0

**Comment by EmJayFry** [comment]
On 02 Feb 2017 15:30, Stephen Biggs wrote:
> I have uninstalled / reinstalled again and that gave no problems, however, I
> then opened an existing file and simply clicked on '+' to add a record and got a
> Unhandled exception with the following Details:
>
> See the end of this message for details on invoking
> just-in-time (JIT) debugging instead of this dialog box.
>
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
> at WinFreeReg.formFileWorkspace.BindingNavigatorAddNewItem_Click(Object sender,
> EventArgs e)

Found this particular problem and fixed it. Due to a naming problem, could only 
add Baptism records. Burials and Marriages always crashed. Because of the nature 
of the problem, there is no work around, and a fresh release is required. Will 
hold off for a few hours while I check out a slightly different problem I came 
across whilst trying to add a record at the end of the list rather than at the top.

-- 
Regards,
Mike Fry (Jhb)
