### ISSUE TITLE
65984067 an Issue with the cookies banner (Eric)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#914]
Issue reported by **ericb** at 2017-02-02 16:54:27 UTC
Time: 2017-02-02T16:51:24+00:00
Session ID: c32512473bc5d973152cfb9cbaffe859
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [http://www.freereg.org.uk/cms/refinery/login](http://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Each time I log off - or get logged off because my session is inactive for a while, I then have to do the darned Cookies Banner Accept routine to start again.

This is a seriously retrograde step. Please revert to the user friendly version.

    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58936443f493fd075a864973/_old_)

**Comment by Captainkirkdawson** [comment]
Nothing has been changed since the middle of January. So there is nothing to revert to. The cookie process has not been changed in the past year.

**Comment by Sherlock21** [comment]
Well something, somewhere has changed. 
And I have not changed my Safari settings for many a month.
I just tried it out again now. I quit my FR Prod access, and closed the Safari screen that had accessed it.  Displaced a new Safari screen and looked a Preferences - Freereg.org.uk cookies is still there.
As it github.com because i am still writing thins ( on a different Safari window)
These Cookies will both ( along with all others ) get zapped when I log off the computer.

SO any ides please. Its only just started this last week.

**Comment by suffolkroots** [comment]
Please could we have implicit cookies acceptance.

**Comment by Captainkirkdawson** [comment]
See also #992  and #528

**Comment by richpomfret** [comment]
Closing this - we will move ahead with 992 and switch to implicit.
