### ISSUE TITLE
Problems with WinFreeREG v1.1.4

### ISSUE THREAD

**Issue by SteveBiggs** [FreeUKGen/FreeUKRegProductIssues#917]
1. Login to FR works, but once logged in, when I try to Fetch Counties or Fetch Places I get a failure message:  ... (500) Internal Server Error. 
Note that Fetch Register Types and Fetch Churches both work fine.
2. In a transcription file, after clicking 'Add record' then 'Delete record' then 'Add record again, a Unhandled exception occurred. After clicking 'Continue', the exception happens every time 'Add' is attempted.
3. When I tried to close the FreeREG Browser, I got the (500) Internal Server Error again. Click OK and it closes. This is not always repeatable though.

**Comment by EmJayFry** [comment]
Have been experiencing those sort of problems all day with both live and test3.
Overnight implementation of implicit cookies caused me to have to delete all cookies and start again before I could login. Logouts still not working. something is going wrong on the servers.

**Comment by EmJayFry** [comment]
Kirk made some changes on test3 for the uploading and replacing of files. Can't test because of other problems. Waiting for Kirk to wake up.

**Comment by SteveBiggs** [comment]
Kirk fixed the logout issue last night, but I'm still getting the (500) Internal Server Errors as before.

**Comment by Captainkirkdawson** [comment]
I believe Mike has to test and release update

**Comment by EmJayFry** [comment]
Confirm points 1 and 2.

Point 1 requires Kirk to investigate - there are crashes on test3 to be poured over. Tehn there's probably a change to be forced on WinFreeREG depending on what Kirk finds.

Point 2 need investigation of what happens on the PC

Point 3 was tied up with a problem logging out. Kirk changed test3 and a complementary change was made to WinFreeREG. Solved.

**Comment by Captainkirkdawson** [comment]
Please retry on test3

**Comment by EmJayFry** [comment]
Will do so in the morningSent from my Huawei Mobile-------- Original Message --------Subject: Re: [FreeUKGen/FreeUKRegProductIssues] Problems with WinFreeREG v1.1.4 (#917)From: Kirk Dawson To: FreeUKGen/FreeUKRegProductIssues CC: Mike ,Assign Please retry on test3

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeUKGen/FreeUKRegProductIssues","title":"FreeUKGen/FreeUKRegProductIssues","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Captainkirkdawson in #917: Please retry on test3"}],"action":{"name":"View Issue","url":"https://github.com/FreeUKGen/FreeUKRegProductIssues/issues/917#issuecomment-279084077"}}}

**Comment by EmJayFry** [comment]
Well, I won't be using the phone again for email! What a mess!

Tested and it's all working again. I need to put out an interim release, because the problem in WinFreeREG will be stopping further testing.

**Comment by EmJayFry** [comment]
Further problems. Uploading & Replacing files result in a 404 response.

Can Kirk please check test3 logs

**Comment by EmJayFry** [comment]
Upload and Replace problems sorted. Everything working again.

**Comment by Captainkirkdawson** [comment]
You need to be aware that the code changes required to support WinFreeREG have NOT been deployed to production. Until they are all attempts to use it in that environment will fail.
Have you confirmed that you are making your requests with the Administrator cookie present? Without it  WinFreeREG on production will fail erratically. The presence of the cookie can be tested on test3.

**Comment by EmJayFry** [comment]
Still not receiving the Administrator cookie.

**Comment by EmJayFry** [comment]
Still not receiving the Administrator cookie in WinFreeREG

**Comment by Captainkirkdawson** [comment]
You will never receive it as I do not believe that api's receive cookies in the manner that browser do.

I sent you the information on the content of the cookie 2 days ago with the suggestion that you add it to your post,

It is essential that haproxy sees that cookie in order to direct the request to the primary server.

**Comment by EmJayFry** [comment]
Not received anything describing the Administrator cookie

**Comment by Captainkirkdawson** [comment]
I sent it to you at 12:09 MST on the 13th.
Have forwarded you a copy of the message

**Comment by SteveBiggs** [comment]
Testing v1.1.5 on test3:

Minor point - when you click Fetch Places, it (understandably) takes a while but there's nothing to tell you it is actually fetching them. If you think it didn't work and click Fetch again, you get an unhandled exception error. Is there any way to show some sort of progress bar that it's fetching? Or make the Fetch button inactive until it's fetched?

The file Upload works fine, but when I try to Replace a file it consistently fails with a '(500) Internal Server Error'. Ali Hill, however says it works fine for her.

**Comment by SteveBiggs** [comment]
Further info: Replace works for files I uploaded earlier today, but when I try to upload an old file that's been on the test3 server a few months, I get the 500 error.

**Comment by Captainkirkdawson** [comment]
Issue exists because the  test3 physical files have not been synced with the production set for likely well over a year. The database however is a more recent clone of the production data base. Hence there is a disconnect between the two. 

You may confirm that there is no issue with replacing an old file by using one we know to be there

![ssx](https://cloud.githubusercontent.com/assets/2874694/23094861/c1ad4802-f5bd-11e6-8402-681a85e54456.JPG)

**Comment by Sherlock21** [comment]
Steve

If you email me a copy of the file you are trying to upload as a replace, I will have a look at it?

And tell me the userID if you would please.

Eric B

**Comment by SteveBiggs** [comment]
Replace works fine with the files in Kirk's list.

**Comment by richpomfret** [comment]
To deploy and further testing required.
