### ISSUE TITLE
66943820 Replace generated too large message incorrectly? (Joanne)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#921]
Issue reported by **ManCity** at 2017-02-13 19:30:20 UTC
Time: 2017-02-13T19:29:10+00:00
Session ID: 360356759f00f7f81db51a3d3cda6394
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: [http://www.freereg.org.uk/manage_resources/new](http://www.freereg.org.uk/manage_resources/new)
Reported Issue:
Message received: Too many batch entries. Have your coordinator contact system administration with this message, date and time
Document being replaced only has 1600 entries not that large    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58a2094cf493fd1161233f06/_old_)

**Comment by Captainkirkdawson** [comment]
Insufficient information. What file and for what userid. Could guess the latter but not the former.

**Comment by Sherlock21** [comment]
I raised a Problem Note yesterday, and I got the impression from the wording of the Window one gets after clicking on the Report a Problem Link at the foot of the page where the issue arose, that its important to do the report from the page on which the issue arises, because all the necessary information that the Management needs to address the issue, is automatically added to the user's note. So there is no need for the Reporter to spell out the issue details again in the text box presented.
As I suspected from my own case, this is not so.

Perhaps the screen notes which accompany a Report a Problem input form need to be a bit clearer w.r.t what the reporter need to spell out in the box.

**Comment by Captainkirkdawson** [comment]
The feedback does do what you suggest it should do. However you have to be on the page you wish to report an issue with not some other page.
In the case of this report the page reported to have an error is the coordinator action page for a county. There is nothing on the page that gives any information about the file in question.

**Comment by Captainkirkdawson** [comment]
Since there has been no response to the request for specific information and the messaging system for large files is under review I propose to close this item
