### ISSUE TITLE
71148355 File "not processed" has been processed (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#946]
Issue reported by **SBManager** at 2017-04-03 11:25:55 UTC
Time: 2017-04-03T10:31:31+00:00
Session ID: 7f9d2cadd724fbf7648374d26e019493
Problem Page URL: [/physical_files](/physical_files)
Previous Page URL: [https://www.freereg.org.uk/physical_files/select_action?](https://www.freereg.org.uk/physical_files/select_action?)
Reported Issue:
A file in the list of not processed (SSXCHNMA1) has in fact been processed and the batch is in the relevant Place/Church/Register (Sussex/Chichester/St Olave)
http://www13.freereg.org.uk/uploads/feedback/screenshot/58e23143f493fd077f4ffce8/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58e23143f493fd077f4ffce8/Capture.jpg)

**Comment by Captainkirkdawson** [comment]
The change of flag is the last activity on a process. It may be that the process did complte. It may be that it did not process all records and was caught in a crash.

**Comment by SteveBiggs** [comment]
Thanks Kirk. So would it be useful to have coordinators check the list of "not processed" files for their county and purge any such instances?

**Comment by Sherlock21** [comment]
i have a go at this year's entries when I have a moment to spare, and every time, the file concerned was actually been included in the Production set with a date stamp of the same date as that in the Not Processed. I just thought that the CC was quick off the mark and fixed whatever the issue and loaded a good one.
My intention was to work backwards and delete the old ones.

**Comment by Captainkirkdawson** [comment]
OK can see the issue but not why.

There are 2 entries for physical files for that userid and filename created 200 ms apart. The first has the completion of processing timestamp. The second does not.

So my hypothesis for the cause of these entries in the not processed list is incorrect. Now I need to find out why!

It appears they are resulting from a double click on a heavily loaded server.

**Comment by SteveBiggs** [comment]
I have noticed that the response time of carrying out actions in the membership area has been quite slow/timing out recently and other users have commented on this. Is the load higher than it used to be or is there another reason? Do we need more server power?

**Comment by Captainkirkdawson** [comment]
Have used my new development framework in the cloud to address this issue.
It appears that double clicking was responsible for at least one example. I have added a spinner on both the upload and replace functions to indicate that we are processing the request. This deactivates the button until the task is responded to by the server. A subsequent click will be a little later and should be caught by the server code. Could I please have a test of this code change on test3
@Sherlock21 @SteveBiggs

**Comment by Captainkirkdawson** [comment]
Have cleared the list of those for which this was the cause.

**Comment by Sherlock21** [comment]
I am out today, but will get to test it this evening.

E

**Comment by Sherlock21** [comment]
Attempted to do a REPLACE from in my Batches. at about 09:25 BST Thursday
Selected ericb.WRYSEDTSTBU3.csv from my Mac files.
hit REPLACE, and got the red msg: sorry something seems to have gone wrong.

after a short gap 5 mins or so - i tried again with same file. Still o go and gave up.

I have not tried just doing a load of a new file.

**Comment by Captainkirkdawson** [comment]
Sorry. My error. Tried to update a logical variable. Fixed. @Sherlock21  Please retry

**Comment by Sherlock21** [comment]
Right.

T3.
Using the same test file as before: WRYSEDTSTBU3.csv.

16:15 BST ish. did a Replace, from my Batches view. careful NOT to double click.
Replace worked fine. but I did not see anything of the whirly wheel you referred to inserting.
I got the usual system email message of file updated times 16:16. and OK.
NEXT I did another Reload ( 1619 BST ish.

Deliberately did a double click on the Go button.

Saw nothing different -

system email message received: times 16:26 says all 23 records were updated ( I only changed 2! ) So I am not sure why 23 were changed. Was it because this file was Char set UTF-8 where the first update had been typed in error and said WTF-8 by error on my part for rushing this morning]


Anyway: still no sign to me of the little spinning wheel. How do I initiate that if I am supposed to please?

**Comment by Captainkirkdawson** [comment]
The Upload Replace button turns into a spinning wheel on a click. You have to do nothing other than click the button.

Character set change would cause all records to be processed.

There was no double post at 16:19

Do you see a spinning wheel on a search?

I see spinning wheel

@SteveBiggs @edickens can you confirm sight/no sight of spinner on replace/upload of file?

**Comment by Sherlock21** [comment]
OK

I did NOT see a spinning wheel on the Replace button in my above tests.

I also did NOT see a spinning wheel on SEARCH button on 2 test I just now did.
But as there was  perhaps only me on T3, the searches were lightening fast.

**Comment by Sherlock21** [comment]
I just created a search that took some time to run - as all my others were done and over before i could scroll down far enough to see the search button again - 
This last time we have plenty time to find and see the spinning wheel if it was there - but NO sign of it.
So I am content I did not miss it. sorry!

**Comment by Sherlock21** [comment]
I even tried deliberately multiple hitting the Search button just now  17:07 BST.

and I do not see anything unusual or of the liking to a warning to keep my fingers orff.

**Comment by Captainkirkdawson** [comment]
Do you have javascript disabled in your browser?

**Comment by SteveBiggs** [comment]
The search button has always turned into a spinning wheel while searching
(at least for a long time). I just did a replace on T3 and yes, I see the
spinning wheel.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Sherlock21** [comment]
I am using Mac + Safari 9.1.3 ( its the latest that will run on Mavericks. - which in itself is not the latest Mac OS, but it is the latest that will run on my machine.

I DO have Java-script enabled.
and to Steve: I have never seen the spinning wheel on FR -

**Comment by Sherlock21** [comment]
If I use Opera browser,I do get a sort of spinning wheel. But using Opera is basically last resort and no good for everyday use as the Bookmarks are too hard to work out where they keep going to in this version unfortunately!

**Comment by Sherlock21** [comment]
By the way: if I try and revise a search by using the browser back button, instead of using the Fr button REVISE, then I gat the spinning GO wheel - so it will work sometimes. - just not in this  required case.

**Comment by Captainkirkdawson** [comment]
Sounds like its a safari/javascript problem
https://discussions.apple.com/thread/7628713?start=0&tstart=0
sounds very similar

**Comment by Captainkirkdawson** [comment]
I note that jelit has had another double click on a replace/upload.
Do we wait for the next scrum on April  24 before deploying or are we happy to deploy now?

**Comment by edickens** [comment]
Deploy now.  Otherwise just more problems to sort
      out.  E
    Eric J Dickens

    On 14/04/2017 15:58, Kirk Dawson wrote:
    
    
      I note that jelit has had another double click on a
        replace/upload.
        Do we wait for the next scrum on April 24 before deploying or
        are we happy to deploy now?

**Comment by Captainkirkdawson** [comment]
TY Will await comment by others to ensure we are all on same page

**Comment by SteveBiggs** [comment]
I agree - deploy now.

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Sherlock21** [comment]
Kirk's pointer to the Apple note about how to reset everything so that this particular Java script works,  is for the same problem as i have.
I followed the Apple methodology, but it did not work for me!

So I give up on that one! - life's too short.

Kirk: follow the crowd for views therefore please.

**Comment by Captainkirkdawson** [comment]
I did a final checkout and detected a bug it was possible to upload a file of the same name that had already been processed, That has been corrected, but need a breaking test before deployment.
@Sherlock21  @SteveBiggs @edickens

**Comment by SteveBiggs** [comment]
OK I'm​ out tonight playing a gig so will test it tomorrow.

**Comment by Sherlock21** [comment]
Whilst waiting for your suggestion,
I played with my file ericb/WRYSEDTSTBU3.csv  - an exist file in T3. This was at 17"20 BST on 16 \apr.
I did a Reload of it as its already in T3.The uploaded file had NO changes since last uploaded. yet it ggot processed as a new file according to the emial message.

"Eric,

The file submitted for processing has been completed. Please review the following report.

Started on the file WRYSEDTSTBU3.csv for ericb at 2017-04-16 17:20:01 +0100.
Updating the current batch for WRY, Sedbergh, St Andrew, Parish Register. 
23 records were processed of which 23 were updated/added and 0 had data errors.

Created 23 entries at an average time of 347ms per record at 2017-04-16 17:20:09 +0100. 
If there were errors in the header or with Place and Church names they will have to be corrected off line. Most other data errors can be corrected by using the on-line editing system or by correcting the file off line and then replacing the file on the system.

The FreeREG Team".

5 minutes later I repeated the RL. with the same unchanged file.
I got the on screen message : sent for processing - as I expected.
Then, at 17:30 BST i got the same exact email saying created 23 entries at an average time of 0ms.

Yet I had been of the opinion that SOMETHING had to be changed in the file that is reloaded else the attempt was rejected? Was this a wrong notion on my part? 
What did you expect that processing would do in this case?

**Comment by Captainkirkdawson** [comment]
On 16 April 2017 at 10:39, Sherlock21 <notifications@github.com> wrote:

> Whilst waiting for your suggestion,
>
*Do not understand. Our systems are doing their job, Your system is the
only one of which I am aware that does not handle JavaScript, my research
shows this to be a common issue for safari 9 and some apple hardware. I
have pointed you to the only solutions of which I am aware. *

*Since it really does not seem to impact your ability to function there is
little we can do.*

> I played with my file ericb/WRYSEDTSTBU3.csv - an exist file in T3. This
> was at 17"20 BST on 16 \apr.
> I did a Reload of it as its already in T3.The uploaded file had NO changes
> since last uploaded. yet it ggot processed as a new file according to the
> emial message.
>
> "Eric,
>
> The file submitted for processing has been completed. Please review the
> following report.
>
> Started on the file WRYSEDTSTBU3.csv for ericb at 2017-04-16 17:20:01
> +0100.
> Updating the current batch for WRY, Sedbergh, St Andrew, Parish Register.
> 23 records were processed of which 23 were updated/added and 0 had data
> errors.
>
> Created 23 entries at an average time of 347ms per record at 2017-04-16
> 17:20:09 +0100.
> If there were errors in the header or with Place and Church names they
> will have to be corrected off line. Most other data errors can be corrected
> by using the on-line editing system or by correcting the file off line and
> then replacing the file on the system.
>
> The FreeREG Team".
>
> 5 minutes later I repeated the RL. with the same unchanged file.
> I got the on screen message : sent for processing - as I expected.
> Then, at 17:30 BST i got the same exact email saying created 23 entries at
> an average time of 0ms.
>
> Yet I had been of the opinion that SOMETHING had to be changed in the file
> that is reloaded else the attempt was rejected? Was this a wrong notion on
> my part?
>

*Something may not be as I would have expected. Clearly it processed 23
records which I would have expected for an unchanged file. The average time
tells me that the records were likely unchanged so the critical message  to
say*


*23 records were processed of which 0 were updated/added and 0 had data
errors.*

*Unfortunately you did not send that line*

**Comment by Captainkirkdawson** [comment]
Further to my last message I extracted the actual message you received on
your second processing.

Started on the file WRYSEDTSTBU3.csv for ericb at 2017-04-16 17:30:10
+0100. <p>
Updating the current batch for WRY, Sedbergh, St Andrew, Parish Register.
<br>
23 records were processed of which 0 were updated/added and 0 had data
errors. <p>
Created  23 entries at an average time of 0ms per record at 2017-04-16
17:30:10 +0100. <br>


It has exactly what I would have expected from processing an unchanged file

23 records were processed of which* 0 were updated/added *and 0 had data
errors.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
I have done some more upload / replace tests in T3  and all seemed to be
working correctly until I tried to replace SSXEGDMA which is in my own list
of batches but I got this:

[image: Inline images 1]

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Sherlock21** [comment]
I tried the iPad version as well - the Safari one in the bundle. that is current software.

and I dont get the whirly wheel their either! so no one else on iPads will either if they use that.

BUT as you say: I agree with your - move on - these is nothing I can do to get this to work on this manner - although if I ever use the Browser Back arrow in stead of the in-app navigation, it give the required whirly wheel then. - So Baffling. but lets move on.

Eric B

**Comment by Sherlock21** [comment]
SO
No harm done then, is there. - except a waste of Processor time. 

OK. What did you actually have in mind for us to try and test out - both to make it work, and to try to make it fail?

EM

**Comment by Captainkirkdawson** [comment]
On 17 April 2017 at 08:29, Sherlock21 <notifications@github.com> wrote:

> SO
> No harm done then, is there. - except a waste of Processor time.
>

*There is no real waste of processor time if we see it has not changed then
we do nothing  with the record*

>
> OK. What did you actually have in mind for us to try and test out - both
> to make it work, and to try to make it fail?
>


*Does replace of one of your files work when same name; fail when name
different;; does upload of file of same name as exiting file fail; *

*Can you upload and replace for a userid as a coordinator. Does it fail
when it should*

>
> EM
>

**Comment by Sherlock21** [comment]
SO

here’s what i have done:

1) created a new file and uploaded it	WRYSEDTST4.csv. with 23 records in it.
result: correct message and actions.
2) revised 1 record intis file and RL
result: file processed. 
one record shown as changed - OK
but email text ALSO says:
"Created 23 entries at an average time of 43ms per record at 2017-04-18 08:33:49 +0100. “	why created 23 records when 22 are there and unchanged already?

3) tried to upload same existing file as a new file.
Result: first msg says: "sent for Processing” - should it not have got rejected at this stage as this file name already exists? (ericb.WRYSEDTST4.csv)

WRONG RESPONSE also. it seems to have gotten processed:

"Eric,
The file submitted for processing has been completed. Please review the following report.

Started on the file WRYSEDTSTBU4.csv for ericb at 2017-04-18 08:43:49 +0100.
Updating the current batch for WRY, Sedbergh, St Andrew, Parish Register. 
23 records were processed of which 0 were updated/added and 0 had data errors.

Created 23 entries at an average time of 0ms per record at 2017-04-18 08:43:49 +0100. 

If there were errors in the header or with Place and Church names they will have to be corrected off line. Most other data errors can be corrected by using the on-line editing system or by correcting the file off line and then replacing the file on the system.

The FreeREG Team"

It should have got Rejected with msg: this file already exists or similar.
 I will repeat this uplad again, with all but one record removed to see what happens thins time.
Result:  CORRECT result this time. the onscreen msg said: You already have a processed file of that name. You cannot upload a file with the same name etc.

SO how was it accepted the first time ( 08:35 ish) and rejected the second time 08 47ish?


Changing the filename of my test file now, to leave the evidence there for you.

4) upload a file on behalf of a different ID. alsibk.WRYSEDTST4,csv with 1 record in it.

file appeared in the correct place & UID. 
but I did not get the email - should I have done. I was DM. and user ID was alsibk - the SC/CC as it happens.

5) Will repeat  4 but as a RL with extra data in it. at 09:05.
I started this off from view the records for SEDBERGH, and find the file I needed. then view content where I can pick: Replace Batch.
Result: started off correctly & sent for processing.

No progress email nor onscreen progress. BUT looking at the Placename in the APP, yes tis been updated correctly.

A Search records worked correctly with UID and file names correct. 



6) testing in my ID: trying to replace with wrong filename

Correct response on trying to upload. all im my UID.

7) Testing DM uploading a Replacement file but in the UID of alsibk.

located the alsibk.WRYSEDTST4.csv file from in the Placename view.

selected Relpace batch.

picked file WRYSEDTST4.csv but left the uid shown as ericb	[ which I should have changed to alsib did deliberately did not change it]

(time of this test was about 09:19 ish)

RESULT the reload got Accepted = WRONG

Now of course I can’t tell ( in the App)  which batch was uploaded at which time as they are all today.

I can run this again if you are confused and can’t sort out which is which either!

end

eb

**Comment by Captainkirkdawson** [comment]
That is EXCELLENT testing just what I needed. Will look at later. May be a
delay as its golf day

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
What !!
A day off to play GOLF!!!!!

and here i gave up gardening to rerun my latest test (from this mornings report )” because I did not do it very well..

now repeating the bit where i/ upload a fist fief v=for another UID, then try and Reload a change to that one ( for the same other ID)

Dont worry…. I will stick at it until I get my logic  right.

TY.

EB

**Comment by Sherlock21** [comment]
K

I have completely re done the testing of "uploading for another person". ( item 6 in the previous sumary results set)
And it seems OK
BUT as i dont get the system emails, I have asked Ali Hill to forward them to me just to check.
and she is not replying right now.

I will have to wait for tomorrow now, as I am off to watch something on TV.

Will sign this off when i get the replay from Ali.

ERic

**Comment by Sherlock21** [comment]
Kirk

Finished off this set of testing by repeating a RL for someone else.

It works correctly.
the onscreen messade is right.

the email that its been completed goes to the CS/CC - as they all do.
BUT in the caase of another party doing the upload, they are left in the dark after the first on-screen message that the upload has been sent for prtrocessing.

Like DM uploading this test in the name of the SC, the DM needs to get the same email when the processing is completed.
Its not life threatening  if you dont do it, because the frequency of it happening for real must be slim. But if its easy for you to generate a copy of the one to the CS, then that woudl be the logical conclusion.

OTHERWISE.	Job completed.

eb

**Comment by Captainkirkdawson** [comment]
Thank you for that excellent work.

So it appears that I have a problem with 3 and 7 and Steve also reported something similar with 7 so will not deploy yet.

WRT to your getting emails as DM there is no easy way of achieving your wish. The SC and CC get their emails NOT because they initiated an action (even if they did). They get it because they are responsible for either the Syndicate or County in which a file was processed.

**Comment by Sherlock21** [comment]
Well, given that I don't do that sort up "upload for others" as a normal part of my activities, its no problem really. So skip that suggestion please.
As to the 3 & 7 issues, let me know when you have those sorted and I will run through the test again now I am sorted with a method!

**Comment by Captainkirkdawson** [comment]
Will do

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1
