### ISSUE TITLE
71859324 File not processed not in list (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#950]
Issue reported by **alsibk** at 2017-04-11 16:55:24 UTC
Time: 2017-04-11T16:52:32+00:00
Session ID: d1db9b72a45a8f1ab0a4f4778c01e4da
Problem Page URL: [/manage_counties/display_files_not_processed](/manage_counties/display_files_not_processed)
Previous Page URL: [https://www.freereg.org.uk/manage_counties/select_action?county=WRY](https://www.freereg.org.uk/manage_counties/select_action?county=WRY)
Reported Issue:
WRYHAWMA1.CSV for DerbyKid at 2017-04-11 16:29:35 +0100. 

was not processed but is not in my Files not processed list.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58ed0a7cf493fd27b5460d10/_old_)

**Comment by Captainkirkdawson** [comment]
Can find no such file being loaded at that time
The last file of that name for that person was 13 Jan 2017

**Comment by suffolkroots** [comment]
We are sorry but the file submitted was not processed. The processing log follows and should contain a reason.
Started on the file WRYHAWMA1.CSV for DerbyKid at 2017-04-11 16:29:35 +0100.

Processing was terminated because of a fatal header error.

Invalid file type in first line of header.
I did not know enough about your data format to extract transcriber information at header line 2.
I did not know enough about your data format to extract Credit Information at header line 3.

If the reasons are header errors or Place or Church names you must correct the original file and upload the corrected version into the system

**Comment by Captainkirkdawson** [comment]
I would like to thank you for the additional information that places the first message in context.
My only question why you have not followed the advise to correct the file and reprocess the file

**Comment by Captainkirkdawson** [comment]
The physical file information is deleted from the system if there is  a header processing failure because we are unable to create a meaningful batch document. This situation normally occurs on an upload. If we retained the physical file information  then the system would see an existing file and stop a subsequent upload and insist on a replace. Unfortunately since the file was not processed there is nothing in the tables to replace. Hence we are in a locked out situation. By deleting the physical file information we avoid the lock out. 
This is the first time that I am aware of a replace failing because of header information. However the previously processed file is there so a replacement with a correctly formatted file is still possible.
At this point trying to retain an entry in the physical file collection for what is an unprocessed and unprocessable would likely cause more trouble as the only action that could be taken would be to delete the file. Any attempt to reprocess would fail again and there is nothing to perform on-line updates to.

**Comment by Captainkirkdawson** [comment]
At scrum review propose to recommend closure

**Comment by suffolkroots** [comment]
Kirk said
"I would like to thank you for the additional information that places the first message in context.
My only question why you have not followed the advise to correct the file and reprocess the file"

To discover and solve the problem I have to get the file from transcriber or look in the not processed list. 
Neither were available.

It has now been resolved through the F1 route of passing files backward and forward by email.

**Comment by Captainkirkdawson** [comment]
We (Ericb) can always retrieve the last processed file from the attic no need to go to F1. It would not have been the one that had header problems but neither would the one on F1.

**Comment by suffolkroots** [comment]
Kirk this file had not been processed. I would expect to see it in the files not processed list.
If it won't be there why do we have the action?
I did, of course, not retrieve this file from F1. This reference was re the necessity  to proceed back and forth by email rather than see/solve problem online.

**Comment by Captainkirkdawson** [comment]
But Ali the file had been processed and found to have header errors. You told me you received an email to that effect. 
The not processed action informs you that a file has not been processed. It is there as a safety valve. Since files are uploaded and placed into queues. There needs to be a way for to see if for some unknown reason the file had slipped through the cracks. It should be an extremely rare occurrence but it could and has happened. ie it is a list of files that the processor has not attempted to process AND that are not waiting to be processed.  Should always be zero in a perfect world.

**Comment by suffolkroots** [comment]
Kirk the email which I provided for you was **File not processed**.
We are sorry but the file submitted was not processed. The processing log follows and should contain a reason.
Started on the file WRYHAWMA1.CSV for DerbyKid at 2017-04-11 16:29:35 +0100.
That's why I looked for it in the not processed list

**Comment by Sherlock21** [comment]
Surely the actions should have been:
The Uploaded still has the file.
SO correct it as indicated.
[else if the uploaded is not the Transcriber, pass back to the Transcriber to correct]
Then upload again.

If there are the errors which the system message indicates, then that leaves the file in a state where it cannot be corrected on line - the file has not got far enough down the process to facilitate that course of remedy.

**Comment by Captainkirkdawson** [comment]
Have changed the error message.
