### ISSUE TITLE
72009020 Access to physical files by county (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#951]
Issue reported by **alsibk** at 2017-04-13 10:30:20 UTC
Time: 2017-04-13T10:22:37+00:00
Session ID: 705a6090889f1445cb920870a7bfdf06
Problem Page URL: [/physical_files](/physical_files)
Previous Page URL: [https://www.freereg.org.uk/physical_files/58ef412af493fd27b5463e43](https://www.freereg.org.uk/physical_files/58ef412af493fd27b5463e43)
Reported Issue:
Manage syndicate/List files waiting to be processed (because they are not there in Manage county)  breadcrumb back to physical files takes me to all physical files

http://www13.freereg.org.uk/uploads/feedback/screenshot/58ef533cf493fd27b5463f89/Physical_files.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58ef533cf493fd27b5463f89/Physical_files.jpg)

**Comment by richpomfret** [comment]
To investigate previous fix and see what's happening.

**Comment by Captainkirkdawson** [comment]
It is not possible to list files awaiting processing nor unprocessed files for a county. 

Why? The file has not yet been processed hence we do not know what counties it may contain.

We can list for a syndicate because we known what users are in a syndicate and we know  what files they have uploaded and are waiting or unprocessed.

It was a mistake to advertise a capability by county.

The action will be removed.
