### ISSUE TITLE
Enhance corrections process (was 73652661 Notepad view corrections (Ali))

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#954]
Issue reported by **alsibk** at 2017-05-02 11:04:21 UTC
Time: 2017-05-02T10:58:38+00:00
Session ID: bc7ecae77ae405ddc19ecd4f31852d57
Problem Page URL: [/manage_counties/select_action](/manage_counties/select_action)
Previous Page URL: []()
Reported Issue:
Please would it be possible to have an online editable notepad view of files as is available in FreeBMD. The current correction regime is very cumbersome and time consuming if there is more than one amendment needed.    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/590867b5f493fd3e88d84eac/_old_)

**Comment by Captainkirkdawson** [comment]
Afraid not. FreeeBMD is a file management system like FR1 was; it  is not an on-line system FreeREG is.
Perhaps you could explain in what manner the on-line system is cumbersome and we can look at improvements.

**Comment by suffolkroots** [comment]
I recently came upon an historic file of 7000+ records which had 19 consecutive date typos.
In order to correct these online, for each of the 19 records this is the current process--

Browse to first record needing amendment
Select ED
Edit
SUBMIT
Arrive at 
![image](https://cloud.githubusercontent.com/assets/10379655/25799005/46373e06-33db-11e7-8cd4-71044977838f.png)



Breadcrumb back to list of records
Browse to next record needing amendment
Select ED
Edit
SUBMIT
Arrive at -----------

etc etc etc for 19 separate actions.

Ordinarily I could of course download, correct in notepad and replace. However, since you have put a limit on the size of replacement files this is not always possible.
I now have to go cap in hand to DM, send him the amended file and request the replacement.

It should surely be possible, in the event of more than one correction being needed in a particular file, that the corrections could all be undertaken before the corrected file is finally submitted.

In BMD, all file errors can be corrected online in notepad view-----
![image](https://cloud.githubusercontent.com/assets/10379655/25798967/1e84c8a6-33db-11e7-9729-15113a01ac1d.png)


Having clicked View/Edit, we are presented with the notepad view of file which we can then edit online:
![image](https://cloud.githubusercontent.com/assets/10379655/25798930/f9a37c8a-33da-11e7-9ebf-23bfd6952586.png)

**Comment by Sherlock21** [comment]
The process of editing online is fine if there is only one change in that file.

But if there are more than one record to be edited - and there can easily be several 10's in a 8000 record file, it would be far more convenient for the Users, if all the changed can be done at one go, and then fired off for processing.

SO could you devise something on the following lines perhaps please?
After doing the necessary correction to the first record concerned, BEFORE hitting 
could there be a "Do you wish to edit anything else in this file--YES/NO"

YES would take you back to where you were,  so one could do the next record [ and loop round as many times as needed]
NO would Submit the lot in one go.

**Comment by edickens** [comment]
I've not checked it out, but why not just use the list errors report and correct them?  No need to browse the file.  Or are these records that don't show as Errors but need correcting, for example when a researcher reports a problem?

**Comment by suffolkroots** [comment]
Eric these were date typos and would not be shown as errors. I found them whilst checking decadels

**Comment by PatReynolds** [comment]
Suggest change of approach: In cases with big files and lots of editing to do: download, make the changes, break down into smaller files of max. 2000 entries (e.g. into register book groups), and upload each in turn.

**Comment by suffolkroots** [comment]
Thankyou for your suggestion---I will allow those poor old files to rest in peace.

**Comment by Sherlock21** [comment]
But that suggestion by Pat is no good for the same reasons as Reload it. - it would involve DM having to DELETE the original file, or the CC's version of delete which is converted into an overnight processing job and both uses more processing that does the Reload that we are trying to curb. Meanwhile the double records would exist until the first larger file is completely removed.
The only easy solution is to do what I suggested  5 entries above.

**Comment by Sherlock21** [comment]
Is it not a bit unreasonable to close an item without a proper resolution?

**Comment by edickens** [comment]
Hi EricB,
We did discuss this with Kirk before making this suggestion.  He felt that the extra processing when having to delete a lot of records while splitting up the batch was worth it as a one off need.
As for your suggested solution, is this not just the Breadcrumb taking you back to where you were while browsing?
E

**Comment by Sherlock21** [comment]
Fine, Eric D

But if the thoughts in your above reply had been considered before Pat made her statement, then should they not have been printed in her decision so we were all on the same playing field?
