### ISSUE TITLE
75708819 General county information (Ali)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#960]
Issue reported by **alsibk** at 2017-05-26 06:13:39 UTC
Time: 2017-05-26T06:09:57+00:00
Session ID: 5fa189af190a07b7d8b4a007bf97ff94
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
Please would it be possible for CCs to edit their county information as they used to be able to do in ppp. Thankyou.
http://www13.freereg.org.uk/uploads/feedback/screenshot/5927c793f493fd2c503d9a93/County_info.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/5927c793f493fd2c503d9a93/County_info.jpg)

**Comment by SteveBiggs** [comment]
Requested changes should be sent to Eric for review who will pass on to Alison. Steve to reply to Ali.

**Comment by Sherlock21** [comment]
As the modern website is nothing like the old F1, I am at a loss to know what exactly Ali has in mind here.

So perhaps a detailed list of exactly what is being sought?

What functions which are there but operated by myself and other Managers as asked to be handed over to the CCs?

What new functions which are not there at present, but are being requested now?

**Comment by edickens** [comment]
Hi EricB,

There were information lines at the top of the FR1 PPP which the CC could edit in html.
![capture](https://user-images.githubusercontent.com/8876165/27884724-2dd9beb8-61cd-11e7-956f-6df921de93d4.JPG)

Some of this has been entered in FR and is set up in the Refinery and is inserted at the top of the "Transcriptions" County pages.

Ali is asking to be able to edit this and so display information to researchers.  But at present we do not have coding for this, however the Refinery can be edited by management.  Changes are not made very often which is why we are suggesting that it is done by request for now.

ED

**Comment by PatReynolds** [comment]
Decision that changes should be made by Eric, and Alison informed was because of the complex nature of the code in Refinery - giving CCs access to edit one area would give global access.

**Comment by Sherlock21** [comment]
Thank you Eric D for this input.

Pat: given Eric D's inside info, what then did you have in mind by passing this one to me to sort out please? since it seems none of the above is now Caounty - Specific, relevant given the way that FR has been compiled. the one ref to Della Patch is now to be found grin each input batch ( if they have had the correct header info.)

**Comment by Sherlock21** [comment]
Pat: which "Eric" please?  [B or D]
And is this a statement of your conclusion for forward going? or a statement of how it was up to now please?

**Comment by edickens** [comment]
Eric D.  I can edit the Refinery, but Alison has asked to be involved as it affect accessibility.

ED

**Comment by SteveBiggs** [comment]
Reply sent to Ali explaining. Issue can be closed.
