### ISSUE TITLE
75827240 Announcements made by email through the FreeREG server are not getting to all necessary recipients (Staffordshire)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#964]
Issue reported by **STSCoord** at 2017-05-27 15:07:20 UTC
Time: 2017-05-27T15:06:54+00:00
Session ID: 673ae82f324a17597014090fe40096d7
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: []()
Reported Issue:
The recent email that Eric Dickens sent regarding the non-availability of the Image Server was not received by some people. My CC persona (STSCoord) being one of them. My transcriber persona (MikeNL) DID receive this message. Eric also thought that it might be based on a duplicate name in the UserId's but this was not the case. Messages should be sent to ALL UserId's that conform to the requirements of the "circulation list".
    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/59299628f493fd2c503e8481/_old_)

**Comment by PatReynolds** [comment]
Possibly an intermittent block due to sending via Sendgrid - if you can let me have the email address which did not reach Mike, I can check.

**Comment by ghost** [comment]
Info from contact as requested:

The email was the ones with subject matter "Access to the Image Server. Reference 75714751" and, more specifically, the one timed 1838 on 26 May 2017.

It DID NOT get through to STSCoord but DID get through to MikeNL.

**Comment by PatReynolds** [comment]
What was the email address that was not reached?

**Comment by ghost** [comment]
My apologies. It is freereg2.sts.coordinator@gmail.com

**Comment by PatReynolds** [comment]
Sorry about that, as soon as I saw what you'ld typed I realised this info was on the public side of the website (duh!).  
Righto, doesn't seem to have got as far as sendgrid - this screenshot shows the earliest record of sending to this address that I have - and these and all later ones are getting through without any issue.  Absolutely nothing on the 26th - so it seems the issue is not with sendgrid/spam, but with the message system, or between the system and sendgrid
![sendgrid capture](https://cloud.githubusercontent.com/assets/6338822/26675676/c2131394-46bc-11e7-9a51-619b0226dd2e.JPG)

**Comment by Captainkirkdawson** [comment]
This is 9 months old. There is no way to go that far back into history to find an issue. 
There have been no recent reports so I suggest this be closed.
