### ISSUE TITLE
Create new dev test environment

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeUKRegProductIssues#973]

**Comment by Captainkirkdawson** [comment]
Use test2.freereg.org.uk to connect to a development setup and mongodb instance on vervet. This will leave test3 as a production test site on the sharded servers

**Comment by Captainkirkdawson** [comment]
test2.freereg.org.uk is set up to connect to the freereg2/development host on apache. 
There is a local instance of mongodb running on vervet to support  this as well as test2.freecen.org.uk. 
It is a rails development implemetation hence all css is compiled from the  content of the asssets folder rather than the public folder.
The rails log is development.log in the log folder of the application NOT in passenger.log
test3.freereg.org.uk is set up to connect to the sharded mongod system with a test database.
Code should be tested first on test2 and if OK then tested on test3.
