### ISSUE TITLE
Try to specify where 0 dates occur

### ISSUE THREAD

**Issue by suffolkroots** [FreeUKGen/FreeUKRegProductIssues#987]
Having spent valuable time trawling through a 12000+ file to find one elusive bad or missing year, I request that we be provided with clues as to the whereabouts of these dates. Line numbers would suffice. Thankyou

**Comment by Sherlock21** [comment]
Seems to me that if we are to show Year range of each batch, then its either got to be correct, or don't do it al all.

The present method of having sound date ranges on most Batches, but a "from" year of 0 on quite a lot, and all with different reasons for the 0, brings distrust upon the system in my view.

Richard: Can we not agree a common logic to the solution please, and then fix it?

**Comment by edickens** [comment]
The problem is know which 0 years are fixable and which are just because the year is unreadable and has UCF.

**Comment by Sherlock21** [comment]
Indeed - which is why my advice has been to add a short note saying the record has a missing year ( or illegible year) and the date year is estimated from record's position in the Register.

**Comment by SteveBiggs** [comment]
There are a few separate issues here -
1. Should we allow transcribers to use UCF on illegible years and/or leave them blank? (There is another story for this). Occasionally,  it's not possible to even estimate the year due to a badly jumbled original register or where entries are put in out of sequence.
2. Where there is a missing year, should  it be returned as '0' or ignored in the date range?
3. Can/should we change the batch details reporting system to flag up missing years as a warning, so they are easily  found and amended if relevant?

Personally, I would like UCF to be supported on the year in the search engine so "yes" to 1.
I would like missing years to be ignored in reported batch date ranges.
3. would be useful, if possible.

**Comment by Sherlock21** [comment]
1) if there is no 4 digit year in the record, then it will never come out in a search. So it might as well NOT be in the batch at all.

2) NO it should not be reported as 0 because that's not logical in my book. It shows to the users that we have dodgy data too in my view. 
It could be ignored in computing the data range of a file, so that the rest would be meaningful - but then, as answer in (1), that record might as well not be in the collection.

3) yes. But you need to tell the inputter what to use in the transcription in these cases. An estimate PLUS a comment is the most sound option in my view as a Transcriber - also supported by some CC's that I have discussed it with.

**Comment by SteveBiggs** [comment]
I agree with your comments, Eric except that in 1. the record would be found by a search without dates, but that's probably rarely how researchers do their searches.

**Comment by Captainkirkdawson** [comment]
25% of all searches have no date range

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by SteveBiggs** [comment]
Further comment from EricB:

"But isn’t the main point that if we speak about UCF, then if we are only really accepting the use of * in a data, rather than the whole collection of UCF as applies across the rest of the Transcription.

reason: so as to make the searching code easier to write effectively?

you cant leave out YEAR from your spec.  if you are searching at County level
The year is the key bit. if no year, then as I just discovered, I get NIL results in a County only, and in County + Place, there are > 250 records so you get none there either.

Its therefore essential to have year there properly - or as properly as the Trancriber can, backed up with a explanatory note in the Notes."

**Comment by SteveBiggs** [comment]
If you search for a specific name with no dates in a County, it will return results. Try John HIGGINS, Baptisms, Sussex and you should get 14 results. These all include correct dates, but if there was one missing, it would also come up.

**Comment by Captainkirkdawson** [comment]
IMHO the date range data that flags a zero IS an indicator of an issue with the data that needs investigation. It has led to the correction of many  date errors.
Perhaps we do NOT display the actual date range in the Transcription information and leave ONLY the Official Date Range for the register. This of course means that to be helpful the coordinator must fill in that information for the register.

**Comment by SteveBiggs** [comment]
I agree that flagging the 0 to the transcriber in their batches is useful for catching issues. In my experience the most common reason for a 0 date is that a blank line has been left on the end of the file, so I just delete it.

However, I would not want to lose the actual date range from Transcriptions as seen by researchers since this is extremely useful to them telling them what's been transcribed. Is it not possible to omit the missing years from the date range and report the first and last valid one here?

**Comment by Sherlock21** [comment]
Steve re your above post: if you search for Fisher in WRY, with no Place, you get blank for the answer. Even iff you put Baptisms in one gets Blank

Adding Place name but still no year range, gets > 250 so that does not work as I said before.

**Comment by Sherlock21** [comment]
Kirks point about  not displaying the date range to public would be a retrograde step in my view.

It enables the researcher to not waste their time searching for 1500's records if the start year of our records is 1659.

**Comment by SteveBiggs** [comment]
Strange. I don't need to put in a place - just the county, but it's true that Fisher alone returns too many results, but if you narrow down to say Robert Fisher, you get 48 results. It's true that common surnames in large counties will be a problem. I agree that the best thing would be to add at least a year to the entry (with a comment) whenever possible and I always have advised my transcribers to do that, but occasionally it's not possible to estimate with any reasonable accuracy.

**Comment by Captainkirkdawson** [comment]
I did not propose to remove the max and min dates. what I did was say we display only the dates that are in the register collection. These are the dates that the register is supposed to hold. Unfortunately these are rarely used which is why we included the actual dates warts and all.

**Comment by Captainkirkdawson** [comment]
Lets remind ourselves of the original request for this story which was  to have the system indicate the record that generates a zero entry to it can be corrected.

**Comment by Captainkirkdawson** [comment]
Have added an action that lists the zero entries, See  test2 for evaluation 
https://test2.freereg.org.uk/

**Comment by suffolkroots** [comment]
Thanks Kirk, I see  zero entries are now listed at end of file.

But there is now no reported indication that this file has zero dates  eg in date span.

So how will we know?

Also, 2 dates following a * entry have been moved--is this intended?

No email received about this replacement file.

![missing dates](https://user-images.githubusercontent.com/10379655/29448147-28a8b948-83ed-11e7-86e0-56235dcdbe13.jpg)

**Comment by SteveBiggs** [comment]
Which file are you looking at that does not have zero dates in the date span? Kirk's example  (NFKACLBU) does show '0' in the batch information.

**Comment by suffolkroots** [comment]
WRYBUWBA97.CSV was my test.

NFK is outside my viewing range.

**Comment by SteveBiggs** [comment]
Yes that is strange because the other file in that register (WRYBUWBA) does show '0' for the missing date. One for Kirk to look at.

**Comment by suffolkroots** [comment]
Kirk I apologise I replaced this file now the zeros are not at the end of the file.

Whilst accepting that if they are all together they are easier to find, they still have to be searched for.
![image](https://user-images.githubusercontent.com/10379655/29466400-ac74cb62-8434-11e7-9146-69d9d06b471b.png)

Still not showing zero start.

Issue with 2 dates after * seems to have vanished.

**Comment by suffolkroots** [comment]
Apologies again Kirk, listing of records with zero dates in very useful. as long as the file is shown as zero date in info email and in Show Header. WRYBUWBU88 (alsibk) this doesn't seem to be working.

**Comment by Sherlock21** [comment]
Steve, Eric D & Kirk:

Please spell out what date structure you are currently permitting in the current Test2 server testing of dates.

Is it any use of UTC anywhere in the date?
Is it UTC in any part of the date except the year number, which must be 4 digits?
or is UTC banned in dates?
or is it any use of UTC plus estimated year component + ?
or is it one single * for the whole date missing?
Without this agreement and dissemination of the rules to the testers, its a bit pointless because each will be thinking different rules apply

NOW that kirk has provided the file tab for List Records that generate the 0 year in the file name, its very east to find and correct the ones which are errors. But the original from 0 to yyyy needs to stay because its easily spotted at church register list level then follow up using the new tab List Records that generate  Zero years

**Comment by Sherlock21** [comment]
See also 841. these 2 can't be dealt with in isolation in my opinion

**Comment by suffolkroots** [comment]
I'm not sure that UCF has any place in year display. 
Years should be YYYY.  In cases of uncertainty should be YYYY? with an explanatory note.
The reported year span of files with zero date should be 0-YYYY, or the zero dates should be flagged as errors.

**Comment by richpomfret** [comment]
To be pushed to production.

**Comment by SteveBiggs** [comment]
This has not been pushed to production yet. In test2, the listing of zero years works, but in the register view of files, the date range for files does not show the zero years so it's very difficult to find files that have zero years.

**Comment by edickens** [comment]
The date range for files (batches) is not shown because in #807 all entries likely to cause 0 dates were omitted from the year range calculation.  This was done so as not to create confusion for researchers.

**Comment by SteveBiggs** [comment]
Yes, we don't want the zero dates in the researcher view of transcriptions, but they are very useful for the coordinator. Can the two be separated?

**Comment by Captainkirkdawson** [comment]
That takes you back full circle to the August 14 comments in this thread!

**Comment by SteveBiggs** [comment]
Yes, this is what I've wanted all through - coords to see zero dates in register view of batches to quickly identify problems, but researchers only see the valid minimum date transcribed when they view Transcriptions, but I don't know if that separation is possible/easy ....

**Comment by Captainkirkdawson** [comment]
As I said in August. 
Fields exist for what the max and min dates of a register should be as well as the actual fields. Unfortunately few people have entered that information on what a register range should be as it is a human entered field.  Thats why the actual fields are displayed to the researcher instead. Lack of information is also why we were never able to implement date checking! 
Since zero is the actual field that is what you get.

**Comment by SteveBiggs** [comment]
It could be confusing to a researcher if we list the max and min dates of the full register, because they may assume that is what we have actually transcribed. I think they want to know what is available to view on our site at any given time.

**Comment by Captainkirkdawson** [comment]
Nothing further to say other than what I said on August 16
Lets remind ourselves of the original request for this story which was to have the system indicate the record that generates a zero entry to it can be corrected. 
On August 17 I said
Have added an action that lists the zero entries, See test2 for evaluation
https://test2.freereg.org.uk/
I do not know if that was ever propagated to production.
Much of what has been said has no bearing on that request.

**Comment by Sherlock21** [comment]
I was asking myself exactly the same question as Steve above.

**Comment by suffolkroots** [comment]
>>Kirk said "Fields exist for what the max and min dates of a register should be"

The only mention of this in CCs' Help is----

"consider adding some notes about the Register: its source, its status (finished, in progress, needing assistance), the official start and end date of the register, even a comment on the copyright."

This can hardly be deemed an instruction and mandatory.

The vast majority of data are not complete sets, indeed I have no idea what, in many cases,  the possible complete spread would be, and have no intention of wasting my time trying to find out. What researchers want to know is what we have, and that is recorded clearly.

**Comment by Sherlock21** [comment]
I am inclined to agree with Ali.
Perhaps  there are 2 different requirements at play here , and they are getting mixed up since they both use the same names, ( date years From and To) when the issue would be helped by more distinct titles? One ( on the church Information page) is  and overview  and the other ( our actual transcriptions) is what is available to our Researches to use. These will not often be the same.

The other point I wish to make may well be the same was Kirk's point about: is the latest "fix" loaded into Production, or is it just there in T2? - [ and T2 itself is not a satisfactory test region, as it is not available to me to access due to it not being compatible with Mac OSX on iMac's]

**Comment by SteveBiggs** [comment]
Vino has implemented the zero years report in test3. Go to: *Manage
Syndicate >> Review Batches by Filename*

Steve

**Comment by suffolkroots** [comment]
Zero years report very welcome thankyou---as long as it's consistent.
These 2 files have no 0 years, so why are they listed so?
![image](https://user-images.githubusercontent.com/10379655/31576329-856e91fe-

**Comment by edickens** [comment]
Checking report.
This is from STS Syndicate BKMHANBA (MikeNL) in Parish Register of St James the Great in Hanslope of Buckinghamshire list of entries with 0 years.
![image](https://user-images.githubusercontent.com/8876165/31576379-aeecf736-b0f1-11e7-88dd-5c30d8aa9ab8.png)
But the zero year is just because it is a Birth entry.
The path "() in of in of" is also not showing correctly.

**Comment by suffolkroots** [comment]
Surely 0 year means no date whatsoever, as birthdate is accepted if no baptism date?

**Comment by edickens** [comment]
Yes.  So these should not be shown as 0 years.  E

**Comment by Sherlock21** [comment]
Firstly: Thank you for putting this into T3.

Secondly, here are my snags:-
zero dates action link needs to be reduced in with by making it wrap. - as in Place name or church name or dates fields. see attached. this result is that the action fields at the right are too restricted - to drop off the RH edge, needing one to scroll across. - extra keystrokes and disruption.
![date field width](https://user-images.githubusercontent.com/9368704/31583258-988187d4-b18f-11e7-9ed6-a0e150e3dd71.jpg)

**Comment by SteveBiggs** [comment]
Perhaps the wording on the button could be reduced to just "Zero Years".

Steve


Stephen Biggs
FreeREG Chairman

**Comment by Sherlock21** [comment]
Yes, Steve - and still wrap for greatest saving.

**Comment by edickens** [comment]
or "0 yrs".

**Comment by Sherlock21** [comment]
Comments of Zero Year Date - continued.

If there is a non date character in the Birth Date field then that already gave rise to as Dates Error flag.
NOW, this present mod is not working in the right order, and misses the None Date in the Baptism  field, as does not give rise to the Zero Date Error in the Batches list.

![zero dates 2](https://user-images.githubusercontent.com/9368704/31583525-93d352fc-b195-11e7-8302-cb82d9bf7e5d.jpg)


the file is: WRY/ericb.TSTUTF8.csv for you to look at the original file - fabricated fort this test.

**Comment by SteveBiggs** [comment]
As previously commented, where an entry has a birth date and no baptism date, this should NOT be flagged as a zero date - only one or the other is required. Some of the Sussex files on the production site show a '0' start date in the Transcriptions listing to the public where they have a birth date without a baptism date, suggesting this is a wider problem.

**Comment by SteveBiggs** [comment]
To reduce the column width I suggest that the header says 'Zero Year Entries' which will wrap to 3 lines of one word and the button just says 'Entries'.

**Comment by Sherlock21** [comment]
Bbased on my previous testing, the "Either/ Or" did work correctly.
SO I would suggest there is a real duff date somewhere, of the code has been changed since it was tested.

**Comment by SteveBiggs** [comment]
@Sherlock21 , I thought the same thing and spent a long time pouring over the file looking for the "duff" date, but there are none. When you click on the "Zero Entries" button it lists entries with a birth date but no baptism date:
![Capture.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588631f51e19621a00230146/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f02e7384e671e6162351580d4bac43585f45ffac8928f0a42062c80d55b98e30063e937f03a6aa8318b500bf218b4c85b0b5834cc9ec3f37aa.jpg)
However, you are right that other files with birth but not baptism dates do NOT flag up like this, so this is a strange file. If you want to check yourself, the file is SSXBOLBA2 under Sussex on Test3.

**Comment by edickens** [comment]
Have those files that are not flagged as errors got a space in the Baptism date field?

**Comment by SteveBiggs** [comment]
Eric, I'm not sure what you mean. There is nothing in the Baptism date field and you can't have just a space as this is rejected as a date error.

**Comment by Sherlock21** [comment]
Steve

I can not find these records in the downloaded file - so is it getting rtejected at upload?

the first person in your list below is in a search, for Burials on 12 Aug 1659.
Eric b

**Comment by SteveBiggs** [comment]
Sorry Eric,  the file is SSXBOLBA1 not 2.

**Comment by Vino-S** [comment]
Pushed the code to production.
