### ISSUE TITLE
File system is incomplete

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeUKRegProductIssues#992]
A transcriber has encountered an issue where by they cannot replace one of their files because the system does not have an original copy of the file. The situation is correct as the Physical File collection shows a non existent file 
![dinahst](https://user-images.githubusercontent.com/2874694/29242116-fa3594da-7f43-11e7-8529-6a0ce98acbdf.JPG)
A review of the file system shows that it does not exist nor is there an attic file.
![dinahst1](https://user-images.githubusercontent.com/2874694/29242123-2060a352-7f44-11e7-9504-553578cc1a91.JPG)
Comparing the actual file system files for this user shows 53 files while she own 91 uploaded files
![dinahst2](https://user-images.githubusercontent.com/2874694/29242138-60b7393e-7f44-11e7-91c4-00c5f9a28e5a.JPG)
All of the "missing files" appear to have been uploaded in the period around November 15 2015.
A review shows that the other servers have the same user files. There is an rsync task than copies the file system from colobus to the other servers.
Possible cause of the problem. In the event that colobus goes down mongodb automatically switches from colobus to brazza and continues serving users and transcribers. This is tranparent to them and to us. Ultimately when colobus becomes available again it resumes service as the master.
My hypothesis @lemon-ukgen is that there will be no rsync from brazza during the time it is running as primary and that when colobus resumes control it will rysnc from its own file system again and wipe out any files uploaded or processed during the time that brazza was in charge.
If this hypothesis is correct a possible solution is to move the file system to a different server; perhaps one or more of the mongodb servers and do some intellegent rsyncing between multiple copies. This would have a small benefit of further reducing the disc io load on colobus

**Comment by Sherlock21** [comment]
A swift bit of research there, Kirk!

How long do you estimate this "outage" might have been - if you have availability/running logs?
and so how many other people have got files missing for this reason from that single event, and from all other like events. 
I guess the mind boggles!

**Comment by Captainkirkdawson** [comment]
There have been a few outages of colobus over the years; length and dates are long gone from my memory banks. Really is pointless to speculate.
Need is for @lemon-ukgen to confirm/reject my hypothesis and to work out a long term solution to avoid. This is the most important part. 
As for recovery we can either spend 2-3 weeks fixing or do it on an ad hoc basis. The actual database contains the records and it will only become visible when an old file gets reloaded.

**Comment by Sherlock21** [comment]
The last sentence is the critical one, so if that is in fact the case after Lemon has his input, then I agree with you.... just carry on and fix it from happening in future.

shall I zap these 5 empty files then?

**Comment by Captainkirkdawson** [comment]
No wait for it to get flagged as an issue by the transcriber. Safer that way

**Comment by lemon-ukgen** [comment]
I don't believe we had a problem with colobus in November 2015.

There is risk of confusing two independent things here: MongoDB master and the "files master". MongoDB  switches as it sees fit. The "files master" is governed by HAProxy sending requests that generate file writes to a given server, which was colobus during this time. Then rsync pushes those writes out the other servers.

On the occasion colobus has failed we don't (intend to) do any file writes, so the files shouldn't end up on the non-master files servers. Actually changing the files master isn't something we do lightly; it has huge implications for the other projects (*).

But the rsync does run with `--delete`, so if they did end up on the wrong server they would get deleted since they'd be absent on the master.

For FreeREG2 the logic HAProxy uses to send requests to the master server has been a combination of `Administrator` cookie  plus a few Refinery URLs.

So it's possible that 

* HAProxy logic incorrectly sent this user's file upload request to the wrong server, and `rsync` then deleted it since it was not present on the master

* The request went to the master server and something went wrong.

We don't have FreeREG2 Apache or HAProxy logs that old. But there are other files from this user around the same time:

```
-rw-r--r--  1 webserv  webserv  127098 Nov 13  2015 KENROMBA16.CSV
-rw-rw-rw-  1 webserv  webserv    6983 Nov 18  2015 KENROMBU16.CSV
-rw-rw-rw-  1 webserv  webserv  134856 Nov 24  2015 KENROMBA17.CSV
-rw-rw-rw-  1 webserv  webserv  102908 Nov 24  2015 KENROMBU15.CSV
-rw-rw-rw-  1 webserv  webserv   53772 Nov 24  2015 KENROMBA18.CSV
```

I went looking in Errbit and [found](https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/56484f94e937902a44000009) a CSV-shaped exception for a file very similar to the one you mention, around the same time: https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009/problems/56484f94e937902a44000009.

( Errbit is a pain to search by date, here's the period in November 2015: https://errbit.freeukgen.org.uk/apps/56297e8be93790333a000009?all_errs=true&page=9 )

So I think it's more likely the second scenario.

Is it possible to get a list of all missing files for all users? It might help gauge the size of the problem here.

(*) History: FreeREG2 co-opts the file distribution mechanism from FreeBMD; since thats's what FreeREG1 did and re-using existing tooling kept things fast and simple. Moving FreeREG2 file storage elsewhere, or doing it differently, is possible but a significant piece of work to consider.

**Comment by Sherlock21** [comment]
Given the above comments by Lemon, I will Not go anywhere near the list of Processed but NO File" until you invite me to.

**Comment by Captainkirkdawson** [comment]
Thank you L. I withdraw my hypothesis and revert to facts.

The user Dinahst  has only 53 physical files occupying 4,290,425 bytes on
colobus (and other servers),

The oldest file there is KENROMBA16 for Nov 2015.

The attic files for this user shows that this user has been active since
Jan 2014.

This user has 90 files processed into the data base.

There are many uploaded and processed on 16 Nov 2015 including
KENROMBA3...BA9

We are missing 47 files in the physical system from this userid all prior
to Nov 2015

I will develop a rake task to determine the full extent of the problem.

K



Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by edickens** [comment]
Hi Kirk,
I'm not saying that it applies here, but consolidating, deleting duplicates, reducing the size, and renaming, can all be reasons for deleting files, which could be why files "go missing".
ED

**Comment by Sherlock21** [comment]
Just so that we who use these aspects of FR understand what happens in different cases, please just tell us:
If a user simply REMOVES a batch does that put the removed batch into the Attic eventually after the overnight cleanup has run? 
or actually remove without trace?

If DM uses the DELETE Original and all Associated.... option, does that do just the same as above, but instantly, OR does it do something more drastic as implied in the name, Including all the Attic entries of the same file number?

**Comment by Captainkirkdawson** [comment]
Ericd but then they would surely remove their duplicate etc. But this is
clearly not the case here.


Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Captainkirkdawson** [comment]
The user remove puts the original in the attic deletes the entry in the
files collection and overnight the entries and search records are removed
The DM delete in physical files does the above but in real time.
The DM remove in physical file removes the physical file entries but does
not touch the file or its records.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by Sherlock21** [comment]
Thankyou

much as I thought. but better safe than getting the wrong message

EB

**Comment by Captainkirkdawson** [comment]
A report of the processed files that do not have a file for them was prepared and distributed by email. There are 870 out of 53,503

In the report there is the date of the original upload and the date of the last processing of the file.

For those that have no dates there is no record of upload/processing most likely because they were processed before we started collecting this information in the physical file collection in late 2014

The vast majority (but not all) of these were processed in November 2015

**Comment by Sherlock21** [comment]
Very interesting.

SO, for this collection, do any of these files have a date-timestamp for processed, which is LATER than that of current ‘active’ file?
If any, then does that not mean that FR is behind what the Transcriber thinks is the latest data?.

And so these are the key ones to correct ( from the Transcriber presumably)

OR what do we do with those?
AND what do we do with the rest of the files where the timestamp is not later than the current one online

**Comment by Captainkirkdawson** [comment]
Sorry Eric you have totally lost me on that comment.

**Comment by Sherlock21** [comment]
I was thinking along the lines of how do we ensure that we have the latest copy of the file. 

And if the date timestamp on one of these 870 is later than that on the existing file that is active in the System ,then we are not using the latest one.
Or have I got the wrong angle on your list?

**Comment by Captainkirkdawson** [comment]
This is a listing of processed files that do not have a copy of the file so
I am afraid that one cannot answer your question about later or earlier.

Kirk Dawson
5220 Riverside Drive
Fairmont Hot Springs, B.C.
V0B 1L1

**Comment by lemon-ukgen** [comment]
I spent some time looking at the list provided.

Strangely, the file that's in the screenshots above, `KENROMBA4.CSV` is not in it!

Many of these missing files exist elsewhere in the FreeREG1/2 hierarchy. For example, `KENROMBA3.CSV` is listed as missing, but files with that name -- excluding `.attic` variants -- can be found:

```
freereg/saved/Dinahst/KENROMBA3.CSV
freereg/users/Dinahst/KENROMBA3.CSV
freereg2/freereg1/users/Dinahst/KENROMBA3.CSV
```

and this pattern is always the same. I don't know anything about how the transition worked, but this might at least provide a path to recover the original data? Of the 870 files listed, 129 are completely absent, the remainder exist as above. 

Other than that i'm not sure I have much more to add. Errbit has ~10 of CSV-shaped errors in November 2015 which suggests to me there were problems processing files during the period they're notably absent, but otherwise this is beyond the horizon of logs we retain. I can't find anything to suggest that the file storage or syncing itself is at fault though.

**Comment by Captainkirkdawson** [comment]
For your information L whenever a file is replaced or edited then the file as it was originally is placed in the ,attic so we always have a copy of the penultimate and earlier copies of the file. It provides a history of the evolution of the file. This was how FR1 worked as well.
The attic means that we can almost always recover the penultimate version if we need to.
I will leave it to the scrum to decide on any further action.

**Comment by lemon-ukgen** [comment]
Thanks for the explanation @Captainkirkdawson.

I'm removing myself from this issue, tag me back in if required.
